### ISSUE TITLE
autogen.sh

### ISSUE THREAD

**Issue by sbguthery** [opencog/link-grammar#1002]
After throwing ERROR! due to lack of development Python and noting that 'swig' is required to create bindings for Python2, autogen.sh ends with

A syntax error may mean you need to install 'autoconf-archive'.
After you fix the problem then run './autogen.sh' again.

Which is probably not what is intended since 1) autoconf-archive is installed on the machine on which autogen.sh is being run and 2) no syntax errors were noted.  I might also note in passing that config.log is not generated so one is hard-pressed to "See 'config.log' for more details".

This is on Ubuntu 18.04.2 LTS and for Link Grammar Version 5.5.0 cloned on 9/4.

Not a blocker, just an FYI.

**Comment by ampli** [comment]
Hi Scott,
Thanks for your report.

By now I have found out how to directly detect missing `autoconf` macros (i.e. not via heuristics due to errors caused by that, like done now, which are not so good as you noticed). I will eventually replace these error messages and others by an exact detection. Regretfully I don't have enough time to do that for the upcoming release (planned to be released in a few days).

**Comment by linas** [comment]
We should probably remove support for python2 -- It's marked EOL for January 1, 2020 -- 3 months away.

**Comment by ampli** [comment]
I plan to make a PR devoted to `configure.ac` fixes, and I will add that there too.

**Comment by ampli** [comment]
>> We should probably remove support for python2 -- It's marked EOL for January 1, 2020 -- 3 months away.

> I plan to make a PR devoted to `configure.ac` fixes, and I will add that there too.

I removed the `bindings/python3` directory and change `configure.ac` to configure only Python 3 (named `python` or `python3`).

**Comment by ampli** [comment]
I wrote:
> By now I have found out how to directly detect missing `autoconf` macros (i.e. not via heuristics due to errors caused by that, like done now, which are not so good as you noticed). I will eventually replace these error messages and others by an exact detection.

@lonas wrote:
>> We should probably remove support for python2 -- It's marked EOL for January 1, 2020 -- 3 months away.

I addressed these things in PR #1061 that I just submitted.
