### ISSUE TITLE
LinkGrammar.getLinkageSense and LinkGrammar.getLinkageSenseScore were removed from JNI but still present in Java API declaration

### ISSUE THREAD

**Issue by vsbogd** [opencog/link-grammar#1009]
`LinkGrammar.getLinkageSense` and `LinkGrammar.getLinkageSenseScore` java API method implementations were removed by commit https://github.com/opencog/link-grammar/commit/5249ddb99fb8fd33731b518029c31f316c1c552c#diff-acf5e8f599bb0954fb0aa69ba6293ce1 but they are still present in Java API declaration: https://github.com/opencog/link-grammar/blob/c304c4398557b8849da42e5a40c72cdb13db0758/bindings/java/org/linkgrammar/LinkGrammar.java#L120-L122

Because of this Java compiler cannot find that methods are absent during compilation, see https://github.com/opencog/relex/issues/283

**Comment by vsbogd** [comment]
In addition probably it makes sense to remove `storeSense` option from `LGConfig` API:
https://github.com/opencog/link-grammar/blob/c304c4398557b8849da42e5a40c72cdb13db0758/bindings/java/org/linkgrammar/LGConfig.java#L71-L78

**Comment by linas** [comment]
closing; the correct fix is to rip this stuff out of relex.
