### ISSUE TITLE
Crash when creating a linkage diagrams of extra-long sentences

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#101]
I started to modify linkage_print_diagram_ctxt() in order to allow long link names between words (that are now truncated). While doing that, I found the said crash problem.

The problem is the fixed size of the **picture** array, which its bounds are not checked.
Possible solutions:
1. On out-of-bounds,  return an empty string, an error message, or even a NULL, and also print an error message.
2. Truncate the picture on out-of-bounds + print an error message.
3. alloca() **picture**/**xpicture** using  **line_len** as the MAX_LINE dimension. However, I cannot see how to easily find, in advance, the MAX_HEIGHT  (max. **top_row**) dimension.  This can be solved with a realloc() in case of an out-of-bound **top_row**. (alloca() of an arary of pointers is needed.)

I think there is no point to implement (2) (it is just a complexity with no added value - there is no benefit in providing a truncated diagram).

The easy fix is (**1**). The remaining questions are the returned value in case of an error, and if an error message is printed, whether to print it only in verbosity>0.

I'm for returning NULL (current programs that are not careful to check returned UI values may crash on it, but they would crash anyway on extra-long sentences if they use the current library) plus an error message when verbosity>0.

Linas, please tell me which way to choose and I will send a pull request.

**Comment by ampli** [comment]
I finally implemented another solution, in the lines of the existing check of row overrun:
Just put an error message into the diagram string and return.

It does that when the sentence itself doesn't fit into a diagram line. This usually doesn't cause a crash, unless it is to fit into the last row. However, a sentence slightly longer than that would cause end of diagram lines to be written into the start of the next diagram line, which is not a good thing. So when this condition is detected, the following is put into the diagram string: "The diagram is too long.".

BTW, another bug happens with extra-long sentences: they cause a buffer overrun in **libedit** when it reads the history file which contains extra-long sentence. This happens with libedit-3.1-9.

**Comment by linas** [comment]
Ugh.  I suggest that you report this bug to the libedit folks.  You might
even want to provide  a patch, if you have time :-)

Buffer over-runs can be used to get root: if some SUID program is using
libedit, and you feed it that long line, or tamper with the history buffer,
then you will get root on that machine.  So technically, this could even be
a CVE

**Comment by ampli** [comment]
I found the problem in libedit. It is due to an off-by-one comparison in a condition that allocates a bigger buffer, and can happen with any line length. It exists in the current dev. CVS, and hence I sent a bug report, with a fix.
http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=49683
(Unfortunately I didn't know they don't allow line folding on display...)

**Comment by linas** [comment]
fwiw we use libedit because it was compatible with the BSD license. But since that's not an issue any more, we could use readline. It might be .. ? better?   Support for utf8 in libedit has been spotty, readline I assume is better for this.

**Comment by ampli** [comment]
Regretfully readline is under GPL, and not LGPL (see http://en.wikipedia.org/wiki/GNU_Readline).
So using it would put the link-parser program under GPL. This doesn't matter for the LG library itself, but I think it is best not to put anything in the project under GPL.

BTW, the maintainer of libedit handled my bug report and promptly fixed the problem (first by a bogus fix, but then he changed it to a good fix).

I made some searches but have not found yet another line-editing library that also supports Unicode.

**Comment by linas** [comment]
well, the problem is that it takes years for the fixes to bubble up to the distros.

For example: the utf8 support was there for, .. I dunno 4-5 years already, but it needed a compile-time flag to be turned on, (it was off by default) and the distro's forgot to turn it on (all of them: ubuntu, redhat, debian).   I told them about this, so they fixed it .. at first, incorrectly, and so another 6-9 months lost.   For example, if I remember, its missing in ubuntu 14.04 LTS and will remain missing for years, until the next LTS.
