### ISSUE TITLE
Segmentation fault when running make check on macOS

### ISSUE THREAD

**Issue by le-big-mac** [opencog/link-grammar#1015]
I'm attempting to install link-grammar for use with Python on macOS Mojave but when I run make check I get a segmentation fault. The commands I run are:

```
./configure --disable-java-bindings --enable-python-bindings
make
make check
```
and the error message received is:
```
Making check in python-examples
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
../../test-driver: line 107: 22038 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: tests.py
============================================================================
Testsuite summary for link-grammar 5.7.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See bindings/python-examples/test-suite.log
Please report to https://github.com/opencog/link-grammar
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```
The contents of `bindings/python-examples/test-suite.log` is just:
```
=================================================================
   link-grammar 5.7.0: bindings/python-examples/test-suite.log
=================================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests
===========
```
Any help with this issue would be much appreciated.

**Comment by ampli** [comment]
My guess is that this is a python bindings problem.
Which python do you use? (Python from Anaconda doesn't work with LG).
Try to use python3 from Homebrew (it works for me).
Also configure with `--enable-python-bindings=3` so only python version 3 will be configured and the tests will be performed using it. This is because python version 2 will not be supported by LG soon.
In any case try to see what happens if you "import linkgrammar" from python.

**Comment by le-big-mac** [comment]
Thank you for your answer, uninstalling and reinstalling python3 through Homebrew seems to have solved the problem.

**Comment by asdasd1dsadsa** [comment]
> My guess is that this is a python bindings problem. Which python do you use? (Python from Anaconda doesn't work with LG). Try to use python3 from Homebrew (it works for me). Also configure with `--enable-python-bindings=3` so only python version 3 will be configured and the tests will be performed using it. This is because python version 2 will not be supported by LG soon. In any case try to see what happens if you "import linkgrammar" from python.

`--enable-python-bindings=3` works for me, thx.
