### ISSUE TITLE
unable to install link-grammar on my unbuntu-bionic

### ISSUE THREAD

**Issue by zloker** [opencog/link-grammar#1094]
after "make check" command i have next output>
make[1]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/link-grammar'
make[2]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/link-grammar'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/link-grammar'
make[1]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/link-grammar'
Making check in bindings
make[1]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings'
Making check in java-jni
make[2]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/java-jni'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/java-jni'
Making check in ocaml
make[2]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/ocaml'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/ocaml'
Making check in python
make[2]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python'
Making check in python-examples
make[2]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
make  check-TESTS
make[3]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
make[4]: Entering directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
FAIL: tests.py
============================================================================
Testsuite summary for link-grammar 5.8.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See bindings/python-examples/test-suite.log
Please report to https://github.com/opencog/link-grammar
============================================================================
Makefile:600: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
Makefile:706: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
Makefile:775: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings/python-examples'
Makefile:438: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/vagrant/link-grammar/link-grammar-5.8.0/bindings'
Makefile:550: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

What's wrong and how can i solve this problem to install it correctly with python bindings

**Comment by ampli** [comment]
Hello @zloker,
Please send your `bindings/python-examples/test-suite.log` file.

**Comment by zloker** [comment]
Thank you for replying! I kinda solved my problem, i had the same problem that mentioned here https://github.com/opencog/link-grammar/issues/858 "Error: Failed to open dictionary 'demo-sql'", so i just disregarded it. 
I also had a problem that my python wasnt able to connect to linkgrammar lib, but i just added it to PATH as mentioned in next  issue (export PYTHONPATH=/usr/local/lib//usr/local/lib/python3.6/site-packages/lingrammar)
 https://github.com/opencog/link-grammar/issues/493
