### ISSUE TITLE
Using with Python3. ImportError: No module named alert

### ISSUE THREAD

**Issue by mahmoud-houri** [opencog/link-grammar#1096]
Dear All:
I am trying to install TENNISON coordinator in Ubuntu 20 LTS, the below error is appeared
![Untitled](https://user-images.githubusercontent.com/63161829/81109356-a352e400-8f22-11ea-9b8d-63846c2a1b96.jpg)
.

**Comment by linas** [comment]
What does this have to do with link grammar? I think you wanted this: https://github.com/SDN-Security/TENNISON/tree/master/coordinator

**Comment by mahmoud-houri** [comment]
thanks for your reply,I tried to install all app requirements in the article above, but the error still exit

**Comment by linas** [comment]
sorry, is link-grammar a requirement for this app? I find it hard t believe that it is ... again, I think you are posting to the project. @mahmoud-houri
