### ISSUE TITLE
OpenSSL error on Ubuntu 20.04 LTS while installing

### ISSUE THREAD

**Issue by omar-3** [opencog/link-grammar#1098]
I'm trying to install ```Link-Grammar``` using the command ```octool -rdcpav -l default``` that supposedly would install everything.

After build everything I guess, It starts to install ```Link-Grammar``` and that happens

```
[octool] Installing Link-Grammar....
--2020-06-13 10:09:36--  http://www.abisource.com/downloads/link-grammar/current/
Resolving www.abisource.com (www.abisource.com)... 130.89.149.216
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.abisource.com/downloads/link-grammar/current/ [following]
--2020-06-13 10:09:37--  https://www.abisource.com/downloads/link-grammar/current/
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:443... connected.
OpenSSL: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
Unable to establish SSL connection.
```

I asked on StackOverflow [here](https://stackoverflow.com/questions/62357205/openssl-cant-establish-ssl-connection-because-unsupported-protocol/62359497#62359497), but unfortunately it didn't work.

What to do?

**Comment by linas** [comment]
well, technically, this is an octool bug, not a link-grammar bug.  I think that it is strange that the first time, when it gets a successful 302 response, it uses http and the second time, when it fails, it uses https 

The normal way to debug this would be to turn on the verbose flag on the download tool, and see why protocol negotitation fails.

**Comment by linas** [comment]
Could you re-open this issue here: https://github.com/opencog/ocpkg/issues -- that is the component that contains `octool`.

**Comment by omar-3** [comment]
> well, technically, this is an octool bug, not a link-grammar bug. I think that it is strange that the first time, when it gets a successful 302 response, it uses http and the second time, when it fails, it uses https
> 
> The normal way to debug this would be to turn on the verbose flag on the download tool, and see why protocol negotitation fails.

Yes I tried that and it uses very weird and deprecated certificates

**Comment by linas** [comment]
oh, the link-grammar site? Hmm let me look

**Comment by omar-3** [comment]
see the stackoverflow question I attached above

**Comment by linas** [comment]
I've contacted the website owner. A temporary work-around would be to use http not https during download.

**Comment by linas** [comment]
See also https://github.com/opencog/ocpkg/issues/150

**Comment by AntonKomir** [comment]
Hi, @linas. Are there any updates? I've faced the same issue. I'm a beginner in Linux systems and python, so for me it's a bit hard to work-around with HTTP in installation scripts, sorry. Great thanks for working on this issue.

**Comment by linas** [comment]
The site maintainer is working on it; apparently, it has something to do with the newer clients not using some of the older encryption protocols. I'm not sure why this is difficult to fix, but the site maintainer implied it was ...

**Comment by linas** [comment]
The site maintainer reworked page serving so that TLS 1.2 now works on abisource.com. So I'm closing this ...

It may be unstable, and I will start working on a new long-term site for link-grammar real soon now.
