### ISSUE TITLE
Entries listed can be truncated if too long. 

### ISSUE THREAD

**Issue by JoelSund** [opencog/link-grammar#1199]
<img width="683" alt="Sans titre" src="https://user-images.githubusercontent.com/6420434/116412958-3843a100-a848-11eb-9055-d1d95e6cf2e7.png">

Hello,
Low priority bug.
In !link=1 mode,  entries listed can be truncated if too long.

**Comment by linas** [comment]
Please try to avoid posting gifs into bug reports,. They are hard to read, and impossible to cut-n-paste.

This is not a bug; the printing uses fixed width columns, and you are simply overflowing the printing width.  Parsing is not affected in any way.

These are informational prints, useful only for casual debugging sessions; these prints are not a part of the API. The API will return the the full-length strings.

You can find the API documentation here: 

http://www.abiword.org/projects/link-grammar/api/index.html 

There is a handful of new and quasi-experimental functions that might not be documented there: these are in 

https://github.com/opencog/link-grammar/blob/master/link-grammar/link-includes.h
