### ISSUE TITLE
List of missing words

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#12]
I gathered words, mostly from LG source comments and from my  posts, that are missing in the LG English dictionary. In many cases, all/some of their possible variants are missing two.

I included only words that are found in one of:
http://www.oxforddictionaries.com
http://www.merriam-webster.com
Many other words, like "racey" and "unoptimized" don't appear there so they are not included.

blender
post-process
splitter
indices
prepend
backslash
call-out
catenation
catena
deallocated
globalization
deletable
descenders
descender
disjunction
enqueue
dequeue
entropies
extern
initialization
optimizations
optimization
paren
parens
preprocessor
propagations
reentrant
relicense
splitter
sublicense
subsumption
Unicode
unordered
unreached
unuseful
unusefulness
breakpoint
checkpoint
identifier
disinformation

**Comment by linas** [comment]
pull request #225 adds everything discussed above, I believe. Am closing this.
