### ISSUE TITLE
`prune_lookup_list()` (and also `abridged_lookup_list()`)

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1205]
[`prune_lookup_list()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L573-L608) uses [`dict_match()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L548-L564) in order to remove any Dict_node that doesn't match the bare word of the search string  or is an exact match.
However, the existence of such nodes looks impossible, as [`rdictionary()`]( https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L631-L662) create a `Dict_node` element only for search strings with matching bare words or a whole word (when `dict_order()` returns 0).

`dict_order()` can be one of 3 functions:
1. [`dict_order_bare()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L486-L507)
2.  [`dict_order_wild()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L532-L544)
3. [`dict_order_strict()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L455-L473) (in the ifdef'ed-out `strict_lookup_list()`)

All of these functions only return 0 if the string matches a bare word or the whole word.

So the question is why `prune_lookup_list()` is needed at all.
If it is indeed not needed I would like to remove it.

**Comment by ampli** [comment]
When [`make_connector()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L956-L1035) finds a word at the RHS of a dict definition, it looks it up in the dict.
It uses [`abridged_lookup_list()`](https://github.com/opencog/link-grammar/blob/5ded3151ee33f880fdd12fa1d27705c539dad473/link-grammar/dict-file/read-dict.c#L739-L757) (from the "old times"), which, when given an unsubscripted word, returns matching dict words with matching bare word.
Then there is an `strcmp()` to find an exact match if any.
I think that `strict_lookup_list()` can be used instead (or `abridged_lookup_list()` can make a strict lookup - it is the only place in which it is used)` and save the `strcmp()`, which is done for each macro.

(This is a small saving but I found several possible savings in the dict lookup code.)

**Comment by linas** [comment]
I know of no reason for this. It's legacy code. None of the opencog projects make use of this or depend on it as a side-effect. Seems safe to remove.

**Comment by ampli** [comment]
In PR #1207, `prune_lookup_list()` has been removed and `abridged_lookup_list()` has been changed to `strict_lookup_list()`.
