### ISSUE TITLE
Installing link-grammar on RaspberryPi

### ISSUE THREAD

**Issue by ylee-kr** [opencog/link-grammar#121]
I'm installing the link-grammar library on my RaspberryPi, and everything looks ok except Python bindings.
When configuring, I enabled the option for python binding but Python says 
"/usr/local/lib/python2.7/dist-packages/linkgrammar/_clinkgrammar.so: undefined symbol: parse_options_set_display_morphology" after importing linkgrammr module.
Is there anything that I missed when installing the library?

**Comment by ylee-kr** [comment]
Sorry for bothering you. This was due to liblink-grammar4 that I installed to use pylinkgrammar.

**Comment by linas** [comment]
the python bindings are built-in to the current LG release.
