### ISSUE TITLE
Dict_node::Word_file 

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1219]
Note the `Word_file` filed of `Dict_node`:

https://github.com/opencog/link-grammar/blob/5cb9e68e553b6ba39f17b021cdd13b6c6105a414/link-grammar/dict-common/dict-structures.h#L114-L120
https://github.com/opencog/link-grammar/blob/5cb9e68e553b6ba39f17b021cdd13b6c6105a414/link-grammar/dict-file/word-file.h#L17-L21

It shows the file in which `Word_file::string` appears. The `next` field is not used here (it is for memory management only). So I wonder why a "`char *` filed for the file name is not used instead.

Also, note that `dictionary_lookuip_list()`, `dictionarty_lookup_wild()` and `Dict_node` are in the API, but `Word_file` is not. This makes it impossible to access the file name (e.g. in a Python `link-parser` equivalent, or in `tests.py`).

**My proposal:**
In `Dict_node`, replace `Word_file * file` by `char * file` (no backward compatibility problems in that).

**Comment by linas** [comment]
From what I can tell, it is used in only one place: `dict-common/print-dict.c:` line 1195 ... is this really needed or useful?

There only other place where it is used is in some stubbed-out, dead code: `dict-common/dict-common.c`  -- line 257 

Maybe it would be best to just remove it completely?

**Comment by ampli** [comment]
It is printed in the results of the `!` command of `link-parser`:
``` text
 linkparser> !!test
Token "test" matches:
    test.n                       10309  disjuncts <en/words/words.n.1-const>

    test.v                      116094  disjunct
...
```
It seems useful, and anyway, I just changed it to `char * file` and everything works fine, including new tests that check `dictionary_lookup_list()`. So I propose to leave it there.

**Comment by linas** [comment]
OK, sure.

**Comment by ampli** [comment]
> **My proposal:**
> In `Dict_node`, replace `Word_file * file` by `char * file` (no backward compatibility problems in that).

To be fixed in the next PR.
