### ISSUE TITLE
Omitted "if"s

### ISSUE THREAD

**Issue by stephenfrechette** [opencog/link-grammar#1240]
Found another unusual construction.

"if" can be omitted with subject-auxiliary inversion, but only in the subjunctive with "were", "had", and "should"

`I would have done that were he with me.
I would have done that had he come with me.`

These are the only three verbs I can think of where it is natural do to this.

**Comment by stephenfrechette** [comment]
Also of note forming a negative contraction with these never seems to be natural as well.

**Comment by linas** [comment]
Interesting. Issue #224 tries to deal with phantom words in general. Yet here is a case where the phantom word is forcing a subject-verb inversion.

**Comment by linas** [comment]
`I would have seen you, had you been there`  seems to work already. I'm reviewing.

**Comment by linas** [comment]
Works with the comma:
`I would have done that, had he come with me.`

**Comment by linas** [comment]
Closing, this has been fixed. The primary fix was to allow the verb "done" to be used in this conditional form. Assorted other minor fixes adjusted parse ranking, so that the correct form would come first.

**Comment by linas** [comment]
If you have other constructions that aren't working, list them here. I just noticed that `I would have said so, were he around` -- the fix is for `said` .. I'll do that shortly.

**Comment by linas** [comment]
There are some other action verbs that might need this fix: `I would have [action], were he ...`  I checked a few I could think of, but not exhaustively. The fix is to add `(O+ & <mv-coord> & I*j+)` to those verbs.

**Comment by linas** [comment]
To get the fixed version, get the `4.0.dict` file (only) from github, here: https://raw.githubusercontent.com/opencog/link-grammar/master/data/en/4.0.dict and copy it to your install location, usually `/usr/local/share/link-grammar/en/4.0.dict` and this will provide the above fixes
