### ISSUE TITLE
Porting `link-generate` to MS Windows

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1266]
> From: Dennis

> With VS I get errors in generator-utilities.c, mainly to do with [nwords] capture and cclist/cclen , and that's after I located and placed versions of argp.h and getopts.h (gcc header files)

> I do know it's a Work-In-Progress but if you have time or inclination, can you get a version of the link-generator working to compile with VS x64 ?

@linas,
I can do it by adding `argp` as a submodule under the `msvc` directory and also fixing the indicated VLA problem.
If this seems right I will send a PR.

**Comment by linas** [comment]
Sure .. I don't see any problem with this. You're good with this stuff; you know what you're doing.  I'm not even sure why you're asking, other than to say "Hi!" and, well, I guess they don't say "Merry Christmas" in Israel, I assume they say "Happy Hanukah" ... these are probably inappropriate comments for a github issue, but hey... (Delete this if it makes you feel nervous. I don't generally respect "boundaries", as they are called. )

**Comment by ampli** [comment]
I just wanted to be sure my solution of adding `argp` as a GitHub submodule seems reasonable (as opposed to adding the source code itself like the current `minisat`, or leaving it for the users to download/compile like previously done with regex).
BTW, here people usually just say "Happy Holliday" when they refer to Hanukah or any holiday, without explicitly mentioning which holiday.

**Comment by linas** [comment]
Oh. "git submodule" ... that's different. I'm not sure I like them, it make creating tarballs hard. But you are proposing this as an MSVC thing only; are all MSVC uses going to build from git, instead of from tarballs? 

How big is argp and getopts?  If it's just 2-4 files, just copy them. It's not like you need to do a git pull to get the actual latest and newest update.  It wont have a lot of churn.

**Comment by ampli** [comment]
I think it is preferable to let them build from both. But building from git is more reasonable, as the Windows port is not always well checked before a release so a working version is needed to be taken from GitHub (after a fix).

Only argp is needed (not getopt). It is ~300K. See for example https://github.com/ericonr/argp-standalone . It is about 15 C files.

In any case, it is only a small fraction of the tarball size. So the easiest way is to just include is a subdirectory of `msvc`.

**Comment by linas** [comment]
Wow! I suppose it's an annoying question, but maybe it would be easier to use ordinary `getopt`, which I assume is available by default with MSVC?

**Comment by linas** [comment]
Do you need the sophistication?

**Comment by ampli** [comment]
The main benefit of using `argp` in our case is that no changes are needed to `link-generate.c`. For using `getop` all the argument handling should be rewritten. However, this would be most probably easier than setting `argp` for MSVC. So I can try that.

**Comment by linas** [comment]
Your pick. ...

**Comment by DennGru** [comment]
Hi Amir and Linas,
Anytime you would like me to test a port of link-generate with windows and/or with MS Visual Studio for compiling, let me know.
Dennis in Tasmania
