### ISSUE TITLE
afdict_to_wide fails to read the dictionary files whlie called from Python bindings.

### ISSUE THREAD

**Issue by wvxvw** [opencog/link-grammar#128]
I tried to investigate the problem a little bit, and modified the error message to output more info:

``` c++
        wchar_t wstr[3];
    w = mbsrtowcs(wstr, &pqs, 3, &mbs);
    if (0 > (int) w) /* mbsrtowcs returns ((size_t) -1) on error */
    {

        prt_error("Error: Affix dictionary: %s: (%d) (%s) (%d) "
                  "Invalid utf8 character\n", afdict_classname[classno], 
                  (int)w, pqs, wstr[0]);
        return false;
    }
```

This is the part of the function that fails, and here's an example Python code that calls it:

``` python
>>> foo = linkgrammar.Sentence(u"This is a test sentence", linkgrammar.Dictionary(), linkgrammar.ParseOptions())
link-grammar: Info: Dictionary found at ./data/en/4.0.dict
link-grammar: Error: Affix dictionary: QUOTES: (-1) («»《》【】『』`„“) (34) Invalid utf8 character

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/linkgrammar/linkgrammar.py", line 341, in __init__
    self._obj = clg.sentence_create(self.text, self.dict._obj)
TypeError: in method 'sentence_create', argument 1 of type 'char *'
```

If I remove the line with the quotes from the dictionary, the code will choke on the next entry (the bullets) and so on. The file isn't corrupt and the angle quotes are a perfectly valid Unicode characters. If I copy the bytes and they try to interpret them as UTF-8 encoded text, it works (in Python):

``` python
>>> quotes = b"\x22\x22\xc2\xab\xc2\xbb\xe3\x80\x8a\xe3\x80\x8b\xe3\x80\x90\xe3\x80\x91\xe3\x80\x8e\xe3\x80\x8f\x60\xe2\x80\x9e\xe2\x80\x9c\x22\x3a\x20\x51\x55\x4f\x54\x45\x53\x2b\x3b"
>>> quotes.decode('utf-8')
'""«»《》【】『』`„“": QUOTES+;'
```

**Comment by ampli** [comment]
Try to add at the start of your Python program:
`locale.setlocale(locale.LC_ALL, "en_US.UTF-8")`

**Comment by wvxvw** [comment]
Thanks @ampli this solved the error related to loading dictionary, but this didn't solve the other part:

``` python
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "en_US.UTF-8")
'en_US.UTF-8'
>>> import linkgrammar
>>> foo = linkgrammar.Sentence(u"This is a test sentence", linkgrammar.Dictionary(), linkgrammar.ParseOptions())
link-grammar: Info: Dictionary found at ./data/en/4.0.dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/linkgrammar/linkgrammar.py", line 341, in __init__
    self._obj = clg.sentence_create(self.text, self.dict._obj)
TypeError: in method 'sentence_create', argument 1 of type 'char *'
```

This looks like an incorrect binding to me, probably that shouldn't be a `char *` but some Python object, or am I wrong?

**Comment by ampli** [comment]
Just omit the `u` prefix.

**Comment by wvxvw** [comment]
@ampli Thanks! this indeed worked, but:

``` python
>>> help(linkgrammar.Sentence)
Help on class Sentence in module linkgrammar.linkgrammar:

class Sentence(__builtin__.object)
 |  Methods defined here:
 |  
 |  __del__(self)
 |  
 |  __init__(self, text, dict, parse_options)
 |      In python 2.x, txt should be unicode string like u'Bo-bo-bo'
...
```

This is exactly the opposite of what documentation says to do! ;)

**Comment by ampli** [comment]
It looks like a documentation problem.
To see what actually works, look at `bindings/python-examples/tests.py` .

**Comment by linas** [comment]
There's also a different, unresolved problem: the code in github has a completely differrent set of redesigned, new improved bindings, that are not compitable with the ones in the last tarball release. I'm not quite sure what to do about that.  Perhaps it would be bet to give the new bindings a new name...

**Comment by wvxvw** [comment]
@ampli Thanks, will do. @linas I never used the old bindings, so I can't tell I've built these this evening from Github repo.

**Comment by linas** [comment]
OH, OK. The github repo currently does not have the old bindings in it (and that's the problem..)

**Comment by ampli** [comment]
Maybe the new binding can be provided for Python 3, and the old ones retained for Python 2.7?

**Comment by linas** [comment]
That sounds like a good idea ... --linas

**Comment by ampli** [comment]
> wvxvw commented on May 23
This is exactly the opposite of what documentation says to do! ;)

Just now I sent a pull request #167, that removes the misleading comment.
I also added a detailed usage message.

--
> That sounds like a good idea ... --linas

I will look at it.

**Comment by ampli** [comment]
The current bindings can be ported to Python 3 with only few modifications.

Since they already work fine in Python 2, I wonder maybe is a good idea to
leave these bindings also for Python 2,
i.e. to provide for it both the old bindings and the new ones.
There see 3 problems with that:
1. We will need to use a different module name for each binding.
2. Maintaining a total of 3 library versions instead of only 2 (for Python
2 and 3).
3. Confusion: It will not be clear to which bindings one refer to by
"Python 2 link-grammar bindings".

So the question is whether it is desired to provide both the old and new
bindings for Python 2,
or just provide the new bindings for Python 3 only.

2015-08-12 5:46 GMT+03:00 Linas Vepštas <notifications@github.com>:

**Comment by linas** [comment]
How about new for python3 ... that would solve the compatibility problem
that the new bindings introduce...

**Comment by ampli** [comment]
>How about new for python3 ... that would solve the compatibility problem
that the new bindings introduce...

Yes. In any case I would like to provide the new bindings for python3, and re-provide the old bindings for python2.

My question was weather to provide the new bindings also for python2, just because they already work for python2 as they are.

**Comment by linas** [comment]
I dunno.  No one here seems very excited about this one way or the other ...

--linas

**Comment by ampli** [comment]
I currently think that after all, it will not be a good idea to revive the old Python2 bindings, due to the extra work needed for maintaining (including testing) two different bindings.

If there are still issues relating to the discussion here,  they should be reopened as new issues.

So I'm closing this issue.
