### ISSUE TITLE
www.abisource.com certificate is expired

### ISSUE THREAD

**Issue by chenrui333** [opencog/link-grammar#1339]
```
$ curl -I https://www.abisource.com/
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```

<img width="470" alt="image" src="https://user-images.githubusercontent.com/1580956/184578388-8d5c4917-8e08-4e13-a79e-9042cf98e7ba.png">

**Comment by linas** [comment]
Can you do me a favor? Can you please contact the #abiword chanel on IRC? On the Libera.chat network, I believe. (or is it gnome.org IRC?) This has been a recurring issue, and I feel a bit exhausted in pestering them about this.

**Comment by linas** [comment]
closing. The abiword.com domain is gone. The DNS records for it are gone. the website is now hosted here, on github.
