### ISSUE TITLE
incorrect use of pcre2_match_data would result in severe memory leak

### ISSUE THREAD

**Issue by carenas** [opencog/link-grammar#1366]
A `pcre2_match_data` is designed to be allocated and free when no longer used, which is why is an opaque type and the API doesn't provide a "copy" method.

The following incomplete (will need at least syntax changes to support MSVC) code, changes the way the reusing of pcre2_match_data was done, to at least ensure it was really reusable within a thread and prevents `tests/multi-thread` to explode on size as a result of leaking frames on each match when using PCRE2 >= 10.41, but still doesn't do the necessary free.

```
$ git diff
diff --git a/link-grammar/dict-common/regex-morph.c b/link-grammar/dict-common/regex-morph.c
index 4ca172f3f..1e90036c9 100644
--- a/link-grammar/dict-common/regex-morph.c
+++ b/link-grammar/dict-common/regex-morph.c
@@ -167,22 +167,9 @@ static void reg_free(Regex_node *rn)
 #if HAVE_PCRE2_H
 
 #define ALLOCTE_MATCH_DATA(var) \
-       pcre2_match_data *var = \
-       memcpy(alloca(re_md_template_size), re_md_template, re_md_template_size)
-
-static unsigned int re_md_template_size;
-static pcre2_match_data* re_md_template;
-
-#if HAVE_THREADS_H
-static once_flag call_once_flag = ONCE_FLAG_INIT;
-#endif // HAVE_THREADS_H
-static void alloc_match_data(void)
-{
-       re_md_template = pcre2_match_data_create(MAX_CAPTURE_GROUPS, NULL);
-       if (re_md_template == NULL)
-               return;
-       re_md_template_size = pcre2_get_match_data_size(re_md_template);
-}
+       static __thread pcre2_match_data *var; \
+       if (!var) \
+               var = pcre2_match_data_create(MAX_CAPTURE_GROUPS, NULL);
 
 static bool reg_comp(Regex_node *rn)
 {
@@ -196,20 +183,7 @@ static bool reg_comp(Regex_node *rn)
        re->re_code = pcre2_compile((PCRE2_SPTR)rn->pattern, PCRE2_ZERO_TERMINATED,
                                    options, &rc, &erroffset, NULL);
        if (re->re_code != NULL)
-       {
-#if HAVE_THREADS_H
-               call_once(&call_once_flag, alloc_match_data);
-#else
-               alloc_match_data();
-#endif
-               if (0 == re_md_template_size)
-               {
-                       prt_error("Error: pcre2_match_data_create() failed\n");
-                       free(re);
-                       return false;
-               }
                return true;
-       }
 
        /* We have an error. */
        PCRE2_UCHAR errbuf[ERRBUFFLEN];
```

**Comment by linas** [comment]
Thanks for the bug report. What is the actual symptom? What is the error that you see? And what operating system is this?

I don't quite understand that the problem is ... I would have assumed that every time `pcre2_match_data_create(MAX_CAPTURE_GROUPS, NULL);` is called, it returns *exactly* the same value!  Does it secretly contain offsets that are location dependent?  Because I cannot think of any other reason why the current code would fail.

**Comment by linas** [comment]
I just checked. On Debian stable, `libpcre2-dev:amd64` version `10.36-2+deb11u1`, I get that the size of the alloced structure is always 240 bytes long, the first two words are pointers, differing by 16, the next two words are zero (for a total of 32-bytes), followed by uninitialized garbage. So I don't really see what the problem is ...

**Comment by carenas** [comment]
> What is the actual symptom? What is the error that you see? And what operating system is this?

`make check` fails after `multi-thread` is killed by the OOM in a Linux/arm64 system with 4GB.
After the fix `multi-thread` goes back to use about a max of 870MB.

I'd seen also the misbehavior (but won't trigger an OOM) in bigger Linux and macOS x86_64 systems, if linked with PCRE2 >= 10.41.

> I don't quite understand that the problem is ... I would have assumed that every time `pcre2_match_data_create(MAX_CAPTURE_GROUPS, NULL);` is called, it returns _exactly_ the same value! Does it secretly contain offsets that are location dependent? Because I cannot think of any other reason why the current code would fail.

The problem is that starting with PCRE2 10.41, 20KB of heapframes are allocated and attached to the match_data; those are used when `pcre2_match()` is called (unless JIT is used), since you were never calling `pcre2_match_data_free()` in your match_data will leak those.

**Comment by linas** [comment]
Reviewing the implementation: 

The struct is defined here:

https://github.com/PCRE2Project/pcre2/blob/d90fb23878eeb8bcb5153b1ebb23948e7de8cf34/src/pcre2_intmodedep.h#L654

It is malloced here:

https://github.com/PCRE2Project/pcre2/blob/52c08847921a324c804cabf2814549f50bce1265/src/pcre2_match_data.c#L58

and the malloc function is here:

https://github.com/PCRE2Project/pcre2/blob/7c49b40e8aed10cc2667dd3c4b7bb692d13ade2a/src/pcre2_context.c#L86

and all of this looks to be 100% harmless ...

**Comment by linas** [comment]
> The problem is that starting with PCRE2 10.41, 20KB of heapframes are allocated and attached to the match_data;

Ahh. OK, that explanation makes sense. (Although it is disappointing. Mallocs are expensive, and the goal here was to avoid pointless mallocs, since we know we are going to be coming back to the same place, over and over.)

Out of curiosity, you said `linux/arm64` -- is this linux running on an Android? I' ask because Im looking for a genius who can make guile run on Android.  I've been repeatedly told that this is  a problem...

**Comment by linas** [comment]
Pull req #1367 should fix this.

**Comment by ampli** [comment]
PCRE2 supports defining a private memory allocator function for `pcre2_match_data_create()`, so I added to my todo list:
Try a private memory allocator for pcre2_match_data_create() to see if there is any speedup.

**Comment by linas** [comment]
> Pull req #1367 should fix this.

Not yet. It's still leaking memory. Apparently, using the `pcre2_match_data` struct more than once results in a memleak. A fresh copy has to be alloced for *each* call to `pcre2_match` ... working to fix that now.

**Comment by linas** [comment]
> private memory allocator

Nahh. All that will happen is that  it will call the private allocator, instead of `malloc()`. Unless the private allocator is magically faster, nothing will be gained.

**Comment by ampli** [comment]
I hoped to be able to define a simple private allocator that uses a pre-allocated TLS block.

**Comment by linas** [comment]
@ampli can you look at this? Master, pull req #1367 and #1368 -- all three appear to leak memory at about the same rate.  It is not regex related; its something else.  I expose this by doing this:
```
--- a/tests/multi-thread.cc
+++ b/tests/multi-thread.cc
@@ -139,7 +139,7 @@ int main(int argc, char* argv[])
        }
 
        const int n_threads = 10;
-       const int niter = 500;
+       const int niter = 50000;
        Parse_Options opts[n_threads];
 
        printf("Creating %d threads, each parsing %d sentences\n",
``` 
and then running `make check` and watching `top`. 

There is another unrelated issue --  I don't understand what pcre2 version 10.41 and newer is expecting me to do. Is #1368 the correct fix? or is #1367 good enough?  Could we just keep a pool  of `pcre2_match_data` in the dict, and just reuse them forever? Or will that leak?

**Comment by linas** [comment]
It's late at night; I'm done for now.

**Comment by carenas** [comment]
Using the match_data more than once is OK, and indeed encouraged, that way the heapframes will be reused over and over (we allocate 20KB and the matches I'd seen in multi-thread require less than 3KB)

You MUST call pcre2_match_data_free() eventually though, or the memory allocated for that (including the heapframes) will leak.

the match_data can't be used concurrently by multiple threads, hence why my suggested code was using a TLS variable that was still static, so therefore shared (sequentially) by all matches that are done by the same thread.

using a pool of them would also accomplish that, just remember to create each of them with `pcre2_match_data_create()` and then eventually free when done with them and will be leak free.

**Comment by linas** [comment]
Thank you @carenas  The simplest solution then seems to be to be to call `tss_create` and pass `pcre2_match_data_free()` as the argument. I'll do that shortly. 

@ampli I ran `valgrind --leak-check=full  ./tests/.libs/multi-thread` overnight and it says that no memory was leaked. Since RAM usage keeps growing, I can think only of two explanations: fragmentation, or some pool is misbehaving.

**Comment by linas** [comment]
Again thanks. I did a detailed study of mem usage and report on the results here: https://github.com/opencog/link-grammar/discussions/1373
