### ISSUE TITLE
LICENSE file mentioned twice in README

### ISSUE THREAD

**Issue by ryandesign** [opencog/link-grammar#1489]
The LICENSE file is mentioned twice in the README's Contents section:

https://github.com/opencog/link-grammar/blob/3a2612761f17e2579cb213a02aa1cef394f98763/README.md?plain=1#L254-L259

https://github.com/opencog/link-grammar/blob/3a2612761f17e2579cb213a02aa1cef394f98763/README.md?plain=1#L298

Looks like this happened in 2d42a841648fec80073338ed553fc62b6d8dbf59.

**Comment by linas** [comment]
Fixed in commit c52c9a65536375f2d5a4a4a88a7ad75ff40b14f8

Thanks.
