### ISSUE TITLE
NEWS file is out of date

### ISSUE THREAD

**Issue by ryandesign** [opencog/link-grammar#1490]
Versions after 5.5.0 are not mentioned in the NEWS file:

https://github.com/opencog/link-grammar/blob/3a2612761f17e2579cb213a02aa1cef394f98763/NEWS#L1

**Comment by ryandesign** [comment]
I see that ChangeLog does describe new versions. If you no longer wish to update the NEWS file, it would help if you add a note at the top of the NEWS file referring readers to the ChangeLog for info about newer versions. Otherwise it just looks like you forgot to update the NEWS file.

**Comment by linas** [comment]
fixed in commit 3801ac79d4e6ac60dda4810d9bb51c87108fedd9
