### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by misgeatgit** [opencog/link-grammar#151]
Hi guys, I'm facing the following error while issuing make command with latest version of linkgrammar

``
make[1]: Entering directory `/home/misgana/OPENCOG/link-grammar/link-parser'
  CC       link-parser.o
  CC       command-line.o
  CC       lg_readline.o
  CCLD     link-parser
../link-grammar/.libs/liblink-grammar.so: undefined reference to `print_hier_position'
collect2: error: ld returned 1 exit status
make[1]: *** [link-parser] Error 1
make[1]: Leaving directory `/home/misgana/OPENCOG/link-grammar/link-parser'
make: *** [all-recursive] Error 1
``

major cause seems print_hier_position is not being resolved.

**Comment by ampli** [comment]
Please apply patch #149, that fixes this compilation problem.
(It is not yet in the latest repository version.)

**Comment by misgeatgit** [comment]
@ampli  Thanks!
