### ISSUE TITLE
Configuring with --enable-debug misses finding opencog/atomspace/AtomSpace.h

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#1527]
When I configure with `--enable-debug`, I get:
`checking for opencog/atomspace/AtomSpace.h... no`
when w/o  `--enable-debug`, it is found.

This is because of an enum definition in `opencog/util/Logger.h`, which uses `DEBUG`.
From `config.log`:
```
conftest.cpp:45:15: error: expected identifier before numeric constant
   45 | #define DEBUG 1
      |               ^
conftest.cpp:45:15: error: expected '}' before numeric constant
In file included from /usr/local/include/opencog/util/async_method_caller.h:37,
                 from /usr/local/include/opencog/atomspace/AtomSpace.h:28,
                 from conftest.cpp:76:
/usr/local/include/opencog/util/Logger.h:51:16: note: to match this '{'
   51 |     enum Level { NONE, ERROR, WARN, INFO, DEBUG, FINE, BAD_LEVEL=255 };
      |                ^
conftest.cpp:45:15: error: expected unqualified-id before numeric constant
   45 | #define DEBUG 1
      |               ^
```
Unless it is fixed in opencog (use e.g. `DBG`, or `#undef DEBUG` in a top-level include file), I propose to add `#undef DEBUG` in the `dict-atomese` files.

**Comment by linas** [comment]
I added `#undef`  directly in `Logger.h` so pull that again and `make; make install` and all should be well.
