### ISSUE TITLE
Non-API functions in link-grammar.def - why?

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#168]
Their mainly appear at the end of link-grammar.def.

For example:
object_open
catenate_disjuncts
connector_new
compute_chosen_words
partial_init_linkage
etc.

**Comment by linas** [comment]
these are needed to allow the the sat-solver code to call these functions.

Also, the file-backed dictionary vs the unfinished sql-backed dictionary needs to call some internal functions, too...

**Comment by ampli** [comment]
At least these are not currently used externally:
compute_chosen_words
lg_mbrtowc

But I guess it is not too critical...

**Comment by ampli** [comment]
Sorry - lg_mbrtowc is actually used - through the macro mbrtowc.
