### ISSUE TITLE
English dict problem at commit 12c7437b

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#169]
The following dict problem started at commit 12c7437b2a4a5f7107f4c18811441e1a3292ebdf.

Sentence:
`Nobody, it seems, wants to be a liberal`

Before this commit:
`LEFT-WALL nobody , it seems.q , wants.v to.r be.v a liberal.n `

After this commit, until now:
`LEFT-WALL nobody , it seems.v [,] [wants] to.r be.v a liberal.n`

**Comment by linas** [comment]
Hmm.

Try replacing the `(Xp+ or <paraph-null>)` by `(Xc+ or Xp+ or <paraph-null>)` -- that should fix it.

Not clear if that would cause any other regressions, though. Based on the rest of that commit, I'm guessing there were problems with sentences of the form "blah blah blah, he said"  ...

**Comment by ampli** [comment]
I check a detailed run on en/4.0.batch and en/4.0.fixes.batch.
It indeed fixed the problem.
It didn't cause other regressions.
So I will send a pull request for that.
