### ISSUE TITLE
domain and SIZE_MAX 

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#200]
In **post_process.c** we have:
```
static size_t find_domain_name(Postprocessor *pp, const char *link)
{
	size_t i, domain;
	StartingLinkAndDomain *sllt = pp->knowledge->starting_link_lookup_table;
	for (i=0;;i++)
	{
		domain = sllt[i].domain;
		if (domain == SIZE_MAX) return SIZE_MAX;  /* hit the end-of-list sentinel */ <---
		if (post_process_match(sllt[i].starting_link, link)) return domain;
	}
}
```
Note the check marked with **<---**.
Here is the definition of `StartingLinkAndDomain` (**structures.h**):
```
/* from pp_knowledge.c */
typedef struct StartingLinkAndDomain_s
{
	const char *starting_link;
	int   domain;       /* domain which the link belongs to (-1: terminator)*/
} StartingLinkAndDomain;
```

Note that `sllt[i].domain` is of type `int`, while **SIZE_MAX** is the naximum value of a `size_t` type variable (quoted from **stdint.h**):
``` 
/* Limit of `size_t' type.  */
# if __WORDSIZE == 64
#  define SIZE_MAX      (18446744073709551615UL)
```

On most 64-bit processors sizeof(size_t) > sizeof(int).
**Edit**: I was wrong, see my next message here.
So this check is always **false** on X86_64. It is not detected by the compiler because the assignment to a size_t variable hides the problem.

It is checked in many more places (from **grep -R SIZE_MAX**):
```
link-grammar/linkage.c :	if (!verify_link_index(linkage, index)) return SIZE_MAX;
link-grammar/linkage.c :	if (!verify_link_index(linkage, index)) return SIZE_MAX;
link-grammar/post-process.c    :		assert(sublinkage->link_array[i].lw != SIZE_MAX);
link-grammar/post-process.c    :		assert(sublinkage->link_array[j].lw != SIZE_MAX);
link-grammar/post-process.c    :		assert (sublinkage->link_array[link].lw != SIZE_MAX);
link-grammar/post-process.c    :		assert (sublinkage->link_array[link].lw != SIZE_MAX);
link-grammar/post-process.c    :		if (i == SIZE_MAX)
link-grammar/post-process.c    :		assert (sublinkage->link_array[link].lw != SIZE_MAX);
link-grammar/post-process.c    :		assert(linkage->link_array[i].lw != SIZE_MAX);
link-grammar/print.c   :		assert (linkage_get_link_lword(linkage, link) != SIZE_MAX);
link-grammar/print.c   :		assert (linkage_get_link_lword(linkage, link) != SIZE_MAX);
link-grammar/print.c   :		assert (ppla[link].lw != SIZE_MAX);
link-grammar/print.c   :			assert (ppla[j].lw != SIZE_MAX);
```

But in any case, nothing in the current sources tries to set it to SIZE_MAX!
There was once such a setting, in a discarded function **merge_constituents**, that has gone with the FAT-LINKS code.

Questions:
1. Is such a setting somehow still needed, so it needs a fix?
2. If not, can we discard all of these **SIZE_MAX** checks?

**Comment by ampli** [comment]
I was wrong. The use of SIZE_MAX here is matching the -1 domain array terminator.
And it works fine when promoting int to size_t (i.e. when they have different sizes).
But I still don't understand the reason to convert the domain value to size_t and check for SIZE_MAX, instead of just checking for -1.

**Comment by linas** [comment]
Some/many of the fields are unsigned ints, and, depending on your compiler, setting and comparing to -1 can fail.  I'm pretty sure that gcc will generate an error message if you compare an unsigned int to -1.

Yes, these compares are ugly, and some of them might not be needed; if you can find a better solution, that would be good. Right now its messy ...
