### ISSUE TITLE
Argument "dir" of match_in_connector_set()

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#201]
Here is the code of this funtion:
```
bool match_in_connector_set(Connector_set *conset, Connector * c, int dir)
{
	size_t h;
	Connector * c1;
	if (conset == NULL) return false;
	h = connector_set_hash(conset, c->string, dir);
	for (c1 = conset->hash_table[h]; c1 != NULL; c1 = c1->next)
	{
		if (easy_match(c1->string, c->string) && (dir == c1->word)) return true; <---
	}
	return false;
}
```
Note the line marked with **<---**.
Since this function appears as 1.4% in the profiling, I tried to speed it up by reversing the order of the **&&** check. However, it only increased its CPU usage. It turns out `(dir == c1->word)` is always true, because this function is now only invoked with **dir=='+'**.

The only place in which it got invoked with **dir=='-'** was in the file **and.c**, which has gone with the FAT-LINKS code.
So I guess it is OK to simplify it by removing the **dir** argument from it.

**Comment by linas** [comment]
yes, seems right to me; convert this to a pull request...
