### ISSUE TITLE
Adding fields to the Disjunct and Connector structures

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#219]
Hi Linas,
I implemented an idea that already shows a speedup of 10+% for en/corpus-fixes.batch and about 40%(!) for en/corpus-fix-long.batch. I expect it may save more because it has a room for improvements in several ways. The idea is to do pre-calculation of connector matches in form_match_list(), instead of calculating that in do_count()/mk_parse_set(). To that end I had to add the fields indicated below to the disjunct structure:

Do you mind if I make the following changes to Disjunct_struct?
```
struct Disjunct_struct
{
	Disjunct *next;
	const char * string;       /* subscripted dictionary word */
	Connector *left, *right;
	double cost;
	bool marked;               /* unmarked disjuncts get deleted */
	bool match_left, match_right; /* used only during parsing */       <--- Added
	const Gword **word;        /* NULL terminated list of originating words */
};
```

Some more speedup can be achieved by adding a filed to Connector_structure:
```
/* On a 64-bit machine, this struct should be exactly 4*8=32 bytes long.
 * Lets try to keep it that way.
 */
struct Connector_struct
{
	short hash;                                                                                  <--- Changed
	bool uc;     /* Uppercase only - to speed up connector match */    <--- Added
	unsigned short word;
	             /* The nearest word to my left (or right) that
	                this could connect to.  Computed by power pruning */
	unsigned char length_limit;
	             /* If this is a length limited connector, this
	                gives the limit of the length of the link
	                that can be used on this connector.  Since
	                this is strictly a function of the connector
	                name, efficiency is the only reason to store
	                this.  If no limit, the value is set to 255. */
	bool multi;  /* TRUE if this is a multi-connector */
	Connector * next;
	const char * string;  /* The connector name, e.g. AB+ */

	/* Hash table next pointer, used only during pruning. */
	Connector * tableNext;
};
```
I changed the `hash` field to `short` in order to keep the structure size as 64 bytes.
This and maybe additional fields in Connector_structure will not be needed if/when I implement the connector enumeration idea.

The speedup idea is based on the availability of list of disjuncts which include sequences of the same connector strings. In that case matching connectors can be done in a different way, and most of the times there is no need to actually try to match them.

BTW, the recent speed up of form_match_list() for en/corpus-fix-long.batch is about 30%, so together this makes a drastic speed up for long sentences. Additionally, I have several more changes that speed up long sentences, that I need to eventually send.

If this structure changes are OK by you, I will continue polishing my changes in order to send a pull request.

**Comment by linas** [comment]
Sounds good to me. Can you re-arrange, so that the two bools are next to each other, and the shorts are next to each-other? Shorts need to be 16-bit aligned, so if you have a struct like this `short; char; short; char;` the alignment will cause it to use 8 bytes, but ` short short char char` will use only 6 bytes. 

I'm not sure, but gcc might even pack bools into single bits, so mixing bools with anything else ends up reserving anything from 1 to 8 bytes per bool.  Best to group like types next to each other., and chars next to shorts, etc.

**Comment by ampli** [comment]
Bools in GCC in c99 mode are 8-bit (before that they ere  int), so this is not going to make the structure smaller.
However, it can be a good idea anyway (here and in other structures) because it enables easy  experimentation with:
1. Make them bit fields.
2 . Use the `__attribute__ ((__packed__))` feature of GCC (and ccomp) (of course conditionally compiled only on the tested architectures, e.g. x86_64).
These things can be done in order to reduce the size of structures, and especially of structure arrays, in a hope for a speedup due to a better use of the CPU cache despite of the unaligned access performance penalty. (BTW, in one of the successful speedup tests I did there are disjunct arrays.)

I will make the change you propose.

BTW, since you changed the configuration script to use -std=c99, and the recent MSVC support a large part of c99, I think we can now make a wide use of c99 features when they make the code more readable, e.g.:
1. Mixed declarations (already exist in several places).
2. Designated initializers.
3. Structure constants.
4. Non-constant initializers.

Will it be fine if I do it?

**Comment by linas** [comment]
We can change to std=c11 for all I care ... the problem is that MSVC supports some but not all of c99 and has issued a statement to the effect that it will never support certain things. This was discussed on mailing list 2-4 years ago. 

Re shorts, chars, you miss my point:  In order for just about any modern CPU to load a short, it MUST be 16-bit aligned. To load an int32, it MUST be 32-bit aligned, and to load a long, it MUST be 64-bit aligned.  So an extreme example would be:
```
struct foo {
   double  x;   // last 3 bits of &x are zero: its 8-byte aligned.
   char y;       // one byte, followed by 7 bytes of pad, because the next double
   double z;   // is 8-byte aligned.
   char w;      // a byte
};
```
Thus `sizeof (struct foo)` is 32 in this example.  But this
```
struct foo {
   double  x;   // last 3 bits of &x are zero: its 8-byte aligned.
   double z;   // is 8-byte aligned.
   char y;       // one byte,
   char w;      // one byte
};
```
has a `sizeof (struct foo)` of either 18 or 20 or 24 bytes, depending on compiler.

**Comment by linas** [comment]
Re `__attribute__(( packed ))` -- not sure its a good idea. The reason I want to pack structures is so that we can fit one or two of them per cache line , which are usually 128 or 256 bytes long. So its best to have structs that are multiples of these sizes, instead of being filled with padding.   Making effective use of cache lines means a sentence parse should fit into L1 or L2 cache, and not spill to L3 or RAM, where things get slow.

Packing bits can make the struct smaller, but if we waste time unpacking bits, we can loose more time than we saved, which would be the case if a whole sentence parse was able to fit into L2, for example.

**Comment by ampli** [comment]
My point was that if in GCC C99 and above (and BTW on MSVC) sizeof(bool) is 1, then it doesn't matter if Connector_structure is:
```
struct Connector_struct
{
    short hash;
    bool uc;
    unsigned short word;
    unsigned char length_limit;
    bool multi;
    Connector * next;
    const char * string;
    Connector * tableNext;
};
```
or:
```
struct Connector_struct
{
    short hash;
    unsigned short word;
    unsigned char length_limit;
    bool multi;
    bool uc;
    Connector * next;
    const char * string;
    Connector * tableNext;
};
```
since in **both** cases the total size is 32 bytes.

If there are architectures or compilers in which sizeof(bool)==sizeof(int),  and supposing 4-bit ints with 4 byte alignment, then the first one will be 40 bytes, and after your proposed reorder (the second one) it will be  ... 40 bytes too!

So we see that this reorder doesn't change the size of this particular structure whatever sizeof(bool) is (1 or 4). Of course, such reorder matters in other cases, as you demonstrated.

I suggested to even change it to something like:
```
struct Connector_struct
{
    const char * string;
    Connector * next;
    Connector * tableNext;
    short hash;
    unsigned short word;
    unsigned char length_limit;
    bool multi;
    bool uc;
};
```
When packed, its size is 31 bytes, and with sizeof(bool)==sizeof(int) it is 37 bytes.
BTW, `unsigned char word` will make the packed version 30 bytes. It will not reduce memory usage unless we have connector arrays (which we don't have for now). See below for a case in which a packed array that causes misaligned access on x86 actually increases the processing speed.

> but short short char char will use only 6 bytes.

It is actually short short char char char in our case (7 bytes).

The article [Does packed struct hurt performance on x86_64?](https://attractivechaos.wordpress.com/2013/05/02/does-packed-struct-hurt-performance-on-x86_64/) hints that in certain cases, array of packed structures can be faster on x86.
This is because a misaligned access on x86 doesn't have a big performance penalty, while cache misses, and especially cache trash, is a big issue (cache trash can cause 10x slowness - from another article).

Regarding packing bits (or using short/char instead of ints or ints instead of size_t, all of course when possible), in general it may sometimes have the following saving:
1. Instead of passing several arguments to functions, pass one argument.
2. For bool, make several operations at once using a bit mask.
3. Some struct field may have relatively rare use, but they still must be there and take memory and cache space, so it is better if they are smaller.
4. When a struct is just a little bigger than 64 bytes without such packing, e.g. 65 bytes.
5. Save on mass copy (of arrays).

So only after an actual test we can see if there is a significant speedup in particular cases (and it depends of course on the CPU architecture and even model). Regarding the LG library, I suspect cache trashing in some places, which I would like to test.

**Comment by ampli** [comment]
>  the problem is that MSVC supports some but not all of c99 and has issued a statement to the effect that it will never support certain things. This was discussed on mailing list 2-4 years ago.

See:
[Visual Studio Moves Closer to C99 and C++11/14 Support](http://www.infoq.com/news/2013/07/vs2013_CPP_compliance).

[C++11/14/17 Features In VS 2015 RC](http://blogs.msdn.com/b/vcblog/archive/2015/04/29/c-11-14-17-features-in-vs-2015-rc.aspx).

A quote from the last link:
In VS 2013, the compiler team implemented some C99 Core Language features in C mode (e.g. designated initializers, see MSDN for the full list), in order to support some popular libraries.

I will be able to compile the LG library in VS 2015 to validate that everything that I use from C99 is supported. Regarding C11, I didn't find relevant improvements that can help much for code readability in the LG library.

**Comment by linas** [comment]
OK, I didn't see the third byte there. Changing the size to 30 from 32 won't affect anything, since the next struct still has to be 8-byte aligned.

There's only a few structures where the size matters: the connectors, and the disjuncts, because there is a lot of them, and because they are accessed very often during parsing. Most of the other structures don't matter.

I used size_t in many places because .. I dunno. Maybe unsigned int would be better, e.g. in Link_s

**Comment by linas** [comment]
change it to std=c11 and use whatever c11 features you want. The next vresin won't be for a while, and we'll find out on the mailing list what the issues are.

**Comment by ampli** [comment]
I actually tested the packed Connector struct of 30 bytes on GCC:
```
#include <stdbool.h>
#include <stdio.h>

typedef struct Connector_struct Connector;
struct Connector_struct
{
    const char * string;
    Connector * next;
    Connector * tableNext;
    short hash;
    unsigned char word;
    unsigned char length_limit;
    bool multi;
    bool uc;
} __attribute__ ((packed));

Connector ca[10];

int main()
{
	printf("sizeof(Connector)=%zu, sizeof(ca)=%zu\n", sizeof(Connector), sizeof(ca));
	ca[1].string = "test";
	printf("&ca[1].string=%p\n", &ca[1].string);
	return 0;
}
```
It prints:
``
sizeof(Connector)=30, sizeof(ca)=300
&ca[1].string=0x60107e
```
So the address of the pointer is actually aligned to 2, and it works.

As the post I referred above says,  X86 doesn't really need the full alignment according to data type size, and a full alignment only makes the memory access slightly more efficient. Whether the packing has actual saving may depend on the amount of operations done on each array element, the total element size, and the saving ratio due to the packing. In our case the saving ratio 2/32 is very small so I guess it will not improve efficiency unless (maybe) almost nothing is done on each element, e.g. only an assignment to one field.
