### ISSUE TITLE
Connector_struct: Field size of length_limit is not enough, or MAX_SENTENCE too big

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#220]
Currently `Connector_struct` is:
```
struct Connector_struct
{
   int hash;
   unsigned short word;
                /* The nearest word to my left (or right) that
                   this could connect to.  Computed by power pruning */
   unsigned char length_limit;
                /* If this is a length limited connector, this
                   gives the limit of the length of the link
                   that can be used on this connector.  Since
                   this is strictly a function of the connector
                   name, efficiency is the only reason to store
                   this.  If no limit, the value is set to 255. */
   bool multi;  /* TRUE if this is a multi-connector */
   Connector * next;
   const char * string;  /* The connector name, e.g. AB+ */

   /* Hash table next pointer, used only during pruning. */
   Connector * tableNext;
};
```
In addition we have these definitions:
```
#define MAX_SENTENCE 65534      /* Maximum number of words in a sentence */
#define BAD_WORD (MAX_SENTENCE+1)
```
The "no limit" value in `length_limit` is only 255.
However,  in prune.c `word` can be set to a number > 255.
It means that matching connectors from such words  will always (silently) fail.

I got aware to this problem when I needed more space in Connector_struct for an efficiency change.
I wanted to reduce the size of `word` to match the maximum limit imposed by `length_limit`,
and then noted that `MAX_SENTENCE` is actually very large.

The questions are how to fix this inconsistency, and how to get more space in `Connector_struct` while keeping it at 64 bytes. 

Possible solutions:
1. Limit the sentence size to 254. Change `word` to `unsigned char`. This will provide enough space in `Connector_struct`, and the library will reject sentences it actually cannot handle due to their length.
2.  Change `length_limit` to `unsigned short`, and keep `MAX_SENTENCE` as 65534. However, there is no much point to do that, as the parsing algorithms cannot handle anyway (in a reasonable time) sentences with > 254 words. In that case, to provide more space  `tableNext` can be moved to an anonymous union (which has a nice feature of "transparency", and is supported by the current VC).

I don't like low limits, but anyway I'm for option **(1)**, because the current limit on `MAX_SENTENCE` is rather impractical high until a farther notice. In addition, some of the above fixes is a must, because else the library can be "bombed" by sentences which it will fail to handle anyway even after much processing time, because of the said inconsistent limit.

Please advise.

**Comment by linas** [comment]
Option 1 is the best option!

**Comment by linas** [comment]
... and I have nothing more to add. For a while, letting word-number be a 32-bit int seemed like  an OK idea, but it really serves no purpose. Option 1 works.
