### ISSUE TITLE
English problem at commit d42d42a: "does be"

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#226]
This sentences now parses as being correct:
*Abrams does be a good programmer

**Comment by ampli** [comment]
Some googling shows me this is Irish English, so I guess it is intentional.
If so, this sentence should be marked as a good one, like the new similar sentences that I now see in en/corpus-fixes.batch.

**Comment by linas** [comment]
Huh. I thought I looked for that in the test bucket, and didn't see it. The simplest things sems to be to just remove it from the test.  I just pushed a patch to do that.
