### ISSUE TITLE
Internal error !

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#227]
There's an internal error:
```
cat ../data/en/corpus-fixes.batch | link-parser > x
```
prints
```
link-grammar: Error: Word 'Sui': Internal error: NULL X_node
link-grammar: Error: Word 'Zeus': Internal error: NULL X_node
link-grammar: Error: sentence_split(): Internal error detected
link-grammar: Error: Word 'vibes': Internal error: NULL X_node
link-grammar: Error: sentence_split(): Internal error detected
```

**Comment by ampli** [comment]
These words are not found (even as substrings) in the released  en/corpus-fixes.batch, so I cannot identify the sentences which caused this problem.

Can you please run it with errors redirected to the same file, and then scan the file for "NULL X_node"?
Something like:
```
$ cat ../data/en/corpus-fixes.batch | link-parser >  x   2>&1
$ grep -B 1 'NULL X_node'  x
```

I already know about such kind of error, involving spelling and contractions:
```
linkparser> this test,'s,
link-grammar: Error: Word 'Estes': Internal error: NULL X_node
```
Meanwhile I will try to fix this one and send a pool request.

BTW, this "NULL X_node" internal error means that the tokenizer marked a word as "in dict", but when constructing the X-Nodes, the word is actually not found in the dictionary.

**Comment by linas** [comment]
Ah, interesting, its the spell checker:
```
*Синтезируется из глюкозы в тканях и органах, например в сердце, печени, почках.
*You need it most.Either way you cant lose.
spell set to 4
*lgdebug(+D_IWA, "(%s) Gword %zu:%s split (split_counter=%zu) into", label,
link-grammar: Error: Word 'Sui': Internal error: NULL X_node

link-grammar: Error: Word 'Zeus': Internal error: NULL X_node

link-grammar: Error: sentence_split(): Internal error detected
*@s
vibeix here
link-grammar: Error: Word 'vibes': Internal error: NULL X_node

link-grammar: Error: sentence_split(): Internal error detected
spell set to 0
*"T" This is a test
*"To" It's to let; there's a notice on the door
```

**Comment by linas** [comment]
Well, adding the words 'vibes' and 'Zeus' to the dict make the corresponding errors go away.  Adding 'sui_generis' does not.

I dunno, so this is a dictionary - spellcheck mismatch. I'm tempted to do nothing ...

**Comment by ampli** [comment]
It looks as if these particular cases have been already fixed (and hence these sentences exist in the batch).

Can it be that you somehow used, by chance, an old copy of link-parser?
Or maybe this has been triggered by a temporary dictionary change in your working copy?

I tested it with b9218b8fd99e9a15d77da6cc0e9a0616da06d30b, and I don't see the problem.

Anyway I will fix the problem in the case that I know (**this test,'s,**). The problem in it is that just now compound words (stem-suffix, prefix-word and contractions) are considered as being in the dict if they can validly get split by the tokenizer, but the code currently fails to validate that each part of a contraction (which the speller provides as a fix) is in the dictionary.

BTW, maybe it will be a good idea to include in the Makefile the build number of the library, to be printed on startup, so we know from exactly which commit a library was generated, for the purpose of bug reports.
Something like [this](http://stackoverflow.com/a/12368262).
In addition we can add to that an ID for each optional component, like the SAT solver, so we know with what optional components a given library has been compiled.

**Comment by linas** [comment]
I just added the words "vibes" and "Zeus" to the dicts. That is why the problem went away.

I also added "sui_generis" but this was not enough to make the problem go away.

**Comment by ampli** [comment]
The version that I checked is from yesterday, before you added these words, and I could not find the problem in it. Anyway, I just have sent a pool request #232 to fix the unknown contracted word problem.
(As sometimes happens, I forgot to mention this issue in the commit message...).

**Comment by linas** [comment]
That fixes it. Thanks!

Re: spell: I have aspell installed, so the build finds that. I've got the US spell dict installed, and maybe also the great-brit one too, I don't recall.    I notice that LG starts with spell-guessing turned on, by default.  If you can't reproduce it, I'm guessing its one of these ...

**Comment by ampli** [comment]
I now understand why I couldn't reproduce this...

This error is sensitive to what the spell guesser suggests as replacement!
If it happened to suggest contracted words whose base word is not in the dict, then this problem would happen. Your spell library just suggested such words, and mine (a totally another version) didn't.

So it is indeed the same problem that I have just fixed.

**Comment by linas** [comment]
stage, I am getting this again:
```
link-grammar: Error: Word 'Sui': Internal error: NULL X_node

link-grammar: Error: sentence_split(): Internal error detected
```

I thought this was fixed; I'm confused.

**Comment by ampli** [comment]
I configured the library to use aspell (validated with ldd), and even enabled spell in the fixes.batch file (!spell=7), but I still cannot reproduce the problem.

What can help me is the whole output of `link-parser -verbosity=5` on the **particular sentence** that causes the failure.

**Comment by linas** [comment]
Hmm Its not happening again ... I'm confused even more.
