### ISSUE TITLE
List of words which are not in the English dictionary

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#233]
I have gathered a few tens of words, which are currently not in the dict (validated just now), many of them "technical". I just encountered them while writing or reading recent posts.
Some of them seem easy to add, like **w/o**.
However, for most of them it will be very hard for me, as a non-native speaker, to send a pool request.
So I'm including them here.

drawbacks
unprefixed
prenominal
unparsable
refactor
smartphone
uninstructive
pragma
postprocessor
coprocessor

subword
substring
whitespace
ampersand
multibyte
downcase
capitalisation (capitalization exists)
capitalize  # transitive and intransitive (capitalise exists)
capitalizable
capitalisable
subscript (verb)
strippable
monospace
emoticon
underbar

backport
supercompact
side-effect
congnitive
nondistinctive

semantical
inflectional
derivational
agglutinative

unlink
unlinked

precompile
precompiled
backtrack
workaround
refactor (classified now as n)
zeroary
wildcard
boolean
Boolean
untruncated
include (include file, include directive, server side includes)
deglobalization
clickable
and/or
w/o
crufty
look-alike
backend
multithread
segfault
unpatched
misconfiguration
ruggedisation
hotspot
inlining
initializer
uninitialized
overclock
uncareful

**Comment by linas** [comment]
Could you sort into nouns, verbs, adjectives and other? that would make it a little easier.

**Comment by ampli** [comment]
Some words have multiple POS and are unsorted here, or sorted according to one POS only.
(Of course I used an ad-hoc script to create this table...)

Word | POS | Comment
-----|-----|--------
[agglutinative](https://en.wiktionary.org/wiki/agglutinative) | adj | 
[capitalisable](https://en.wiktionary.org/wiki/capitalisable) | adj | 
[capitalizable](https://en.wiktionary.org/wiki/capitalizable) | adj | 
[clickable](https://en.wiktionary.org/wiki/clickable) | adj | 
[crufty](https://en.wiktionary.org/wiki/crufty) | adj | 
[derivational](https://en.wiktionary.org/wiki/derivational) | adj | 
[inflectional](https://en.wiktionary.org/wiki/inflectional) | adj | 
[monospace](https://en.wiktionary.org/wiki/monospace) | adj,v | 
[multibyte](https://en.wiktionary.org/wiki/multibyte) | adj | 
[nondistinctive](https://en.wiktionary.org/wiki/nondistinctive) | adj | 
[prenominal](https://en.wiktionary.org/wiki/prenominal) | adj | 
[semantical](https://en.wiktionary.org/wiki/semantical) | adj | 
[strippable](https://en.wiktionary.org/wiki/strippable) | adj | 
[supercompact](https://en.wiktionary.org/wiki/supercompact) | adj | 
[uncareful](https://en.wiktionary.org/wiki/uncareful) | adj | 
[uninitialized](https://en.wiktionary.org/wiki/uninitialized) | adj | 
[uninstructive](https://en.wiktionary.org/wiki/uninstructive) | adj | 
[unparsable](https://en.wiktionary.org/wiki/unparsable) | adj | 
[unpatched](https://en.wiktionary.org/wiki/unpatched) | adj | 
[unprefixed](https://en.wiktionary.org/wiki/unprefixed) | adj | 
[untruncated](https://en.wiktionary.org/wiki/untruncated) | adj | 
[zeroary](https://en.wiktionary.org/wiki/zeroary) | adj | 
[capitalize](https://en.wiktionary.org/wiki/capitalize) | v | transitive and intransitive (capitalise exists)
[downcase](https://en.wiktionary.org/wiki/downcase) | v | 
[over-clock](https://en.wiktionary.org/wiki/over-clock) | v | 
[over-clock](https://en.wiktionary.org/wiki/over-clock) | v | 
[overclock](https://en.wiktionary.org/wiki/overclock) | v | 
[overclock](https://en.wiktionary.org/wiki/overclock) | v | 
[postprocess](https://en.wiktionary.org/wiki/postprocess) | v | 
[precompile](https://en.wiktionary.org/wiki/precompile) | v | 
[refactor](https://en.wiktionary.org/wiki/refactor) | v | noun by regex
[subscript](https://en.wiktionary.org/wiki/subscript) | v | subscript.n exists
[ampersand](https://en.wiktionary.org/wiki/ampersand) | n | 
[ampersands](https://en.wiktionary.org/wiki/ampersands) | np | 
[and/or](https://en.wiktionary.org/wiki/and/or) | con | 
[backend](https://en.wiktionary.org/wiki/backend) | n | 
[backends](https://en.wiktionary.org/wiki/backends) | np | 
[backport](https://en.wiktionary.org/wiki/backport) | n,v | 
[backport](https://en.wiktionary.org/wiki/backport) | np | 
[backtrack](https://en.wiktionary.org/wiki/backtrack) | n,v | 
[backtracks](https://en.wiktionary.org/wiki/backtracks) | np | 
[Boolean](https://en.wiktionary.org/wiki/Boolean) | n | 
[Booleans](https://en.wiktionary.org/wiki/Booleans) | np | 
[boolean](https://en.wiktionary.org/wiki/boolean) | n | 
[booleans](https://en.wiktionary.org/wiki/booleans) | np | 
[capitalisation](https://en.wiktionary.org/wiki/capitalisation) | n | capitalization.n-u exists
[capitalisations](https://en.wiktionary.org/wiki/capitalisations) | np | 
[coprocess](https://en.wiktionary.org/wiki/coprocess) | n | 
[coprocesses](https://en.wiktionary.org/wiki/coprocesses) | np | 
[coprocessor](https://en.wiktionary.org/wiki/coprocessor) | n | 
[coprocessors](https://en.wiktionary.org/wiki/coprocessors) | np | 
[drawbacks](https://en.wiktionary.org/wiki/drawbacks) | np | drawback.n exists
[emoticon](https://en.wiktionary.org/wiki/emoticon) | n | 
[emoticons](https://en.wiktionary.org/wiki/emoticons) | np | 
[hotspot](https://en.wiktionary.org/wiki/hotspot) | n | 
[hotspots](https://en.wiktionary.org/wiki/hotspots) | np | 
[include](https://en.wiktionary.org/wiki/include) | n | include.v exists. ex: include file, include directive, server side includes
[includes](https://en.wiktionary.org/wiki/includes) | np | 
[initializer](https://en.wiktionary.org/wiki/initializer) | n | 
[initializers](https://en.wiktionary.org/wiki/initializers) | np | 
[inlining](https://en.wiktionary.org/wiki/inlining) | n,v | 
[inlinings](https://en.wiktionary.org/wiki/inlinings) | np | 
[look-alike](https://en.wiktionary.org/wiki/look-alike) | n | 
[look-alikes](https://en.wiktionary.org/wiki/look-alikes) | np | 
[misconfiguration](https://en.wiktionary.org/wiki/misconfiguration) | n | 
[misconfigurations](https://en.wiktionary.org/wiki/misconfigurations) | np | 
[multithread](https://en.wiktionary.org/wiki/multithread) | adj | 
[postprocessor](https://en.wiktionary.org/wiki/postprocessor) | n | 
[postprocessors](https://en.wiktionary.org/wiki/postprocessors) | np | 
[pragma](https://en.wiktionary.org/wiki/pragma) | n | 
[pragmas](https://en.wiktionary.org/wiki/pragmas) | np | 
[segfault](https://en.wiktionary.org/wiki/segfault) | n,v | 
[segfaults](https://en.wiktionary.org/wiki/segfaults) | np | 
[side-effect](https://en.wiktionary.org/wiki/side-effect) | n | 
[side-effects](https://en.wiktionary.org/wiki/side-effects) | np | 
[smartphone](https://en.wiktionary.org/wiki/smartphone) | n | 
[smartphones](https://en.wiktionary.org/wiki/smartphones) | np | 
[substring](https://en.wiktionary.org/wiki/substring) | n | 
[substrings](https://en.wiktionary.org/wiki/substrings) | np | 
[subword](https://en.wiktionary.org/wiki/subword) | n | 
[subwords](https://en.wiktionary.org/wiki/subwords) | np | 
[underbar](https://en.wiktionary.org/wiki/underbar) | n | 
[underbars](https://en.wiktionary.org/wiki/underbars) | np | 
[unlink](https://en.wiktionary.org/wiki/unlink) | n,v | 
[unlinks](https://en.wiktionary.org/wiki/unlinks) | np | 
[w/](https://en.wiktionary.org/wiki/w/) | prep,adv | with - can it be a prefix?
[w/i](https://en.wiktionary.org/wiki/w/i) | adv? | with intent
[w/i](https://en.wiktionary.org/wiki/w/i) | prep,adv | within
[w/o](https://en.wiktionary.org/wiki/w/o) | adv,con,prep | without
[w/o](https://en.wiktionary.org/wiki/w/o) | n | walkover
[w/o](https://en.wiktionary.org/wiki/w/o) | n | write-off
[w/o](https://en.wiktionary.org/wiki/w/o) | n? | wife of
[whitespace](https://en.wiktionary.org/wiki/whitespace) | n | 
[whitespaces](https://en.wiktionary.org/wiki/whitespaces) | np | 
[wildcard](https://en.wiktionary.org/wiki/wildcard) | n | 
[wildcards](https://en.wiktionary.org/wiki/wildcards) | np | 
[workaround](https://en.wiktionary.org/wiki/workaround) | n | 
[workarounds](https://en.wiktionary.org/wiki/workarounds) | np | 
[write-off](https://en.wiktionary.org/wiki/write-off) | n | 
[write-off](https://en.wiktionary.org/wiki/write-off) | np | 
[writeoff](https://en.wiktionary.org/wiki/writeoff) | n | 
[writeoffs](https://en.wiktionary.org/wiki/writeoffs) | np | 
[deglobalization](https://en.wiktionary.org/wiki/deglobalization) | n-u | 
[ruggedisation](https://en.wiktionary.org/wiki/ruggedisation) | n-u | 
[ruggedization](https://en.wiktionary.org/wiki/ruggedization) | n-u |

**Comment by linas** [comment]
Thanks, added. and/or was already in the dict, but I guess there are some sentences that use it that aren't handled in the general case?  I'd need examples.

**Comment by linas** [comment]
An ad-hoc script is overkill ... although I have a copy of french dicts that were created via ad-hoc scripts from wiktionary.  Never publshed them, they seemed to buggy and superficial.

**Comment by ampli** [comment]
It seems **and/or** somehow escaped my checks of existence in the dictionary...
