### ISSUE TITLE
Using a trie instead of prune connector table

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#258]
Instead of a big table which needs individual connector comparisons, I propose to implement a _trie_ of connectors. Then the match tests can be very fast. The `*` can be handled like currently a null linkage word is handled in sane_morphism() - the whole algo seems to me very similar, as we just need to find if there is a path in the trie for the checked connector.

**Comment by linas** [comment]
If you wish.  Its not at all clear to me why 5 or 7 pointer chases through a trie is going to be faster than hash and 2-3 pointer chases.   Unless I'm mis-understanding how big some of the has buckets are.

**Comment by linas** [comment]
pointer chasing tends to be very non-local in memory, bouncing around in cache lines.  Too many pointer chases can make things worse, if they jump out of cache and into RAM.

**Comment by ampli** [comment]
The algo now is to find, one by one, if a candidate connector matches a set of connectors.
The question is whether it is possible to find, in a more "bulky" operation, which of the connectors of a word is in the set, as if all the candidate connectors together were an "expression" that we search in a "text", which is the set.

**Comment by linas** [comment]
?  I know what tries are and how you want to use them; it just isn't obvious that they would be faster.

**Comment by ampli** [comment]
By now connector matching and also pruning have had a large speedup, so this idea seems much less promising. I still have ideas how to speed them up (especially expression pruning) and of course I will also consider using a trie if applicable.

So I'm closing this issue.
