### ISSUE TITLE
Test "Jumbo's going?" fails

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#260]
This happens due to the change at commit 76190bbb01dba4843b44b49d8147b1d247510840.

In any case, can these checks now be removed from separate_word()?

**Comment by linas** [comment]
Wow. No. That's a mistake.  Maybe that commit should be reverted. I thought that only java used this code; and my grep-fu failed to find it's use by tokenization.  I would not have removed that if I realized it was still being used.

Are you telling me that tokenization mostly doesn't need that enttity-check?   Clearly "Jumbo is coming?" parses differently in the old and new dicts .. why?

**Comment by linas** [comment]
Jumbo is the name of the kid in Tinker Tailor, if I recall correctly.

**Comment by ampli** [comment]
Only **marker-entity** has apparently no effect. I once added a long comment that it is redundant (FIXME at tokenize.c:2212). So it can be removed from the code, unless I missed something.

On the other hand, **marker-common-entity** was always needed for capitalized words, in order to find out whether to issue them as CAPITALIZED-WORDS, and most probably it needs to be returned to the dict.

**Comment by linas** [comment]
Yeah, I guess is_entity is not used and can be removed. Anyway, it doesn't seem to work.

"I bank with Sun Trust"  parses correctly "Sun Trust" is a bank

"I bank with sun Trust" parses strangely because "sun" is not an entity, so teh capital version is never issued.  Which makes sense, since entities are supposed to be capitalized, anyway.

**Comment by ampli** [comment]
According to my analysis, which I commented in the code, it is not used in the current dict.
From the said comment:
```
                                       ... this may have effect
 *   only for capitalized words that match non-capitalized-words
 *   regexes that are marked as entities. I don't know about such,
 *   ...
```

**Comment by linas** [comment]
Me neither.

**Comment by ampli** [comment]
After d3d84d4056acea88e36bbf89f33432b953bd6c68, this test passes again.
So I close this issue.

**Comment by linas** [comment]
thanks for catching this.   The comment in the code said "Java" and I could find no use in the Java code ... and somehow failed to look  elsewhere.
