### ISSUE TITLE
Order of linkages with the same cost + an array instead of list in form_match_list()

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#263]
I made the following change in form_match_list():
Instead of using a linked list to return the matching disjuncts, I used an array.
This has less overhead due to:
1. It is faster just to fill-in array elements.
2. Memory allocation:
- Can just malloc() all the array elements at once, instead of an malloc() per list element.
- No need to free() until finishing handling the sentence.

However, in case of returning an empty list it has (very) slight more overhead because it then returns one element with a NULL disjunct instead of just NULL (can be changed with a few more code lines, but the possible gain is very small).

Speed-up (**200** runs as 40 sets of best-of-5):
ru/corpus-fixes.batch: -0.71% __[*]__
en/corpus-basic.batch: -0.43%  __[*]__
en/corpus-fixes.batch: 5.2%
__[**]__ In vivo studies ...: 2.8%

__[*]__ May be consistent with ~0% due to the benchmark resolution.
__[**]__ The en/corpus-corpus-fix-long.batch with only this sentence.

However, because currently (i.e. before this change) the list is returned in reverse order, and in my change the array is in the match-list table order (because it is more efficient and elegant code this way), linkages of the same cost are returned in a different order.

For example, currently the first linkage of `This is a test" is:
```
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=6)

    +----->WV----->+---Osm--+
    +---Wd---+-Ss*b+  +Ds**c+
    |        |     |  |     |
LEFT-WALL this.p is.v a  test.n 
```
However, after the said change, the 1st and 2nd linkages order is changed:

```
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.00 LEN=6)

    +----->WV----->+---Ost--+
    +---Wd---+-Ss*b+  +Ds**c+
    |        |     |  |     |
LEFT-WALL this.p is.v a  test.n 
```

Supposing this change (of list to array) is fine by you (we can discuss the apparent speed reduction for short sentences - a benchmark of 1000 runs may be needed for a finer-grain resolution and to find out if to add returning NULL when the array is empty, which happens in several tens percents of the cases), it means there is a need to change the test suite in 2 places (a hard coded result and parses-en.txt).

Such a problem can happen due to other reasons:
1. Making pruning more aggressive.
2. Further efficiency changes in the match-lists, that may change their order.
3. The library qsort() is not guarantied to preserve the order of equal-key records or to emit them in any particular order. The Linux one is currently "stable" (apparently preserving the order of equal-key records), but other qsort()) implementations may not, and if implemented as quicksort with random pivot, they may not even be stable over different runs (this **can be fixed** in the LG library code by comparing the linkage number if the linkages cost is the same, but this introduces a slightly more overhead).
4. Introducing additional parsing algorithms for which it is desired to share tests.

For the long range I propose to change **tests.py** to not depend on the linkage order of linkages of the same cost. However, I could not find a straightforward way to do that, as there apparently no function like:
`assertAnyEqual(reselt, [possibility_1, possibility2, ...])`
but such a function can be written.

For the short range I propose to just change the parse test data of tests.py by hand when needed.

Linas,  this is a combined issue, so please indicate if my array change is acceptable or more checks/changes are needed to find out if the slight apparent reduced efficiency for short sentences is real, and if so, try to fix it (by adding code to support a more efficient empty match-list).

**Comment by linas** [comment]
change is acceptable. If two linkages are the same cost, its OK to return them in arbitrary order.  When its really important, equality can be broken in the dictionary, buy adding a small cost to some connector (although there should be a linguistic reason for doing this.)
