### ISSUE TITLE
Non-Latin output truncated on Windows

### ISSUE THREAD

**Issue by TatianaBatura** [opencog/link-grammar#285]
When I try to parse Kazakh sentences with LinkGrammar 5.3.3 (Windows), some sentences in the output get truncated. I had the same problem with Russian and Turkish sentences.

<img width="434" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/9364537/13370868/584473b8-dd40-11e5-8614-45f4a992a17c.png">

The problem is with the **utf8_next**() function. This function before 5.2.4 didn't truncate non-Latin sentences in the output.

**Comment by linas** [comment]
Ah!  OK, I think I need to prepare a version 5.3.4 anyway, for other reasons so I will try to fix that.

**Comment by linas** [comment]
which version of windows is this?

**Comment by linas** [comment]
OK, can you apply the following patch, recompile, and confirm that it fixes the problem?
```
diff --git a/link-grammar/utilities.h b/link-grammar/utilities.h
index 5218b8b..7fd6fe0 100644
--- a/link-grammar/utilities.h
+++ b/link-grammar/utilities.h
@@ -235,6 +235,18 @@ static inline size_t utf8_strlen(const char *s)
  */
 static inline size_t utf8_next(const char *s)
 {
+#ifdef _MSC_VER
+       /* mbrlen does not work correctly on Windows. See issue #285 */
+       /* https://github.com/opencog/link-grammar/issues/285 */
+       size_t len = 0;
+       while (0 != *s)
+       {
+               if ((0x80 <= ((unsigned char) *s)) &&
+               (((unsigned char) *s) < 0xc0)) { s++; len++; }
+               else return len+1;
+       }
+       return len;
+#else
        size_t len;
        mbstate_t mbs;
        memset(&mbs, 0, sizeof(mbs));
@@ -243,8 +255,8 @@ static inline size_t utf8_next(const char *s)
                /* Too long or malformed sequence, step one byte. */
                return 1;
        }
-
        return len;
+#endif
 }
 
 static inline int is_utf8_upper(const char *s)
```

**Comment by linas** [comment]
OK, I just merged pull reuest #286 which does the same thing as the patch posted above.  If you can confirm that this solves the Windows problem, I will then issue a version 5.3.4 today the next few days.

**Comment by TatianaBatura** [comment]
It's Windows XP.
I'll try to test this patch tomorrow, because it's late here now.

**Comment by linas** [comment]
OK, If it doesn't work, the try `#ifdef _WIN32`  I'm confused as to which is the right one to use.

**Comment by TatianaBatura** [comment]
We recompiled and tested. Your patch fixed the problem.
