### ISSUE TITLE
Build break on Mac 

### ISSUE THREAD

**Issue by christian-storm** [opencog/link-grammar#297]
I hate to be the bearer of bad news but it seems the newest release is breaking on the very thing it was meant to fix (lg_fgetc).

Undefined symbols for architecture x86_64:
  "_lg_fgetc", referenced from:
     -exported_symbol[s_list] command line option
  "_lg_ungetc", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [liblink-grammar.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

**Comment by linas** [comment]
Which version? Yes,  it turned out if one does not have the libeditline, then this broke, in version 5.3.5 -- and I thought it got fixed in version 5.3.6 ... is it still broken with version 5.3.6?

BTW libeditline is what allows the arrow keys to work, so its recommended. Although some versions of editline are missing UTF8 support, which messes up the non-English LG.

**Comment by christian-storm** [comment]
I was trying to install 5.3.6 after noticing that the previous build I had reported a bug on was out of date.  Strangely 5.3.5 works fine and the arrow keys work.  I even tried compiling with the configure --disable-editline and it still breaks.  It appears my system only has readline and not editline in /usr/local.  Did you find or did someone report that 5.3.5 was breaking on El Capitan?

I can pass along my config.log file but I'm not sure that'll help.

**Comment by linas** [comment]
So .. I'm confused.  If you do have editline, then both 5.3.5 and 5.3.6 should be identical (and neither should have the ` Undefined symbol _lg_fgetc` bug.

If you do not have editline, then 5.3.5 has the ` Undefined symbol _lg_fgetc` bug, and 5.3.6 is supposed to fix that.  (There are no other differences between 5.3.5 and 5.3.6, other than adding the missing python test file)

So .. what you are reporting is pretty much exactly backwards from what I expect.  I don't know how to fix that.   Yes, posting the config.log would help.

**Comment by christian-storm** [comment]
I tried to help figure it out but to no avail.  I know it is strange and doesn't make sense to me either.  I did a find /usr | grep editline to make sure I don't have it installed.  I then tried running configure with --disable-editline and --enable-editline.  The build breaks both ways.  github won't let me attach that filetype so here is a link to it https://drive.google.com/file/d/0B9HjtV4kjINveTBjU1ZsVzBETWM/view?usp=sharing.

**Comment by linas** [comment]
Ahh, I think I see the problem.  Edit the file `link-grammar/link-grammar.def` and remove the two entries at the bottom (they say lg_fgetc and lg_ungetc) and build again.  I bet that will fix it!

**Comment by christian-storm** [comment]
Booya.  That did the trick.  I would've never have figured that out.  Glad I stopped when I did.

**Comment by christian-storm** [comment]
Thanks Linas.  Closing this out as fixed.

**Comment by linas** [comment]
Well, I'll publish yet another release, with just this in it.

**Comment by linas** [comment]
version 5.3.7 is on the website, it contains only this one fix.
