### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#302]
I propose the following:
1. Add directory msvc14 with project files for MSVC compilation.
2. **Remove the support** for MSVC9 and MSVC12, since the library code now uses c99 constructs which cannot be handled by these versions. Also, Visual Studio Community 15 (MSVC14) is a free Microsoft product. In addition I would like to add new macros for MSVC support, a thing that would anyway make the existing MSVC9/MSVC12 project files useless.
3. Put all the compilation directions only in msvc14/README. In the main README put only a reference to them.
4. Simplify and fix the compilation directions.

I already implemented (1), including auto generating of link-features.h from link-features.h.in (with configuration @macro@ replacement) and automatic creation of an appropriate link-parser.bat.
I also started with (3) and (4).

**Comment by linas** [comment]
This all sounds very reasonable to me.

**Comment by ampli** [comment]
Done in #312.
