### ISSUE TITLE
API Parsing Inconsistency

### ISSUE THREAD

**Issue by Cutha** [opencog/link-grammar#303]
I followed the official [API Guide](http://www.abisource.com/projects/link-grammar/api/index.html) and wrote a simple C++ test program.

For this sentence:
`I feel is the exciter than other things.`

The command-line parser can identify 10 linkages with 3 main variations in terms of the positions of null links:
1. `LEFT-WALL I.p feel.v [is] the [exciter] [than] other things.n . `
2. `LEFT-WALL I.p feel.v [is] the exciter[?].a [than] [other] things.n .`
3. `LEFT-WALL [I] [feel] is.v the exciter[?].n [than] other things.n .`

However, the API is only able to find 4 linkages and all of them are of the 2nd structure, i.e.
`LEFT-WALL [I] [feel] is.v the exciter[?].a [than] other things.n .`
with exciter either being guessed as adjective or noun and some minor differences in the linkage diagram (see output below).

Is the API being updated along with the parser? I looked at link-includes.h and it lacks documentation. I have played with certain parse options such as max null count / disjunct cost etc. but it still doesn't give me the same result as the command-line tool. Also, the [another example] (http://www.abisource.com/projects/link-grammar/api/index.html#preps_example) in the API guide doesn't run either. It includes "constituents.h" which doesn't seem to exist in the lib directory after installation. Below the example, it says "functions used are described in the section on extracting constituent structure" and that link isn't working either. The whole API guide seems to be a messy mix of outdated and new information. 

Below is my test code for reference:
```
Dictionary    dict;
Parse_Options opts;
Sentence      sent;
Linkage       linkage;
int           i, num_linkages;

setlocale(LC_ALL, "");
opts  = parse_options_create();
dict  = dictionary_create_default_lang();

string s = "I feel is the exciter than other things.";

sent = sentence_create(s.c_str(), dict);
num_linkages = sentence_parse(sent, opts);
cout << "Number of null links: " << sentence_null_count(sent) << endl;
cout << "Number of linkages: " << sentence_num_linkages_found(sent) << endl;
cout << "Number of valid linkages: " << sentence_num_valid_linkages(sent) << endl;
cout << "Number of linkages post-processed: " << sentence_num_linkages_post_processed(sent) << endl;

for (int i=0; i<num_linkages; ++i)
{
    linkage = linkage_create(i, sent, opts);
    cout << linkage_print_diagram(linkage, true, 800);
    cout << "Number of post-processed violations: " << sentence_num_violations(sent, i) << endl;
    cout << "Total sum of disjunct costs: " << sentence_disjunct_cost(sent, i) << endl;
    cout << "Total length of links: " << sentence_link_cost(sent, i) << endl;
    linkage_delete(linkage);
}
sentence_delete(sent);
dictionary_delete(dict);
parse_options_delete(opts);
```

This is the output:
```
link-grammar: Info: Dictionary found at /home/cutha/Desktop/link-grammar/share/link-grammar/en/4.0.dict
I feel is the exciter than other things.
Number of linkages: 4

Number of null links: 3
Number of linkages: 4
Number of valid linkages: 4
Number of linkages post-processed: 4

    +------------------------------Xp------------------------------+       
    |            +---------------------Op---------------------+    |       
    +---->WV---->+         +----------------Dmc---------------+    |       
    +--Wd--+-Sp*i+         |        +------------A------------+    +--RW--+
    |      |     |         |        |                         |    |      |
LEFT-WALL I.p feel.v [is] the exciter[?].a [than] [other] things.n . RIGHT-WALL 

Number of post-processed violations: 0
Total sum of disjunct costs: 0.04
Total length of links: 19

    +------------------------------Xp------------------------------+       
    |            +---------------------Op---------------------+    |       
    +---->WV---->+         +----------------Dmc---------------+    |       
    +--Wd--+-Sp*i+         |        +------------AN-----------+    +--RW--+
    |      |     |         |        |                         |    |      |
LEFT-WALL I.p feel.v [is] the exciter[?].n [than] [other] things.n . RIGHT-WALL 

Number of post-processed violations: 0
Total sum of disjunct costs: 0.1
Total length of links: 19

    +------------------------------Xp------------------------------+       
    |            +---------------------Op---------------------+    |       
    |            |         +----------------Dmc---------------+    |       
    +--Wd--+-Sp*i+         |        +------------A------------+    +--RW--+
    |      |     |         |        |                         |    |      |
LEFT-WALL I.p feel.v [is] the exciter[?].a [than] [other] things.n . RIGHT-WALL 

Number of post-processed violations: 0
Total sum of disjunct costs: 4.04
Total length of links: 18

    +------------------------------Xp------------------------------+       
    |            +---------------------Op---------------------+    |       
    |            |         +----------------Dmc---------------+    |       
    +--Wd--+-Sp*i+         |        +------------AN-----------+    +--RW--+
    |      |     |         |        |                         |    |      |
LEFT-WALL I.p feel.v [is] the exciter[?].n [than] [other] things.n . RIGHT-WALL 

Number of post-processed violations: 0
Total sum of disjunct costs: 4.1
Total length of links: 18
link-grammar: Info: Freeing dictionary en/4.0.dict
link-grammar: Info: Freeing dictionary en/4.0.affix
```

**Comment by ampli** [comment]
Hello Cutha,
As you observed, the API doc is severely out of date.
For the problem you encountered (how to parse with null-count > 0), it seems the original one (from CMU) was already out of date (or was rather incomplete).

It turns out that is that if you would like to parse with null-count=0 to N (N=number of sentence words), you must do it in two steps. This is because of a special optimization that is done in the library for the case of null-count=0 **before** the actual parsing starts (function possible_connection () in prune.c).
This optimization is wrong for null-count>0. So if max_null_count>0, then for correct results min_null_count should not be 0. I guess this must be documented, and even enforced.

Here is a demo of the said 2 steps :
```
	sent = sentence_create(s.c_str(), dict);
	sentence_split(sent, opts); // for sentence_length(sent)
	cout << "Sentence length: " << sentence_length(sent) << endl;

	bool allow_nulls = false;
	while (true)
	{

		num_valid_linkages = sentence_parse(sent, opts);
		if (num_valid_linkages < 0)
		{
			cout << "sentence_parse() returned error value %d, exiting." << num_valid_linkages << endl;
			exit(1);
		}
		if (allow_nulls) break;
		if (num_valid_linkages == 0)
		{
			allow_nulls = true;
			parse_options_set_min_null_count(opts, 1);
			parse_options_set_max_null_count(opts, sentence_length(sent));
		}
	}
```
(Note that sentence_parse() actually returns the number of valid linkages, so I change the variable name for clarity.)

**Comment by Cutha** [comment]
Many thanks. Tremendously informative. In short, just by adding this api works for me:
`parse_options_set_min_null_count(opts, 1);`

**Comment by linas** [comment]
I'm re-opening this, and will keep it open until I get a chance to fix the API docs.

**Comment by linas** [comment]
Never mind, I see #305 covers this.

**Comment by ampli** [comment]
After thinking more on this problem (correct parse results when setting **min_null_count=0** and **max_null_count>0**), it seems it is better to fix it in the library than document it as a limitation (and/or disallow these value combinations). I will send a pull request for that.

**Comment by linas** [comment]
Yes, that is actually the better fix!
