### ISSUE TITLE
configure script missing

### ISSUE THREAD

**Issue by chris-hawley** [opencog/link-grammar#335]
the configure script is missing. Thus, ./configure no longer works.

**Comment by linas** [comment]
missing from where? 
```
tar -ztvf link-grammar-5.3.7.tar.gz |grep configur
-rwxrwxr-x 500/500      671694 2016-05-07 21:49 link-grammar-5.3.7/configure
-rw-rw-r-- 500/500       26082 2016-05-07 21:46 link-grammar-5.3.7/configure.ac
```

There is no configure in github, because github is not intended for end-users, its intended for maintainers only.

**Comment by chris-hawley** [comment]
I was using the github version.
