### ISSUE TITLE
/* XXX FIXME in the future, linkage->num_words might not match sent->length */

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#37]
In which situations such a thing can happen?

1. When the parser processes the current word-array, it seems there should be one linkage word for each sentence word, so they must be equal.
2. If the parser is changed to process the word graph, sent->length will not exist then.
 
Did I miss something? Is there another situation?

**Comment by linas** [comment]
whoops ... I just accidentaly merged something into master that should have waited until after 5.2.5.

If your wordgraph code is ready, it can now be merged. I notice that you havenot created a pull request for it.

Meanwhile, fixes for 5.2.5 will have to go into a different branch, 5.2.x-maintenance  Just FYI. ... I made a mistake which will complicate 5.2.5 ...

**Comment by ampli** [comment]
After the recent changes, the pull request now is not clean.
Hence I would like to rebase it on your current master.
I guess nobody based any work on it yet...

I currently have a branch **wordgraph**, which has messed commits, and a fixed one **wordgraph1**.
So I will rebase **wordgraph1** and rename it to **wordgraph**, and send you a pull request.

**Comment by linas** [comment]
Its not urgent.  I just wanted to tell you I made the mistake.  If you have any fixes for 5.2.5, they should apply to the bracnh called `5.2.x-maintenance`

**Comment by ampli** [comment]
I have fixes for 5.2.5. I installed MSVC13 in order to test their Windows compatibility. I currently try to install a 64bit regex library... If you know one that I can just download and extract - in a binary form - this may save me much work.

**Comment by linas** [comment]
No clue about windows regex.

**Comment by ampli** [comment]
I think the following is the only open issue here (besides of this
>Removal of sent->word is in the distant future,

which can be deferred until a further notice).

--

ampli commented on Jan 23, 2015
>I currently try to install a 64bit regex library

In order to close this issue, here is the solution for that, from my post to the LG group:

>[...]I generated regex.lib from libtre-0.7.5 as follows, using dlltool from cygwin (I don't know if there is a better way):
dlltool -l regex.lib -d libtre/win32/tre.def -D regex.dll libtre/win32/bin/x64_release/libtre_dll.dll
