### ISSUE TITLE
Breaking build on MacOS

### ISSUE THREAD

**Issue by christian-storm** [opencog/link-grammar#374]
The commit 74f421656e6b285a4410f6e6f0b0fabbae11bf5e breaks my build:

```
In file included from ../../link-grammar/corpus/corpus.h:16:
../../link-grammar/corpus/../utilities.h:172:13: error: typedef redefinition with different types ('int' vs 'struct _xlocale *')
typedef int locale_t;
            ^
/usr/include/xlocale.h:34:28: note: previous definition is here
typedef struct _xlocale *               locale_t;
```

**Comment by ampli** [comment]
Probably locale_t is not detected by `configure` because it is in `xlocale.h` instead of `locale.h`.
I guess I will need to add such a check to `configure.ac`.
For a compilation test, please try to add the following at the top of `utilities.h`:
```
#define HAVE_LOCALE_T 1
```

Did you add `#include <xlocale.h>`, or is it somehow got included indirectly? (If so - from which other include file?)

**Comment by christian-storm** [comment]
I didn't add xlocale.h.  It must've been included indirectly.  After running make I grepped for xlocale and found these dependencies:
grep -r xlocale *
```
link-grammar/minisat/.deps/Solver.Plo:  /usr/include/locale.h /usr/include/_locale.h /usr/include/xlocale.h \
link-grammar/sat-solver/.deps/sat-encoder.Tpo:  /usr/include/locale.h /usr/include/_locale.h /usr/include/xlocale.h \
```

Adding to utilities.h at the top didn't work.
 ```
**#define HAVE_LOCALE_T 1**
 #ifndef _LINK_GRAMMAR_UTILITIES_H_
 #define _LINK_GRAMMAR_UTILITIES_H_
```
It caused other issues
```
../../link-grammar/corpus/../utilities.h:171:1: error: unknown type name 'locale_t'
locale_t newlocale_LC_CTYPE(const char *);
^
../../link-grammar/corpus/../utilities.h:271:48: error: unknown type name 'locale_t'
static inline int is_utf8_upper(const char *s, locale_t dict_locale)
                                               ^
../../link-grammar/corpus/../utilities.h:284:48: error: unknown type name 'locale_t'
static inline int is_utf8_alpha(const char *s, locale_t dict_locale)
                                               ^
../../link-grammar/corpus/../utilities.h:297:48: error: unknown type name 'locale_t'
static inline int is_utf8_digit(const char *s, locale_t dict_locale)
                                               ^
../../link-grammar/corpus/../utilities.h:310:48: error: unknown type name 'locale_t'
static inline int is_utf8_space(const char *s, locale_t dict_locale)
                                               ^
../../link-grammar/corpus/../utilities.h:371:67: error: unknown type name 'locale_t'
void downcase_utf8_str(char *to, const char * from, size_t usize, locale_t);
                                                                  ^
../../link-grammar/corpus/../utilities.h:372:65: error: unknown type name 'locale_t'
void upcase_utf8_str(char *to, const char * from, size_t usize, locale_t);
                                                                ^
In file included from util.cpp:1:
In file included from ./util.hpp:6:
../../link-grammar/api-structures.h:127:2: error: unknown type name 'locale_t'
        locale_t        locale_t;
```
I noticed this in config.log
```
configure:16388: checking for locale_t
configure:16388: gcc -c -g -O2  conftest.c >&5
conftest.c:36:13: error: use of undeclared identifier 'locale_t'
if (sizeof (locale_t))
            ^
1 error generated.
configure:16388: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "link-grammar"
| #define PACKAGE_TARNAME "link-grammar"
| #define PACKAGE_VERSION "5.3.9"
| #define PACKAGE_STRING "link-grammar 5.3.9"
| #define PACKAGE_BUGREPORT "link-grammar@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "link-grammar"
| #define VERSION "5.3.9"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define STDC_HEADERS 1
| #define HAVE_STRNDUP 1
| #define HAVE_ALLOCA_H 1
| #define HAVE_ALLOCA 1
| #define HAVE_FORK 1
| #define HAVE_VFORK 1
| #define HAVE_WORKING_VFORK 1
| #define HAVE_WORKING_FORK 1
| /* end confdefs.h.  */
| #include <locale.h>
| 
| int
| main ()
| {
| if (sizeof (locale_t))
|        return 0;
|   ;
|   return 0;
| }

```

**Comment by ampli** [comment]
I will try to fix that.

**Comment by christian-storm** [comment]
Is there a patch I can try to see if it is fixed?

**Comment by ampli** [comment]
I just got a Mac, which runs El-Capitan **10.11.6**.
My `gcc` was actually `clang` (I guess yours too.)
I didn't get any compilation problem (besides on minisat, so I used --disable-sat-solver).
I used this configuration:
```
configure \
	--disable-sat-solver \
	--enable-wordgraph-display \
	--enable-python-bindings \
	--disable-java-bindings \
```
The result was a well-working link-parser.
(Only the backtick test failed - I still need to investigate why.).

However, `locale_t` still didn't get detected, so it was without the dynamic per-dictionary locale support (a thing which shouldn't cause a problem on a typical use.) Now that I have a Mac, I will fix and test this detection problem (and will send a PR ASAP).

In any case, my question is which OS-X version do you have.

**Comment by christian-storm** [comment]
My apologies for the long delay in replying.  I've been traveling.

I'm running 10.11.6 as well.  Here is some information regarding gcc/clang:

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I confirmed that --disable-sat-solver allows me to compile on my machine as well.

Thanks!

**Comment by linas** [comment]
Eh? The locale_t issues are not in the sat solver, they're in utilities.h

What is the sat-solver problem?

**Comment by christian-storm** [comment]
Beyond my pay grade...I defer to Amir.

**Comment by linas** [comment]
Oh, I see, I had to reread the above.  Its useful to post the error messages, as otherwise, I am left to guess.

**Comment by ampli** [comment]
> What is the sat-solver problem?

The minisat code contains several incorrect "%zu" usages is Solver.h, that generate warnings (all in printStats()). An incorrect printing can happen at most (not a crash).

After fixing the locale_t detection problem, SAT can be enabled again. The problem can also easily be fixed (I will send a PR).

When @christian-storm had the problem, HAS_LOCALE_T was still not defined, and as a result,
locale_t was typedef'ed as `int` (it just has to be typedef'ed as something for code simplicity).
It didn't make a problem in the C code, but somehow xlocale.h got indirectly included in the SAT code and the definition of locale_t in it conflicted with this dummy typedef.

So thanks to the format error in minisat the incorrect locale_t detection on OS X has been found and fixed.

**Comment by linas** [comment]
OK, so version 5.3.10 is now published, and should resolve this problem. ... if there are new issues with that, please open a new bug report.

Download here:  http://www.abisource.com/downloads/link-grammar/5.3.10/link-grammar-5.3.10.tar.gz
