### ISSUE TITLE
Github release has missing files

### ISSUE THREAD

**Issue by christian-storm** [opencog/link-grammar#375]
The 5.3.9 release at https://github.com/opencog/link-grammar/releases is different than the one at 
http://www.abisource.com/projects/link-grammar/#download.

diff -q abisource-link-grammar-5.3.9 github-link-grammar-5.3.9
Only in link-grammar-link-grammar-5.3.9: .gitignore
Only in link-grammar-5.3.9: Makefile.in
Only in link-grammar-5.3.9: aclocal.m4
Only in link-grammar-5.3.9: compile
Only in link-grammar-5.3.9: config.guess
Only in link-grammar-5.3.9: config.sub
Only in link-grammar-5.3.9: configure
Only in link-grammar-5.3.9: depcomp
Only in link-grammar-link-grammar-5.3.9: diary
Only in link-grammar-5.3.9: install-sh
Only in link-grammar-5.3.9: link-grammar.spec
Only in link-grammar-5.3.9: ltmain.sh
Only in link-grammar-5.3.9: m4
Only in link-grammar-5.3.9: missing
Only in link-grammar-5.3.9: py-compile
Only in link-grammar-5.3.9: test-driver

**Comment by linas** [comment]
That's right. github automatically creates these incorrect tar files, and I don't know how to make it stop.  It's a whizzy feature that someone who works for github thinks is whizzy, but it breaks actual releases.

**Comment by AmeBel** [comment]
@linas I don't think you can disable it. But, you could upload the actual release or other binaries as described @ https://github.com/blog/1547-release-your-software. I created a sample release @ https://github.com/amebel/link-grammar/releases

**Comment by linas** [comment]
It would be better if I could just disable toe github release mechanism entirely.  That last thing I need is to have yet more complexity and make-work in the release process...

**Comment by ryandesign** [comment]
> It would be better if I could just disable toe github release mechanism entirely.

There is no way to disable it. The best thing to do is to upload your manually-created release tarballs to the GitHub releases, rather than to mark each GitHub release with the off-putting title "do not use" and the inaccurate "pre-release" label.

Incidentally your latest GitHub release is the years-old 5.10.2 even though you have released 5.12.4 just weeks ago. Please create a GitHub release for each released version of your software.

**Comment by linas** [comment]
I don't know how to fix this.  If github is publishing a years-old release, when there are obviously newer releases available, ... that sounds like a github bug, and needs to be fixed upstream.

Ideally, it would be possible to disable this entire subsystem. I don't have the energy to take on a corporate behemoth in some quixotic battle to fix the release tarball strategy.

**Comment by linas** [comment]
Huh! OK, I looked more carefully.

It would seem that github stopped making automatic releases just after 5.10.2 , which explains why things stopped there. They also added a button to delete releases, which solves the fundamental problem of having broken releases, albeit in a rather crude, brute-force kind of way.  I clicked that button 100 times; and deleted them all.
