### ISSUE TITLE
make only vs only make

### ISSUE THREAD

**Issue by christian-storm** [opencog/link-grammar#411]
"My phone can make only calls to family in this area." doesn't parse but
"My phone can only make calls to family in this area." does.

Both are grammatically correct[1].  The first (before main verb) implies the phone has no texting ability.  The second (before object) implies it only has one function.

[1]http://www.grammar-quizzes.com/adv_focus.html

**Comment by linas** [comment]
Huh. Its a somewhat awkward usage, but OK.
Also:
My phone can make calls only to family  in this area
My phone can make calls to family only in this area

**Comment by linas** [comment]
OK -- fixed in commit 49d65b8a4e95c30b2791a94ad6e4fae4d227f31d  -- you can hand-patch your files, if you wish or wait for version 5.3.11 which might be out in a few months or so.

**Comment by christian-storm** [comment]
Thanks Linas!  I think I'm fast approaching owing you lunch.  

I keep running into this one and it is tricky.  'Only' is insidious and can modify words or phrases.  For what it's worth, I agree with you regarding which is the least awkward of the bunch.

**Comment by linas** [comment]
closing as 'fixed'
