### ISSUE TITLE
Configuring Python2 and Python3 bindings at the same time

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#419]
I propose to add the ability to configure both Pyhon bindings at the same time.
The configure script will just use the version it finds, and if it finds both, it will use both.

The problem is that the provided autoconf Python detection macros cannot do that.
Other packages overcame that by providing their own autoconf code for that.

For example: [libpeas/autoconf.ac](https://github.com/gregier/libpeas/blob/8cae6abc21bb2ca18533a3f1806288be633cfc22/configure.ac#L361)

I propose to copy it (it is LGPL'ed).
If this is a good idea, I will send a PR.

BTW, I thought than then it can be a good idea to make the scripts run by Python3 if it is availble, but I don't know how to do that besides having tests.py.in etc., which is cumbersome and and makes developing harder.

**Comment by linas** [comment]
Sigh. As if our autoconf file wasn't too big already.  Sure.

Also, we should enable a build of python bindings by default, if python headers/libs are installed.

**Comment by ampli** [comment]
I still need to implement this:
>FIXME: If both versions cannot be configured, a configuration error should be generated unless --disable-python-bindings is given.
