### ISSUE TITLE
Recommendation for how distro packaging should depend on system minisat?

### ISSUE THREAD

**Issue by jbicha** [opencog/link-grammar#427]
I just packaged 5.3.11 for Debian and I'm wondering how to handle the minisat dependency.

Debian packaging has 3 levels for dependency status:
- Depends (absolutely required)
- Recommends (installed by default but the package should still work if this dependency isn't installed)
- Suggests (not automatically installed but some tools list it as optional)

And do we want to have the dependency from the **liblinkgrammar5** package (installed on many computers because Abiword's grammar checker uses it) or from **link-grammar** (provides _/usr/bin/link-parser_ and installed on far fewer machines)?

**Comment by jbicha** [comment]
Pinging @ampli in case he's not subscribed to issues here

**Comment by jbicha** [comment]
Never mind. It looks like liblink-grammar5 needs to depend on minisat which is what I did.
```
ldd /usr/lib/x86_64-linux-gnu/liblink-grammar.so.5.3.11
	linux-vdso.so.1 =>  (0x00007ffcd54b5000)
	libhunspell-1.4.so.0 => /usr/lib/x86_64-linux-gnu/libhunspell-1.4.so.0 (0x00007f62d6232000)
	libminisat.so.2 => /usr/lib/libminisat.so.2
```

**Comment by linas** [comment]
I guess I should leave well-enough alone.

The abiword grammar checker does not use the minisat component, so in principle, you could even compile with sat disabled, and things will work. Most users would probably not notice. However, I can't really tell... there seem to be some lurkers who use it but don't say what for.

**Comment by jbicha** [comment]
I don't think the minisat dependency is a problem. Perhaps it could be made optional in the future (link-grammar will use libminisat if it finds but won't fail to start if it's not present).

Using the system minisat is a good thing and fixes some minor issues I had with the Debian packaging. I wasn't even aware that it was a 3rd party library before!

**Comment by ampli** [comment]
Linas,
Should the library be changed to just load libminisat if use_sat=1 is set?
If it is not found it can just notify that it needs to be installed for that feature to work.

**Comment by linas** [comment]
dynamic-load? Sure, I guess. I mostly wouldn't care except for some classic arguments:
-- it requires you to write new dylib dynamic loader wrappers (more work)
-- which increases the complexity of the system, and as a result
-- will probably expose bugs on MacOS, Windows
-- resulting in complaints and yet more work...

Do the benefits of dynamic loading surpass the negatives above?

**Comment by ampli** [comment]
You are right. So I will implement the static linking (issue #431).
