### ISSUE TITLE
Problem: In case the bundled libminisat is used, it is installed in the system

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#431]
This is rather problematic because it uses a name that may clash with a package that provides such a library (that may even be incompatible, and in that case LG must use the bundled version), and because this is not a real minisat2 library, as some unneeded (by sat-solver) source files are not even compiled into it.

I propose to use a static lib for the bundled minisat.

**Comment by linas** [comment]
Sure. static-link it to libsat-solver.so.0 which, by the way, should probably get bumped to version 6 in the makefile.

**Comment by ampli** [comment]
> Sure. static-link it to libsat-solver.so.0 which, by the way, should probably get bumped to version 6 in the makefile.

Note that libsat-solver is static for some time now. I don't have an idea where to set its version.

So I guess it should be linked to liblink-grammar in the same manner libsat-solver is linked to it,
and its link to link-parser and java-jni should be removed.

Please confirm that I didn't miss something, and I will send a PR.

**Comment by linas** [comment]
Oh, OK, right about the version number.  I was looking at my `/usr/local/lib` which still has an old, obsolete `libsat-solver.so.0.4.0` installed in it.

**Comment by ampli** [comment]
Solved in PR #444.
