### ISSUE TITLE
Python install/uninstall bugs

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#439]
**1)** Python3 install byte-code compile fails:

```
linkgrammar.py__init__.pyclinkgrammar.py  File "/usr/lib/python3.5/site-packages/linkgrammar/clinkgrammar.py", line 115
    def linkgrammar_get_version() -> "char const *":
                                  ^
SyntaxError: invalid syntax
```

Edit: Fixed in PR #440.

**2)** On debian & ubuntu the linkgrammar module install location for python2 is
`/usr/local/lib/python2.7/dist-packages`
and for python3 is `/usr/local/lib/python2.7/site-packages` (note the last directory component).
It seems strange.
EDIT:
I probably meant something like:
`/usr/local/lib/python3.4/site-packages`

**3)** On debian, debbuild gives these errors:

```
dh_install --fail-missing
dh_install: usr/lib/python3.5/site-packages/linkgrammar.pth exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/__init__.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/_clinkgrammar.so.5 exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/linkgrammar.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/_clinkgrammar.so.5.3.12 exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/clinkgrammar.py exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/_clinkgrammar.so exists in debian/tmp but is not installed to anywhere
dh_install: usr/lib/python3.5/site-packages/linkgrammar/__pycache__/clinkgrammar.cpython-35.pyc exists in debian/tmp but is not installed to anywhere
...
dh_install: usr/lib/python3.5/site-packages/linkgrammar/__pycache__/__init__.cpython-35.opt-1.pyc exists in debian/tmp but is not installed to anywhere
dh_install: missing files, aborting
```

Two things:
- What is the reason of this problem? When I do "make install" after a standard configure/make procedure, python3 seems to be installed fine.
- Is **pycache** supposed to be installed, or to be generated in the installation process?

**4)** Python uninstall:
python2: The package directory linkgrammar remains.
python3: The package directory linkgrammar remains with `__pychache__` in it.

Are these directories supposed to be removed too?

Edit: 4) fixed in d8676fbfc07cf8a68d5fffc670091636ef3a0959

Any hint for 2-4 is appreciated much before I dedicate time to look into these problems.

**Comment by linas** [comment]
Re part 2) -- yes, there seems to be a difference between python2 and python3 install locations; I observed this before, with other systems. It is indeed strange, but it seems that maybe this was one of the major changes between how python2 and 3 work.  However, I did not google this or investigate it too deeply, so maybe it is an error, or is subtle in some way.

Re part 4) -- ideally, uninstall uninstalls everything. However, uninstall is always one of those third-class citizens of package management...

**Comment by ampli** [comment]
Part 2 is not really a "bug", as I found this in /usr/lib/python2.7/site.py of Debian:

**For Debian and derivatives, this sys.path is augmented with directories
for packages distributed within the distribution. Local addons go
into /usr/local/lib/python<version>/dist-packages, Debian addons
install into /usr/{lib,share}/python<version>/dist-packages.
/usr/lib/python<version>/site-packages is not used.**

Part 4 can be fixed, but there is maybe no much point to do so.

So the remaining part to fix is 3, but I still don't know the reason of the apparent problem.

**Comment by linas** [comment]
is this fixed now, or are there problems still?

**Comment by linas** [comment]
current python2 bindings installs into:
```
/usr/local/lib/python2.7/dist-packages/linkgrammar
```
and that is where they've been going for the last two years.  Current python3 packages install into
```
/usr/local/lib/python3.5/site-packages/linkgrammar
```
and I used to believe that is correct, based on python documentation.  I believe that is how it worked for Ubuntu trusty 14.04

However, I currently notice that `/usr/lib/python3/site-packages` does not even exist on ubuntu xenial 16.04 nor on debian.  By contrast, on CentOS 5.11, however, there are no sub-directories containing the string `dist-packages` anywhere, everything, including python 2.4 installed into `site-packages` on CentOS.     So the correct install target now appears to be distro-specific.  However, that version of CentOS is maybe 5+ years old, and trusty is almost 3 years old, so it appears that the modern location for everything is `dist-packages`.

except what I say about xenial up above is ... wrong.  I see stuff installed in 
```
lib/python2.7/site-packages/pyasn1_modules
lib/python2.7/site-packages/pip/
lib/python3.5/site-packages/boost
```

so `pip` is a mjor python tool, and it thinks it belongs in site, not dist. so wtf.  I'm totally confused.

**Comment by linas** [comment]
I just fixed item 4)

**Comment by ampli** [comment]
Problems 1 and 4 are already fixed.
We don't have anything to do about 2.
I don't know if problem 3 was due to a packaging problem at the version I checked, and I hope the Debian package manager will notify us if there are still problems that need fixing.
So I'm closing this issue.
