### ISSUE TITLE
syntax error near unexpected token `ZLIB_CPPFLAGS="-isystem $ZLIB_HOME/include

### ISSUE THREAD

**Issue by ptrakk** [opencog/link-grammar#452]
checking for native Win32... no
checking for Cygwin... no
checking for 64-bit Apple OSX... no
./configure: line 17462: syntax error near unexpected token `ZLIB_CPPFLAGS="-isystem $ZLIB_HOME/include",'
./configure: line 17462: `		AX_CHECK_ZLIB(ZLIB_CPPFLAGS="-isystem $ZLIB_HOME/include",)'

**Comment by ampli** [comment]
I would like to reproduce the problem, so I need some more details:

- Did you use 5.3.11, or is it the current repository version?
- Your exact system version may help (if I can get this problem when testing it on that system).
- Please provide the section of `configure` which includes the reported line number (17462). This section starts with the line "# Locate zlib, if wanted" and includes about 100 lines.

**Comment by ptrakk** [comment]
current repository version.
I'm running kali-linux

`
		{ $as_echo "$as_me:${as_lineno-$LINENO}: The minisat2 headers include zlib.h" >&5
$as_echo "$as_me: The minisat2 headers include zlib.h" >&6;}
		AX_CHECK_ZLIB(ZLIB_CPPFLAGS="-isystem $ZLIB_HOME/include",)
	test "x$ZLIB_CPPFLAGS" = "x-isystem /usr/include" && ZLIB_CPPFLAGS=

`

**Comment by ptrakk** [comment]
[configure](https://github.com/opencog/link-grammar/files/599146/configure.TXT)

**Comment by ptrakk** [comment]
[autogen.err](https://github.com/opencog/link-grammar/files/599158/autogen.err.txt)

**Comment by ampli** [comment]
It looks as if the package `autoconf_archive` is missing in your system.
Try to install it.

**Comment by ampli** [comment]
It is actually called `autoconf-archive`.

**Comment by ptrakk** [comment]
Thanks! works now

**Comment by KnowledgeGarden** [comment]
On Ubuntu 16.04, I installed autoconf-archive and still get the error at line 17463.  Not sure what I am missing now

**Comment by KnowledgeGarden** [comment]
Cancel that. I switched to a release. That configured okay. Now a different compile issue.
