### ISSUE TITLE
configure crashes when python is not installed

### ISSUE THREAD

**Issue by linas** [opencog/link-grammar#458]
Another serious bug: lg configure now crashes when python is not installed.  This is bad, its breaking lots of scripts.

**Comment by ampli** [comment]
This of course can be fixed. Should it notify something in that case (because the default is to provide Python bindings)?

**Comment by linas** [comment]
fixed in pull #459 and version 5.3.13 released

**Comment by linas** [comment]
The goal is not to crash during the build, ad 5.3.13 now does that.

**Comment by linas** [comment]
Anyway, the check for java in configure.ac is a good model for how to do this. So, by default: the java build is enabled, but if java is not found, it prints warnings and continues. 

The current python warnings are probably sufficient.  They are pretty large, and hard to miss, if you look for them.
