### ISSUE TITLE
Missing /build after make install Ubuntu 16.04

### ISSUE THREAD

**Issue by KnowledgeGarden** [opencog/link-grammar#462]
On the 5.3.10 release tarball:
./configure
sudo make install
No error warnings. Installed data in /usr/share
But, the java bindings shell script says to find linkgrammar.jar in ../../build/bindings/java/bin:  
I do not find such a directory; also says to look in /usr/share/java/linkgrammar.jar
Nothing there. Besides, the actual jar it built is linkgrammar-5.3.10.jar, so the shell script does not appear correct in any case.
I have a possibly wrong expectation that the *.so files would be found in /usr/lib
Nothing of that kind there.

In any case, I boot the java shell script and it says Starting Link Grammar Server at port 9000, with 1 available processing threads and with default dictionary location.

In another console, I echo a message suggested in the document and it returns nothing. Meanwhile, the server crashed with an unsatisfiedlink error: no  linklib-grammar-java.so.5.3.10 in /usr/local/lib/

What might I be missing?

**Comment by linas** [comment]
Sorry for the very very late reply; I am seeing this message only now.

I guess that particular shell script was meant to be an example only, which you should tune for your config. I'll try to fix it up to be more general. 

A file called `liblink-grammar-java.so.5.3.10` should have been buiolt and installed, but you wrote `linklib` .. is that a typo?

**Comment by linas** [comment]
closing, stale bug.
