### ISSUE TITLE
Eliminating the empty-word device

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#468]
I succeeded to eliminate it.
It turned out the needed modification was rather small.
The main change is in do_count(). The rest is for supporting it.

**structures.h**:
```c
struct Word_struct
{
...
	bool optional;       /* Linkage is optional. */
}
```
**tokenize.c**:
```c
if (!empty_word_encountered)
{
#if 0
					if (!sent->dict->empty_word_defined)
						prt_error("Error: %s must be defined!\n", EMPTY_WORD_DOT);
					if (!determine_word_expressions(sent, empty_word(), &ZZZ_added))
						error_encountered = true;
#endif
					sent->word[sent->length - 1].optional = true;
...
}
```
**prune.c**:
```c
static bool optional_gap(Sentence sent, int w1, int w2)
{
	for (int w = w1+1; w < w2; w++)
		if (!sent->word[w].optional) return false;

	return true;
}

static bool possible_connection(...)
{
...
	if (no_null_links &&
	    (lc->next == NULL) &&
	    (rc->next == NULL) &&
	    (!lc->multi) && (!rc->multi) &&
	    !optional_gap(sent, lword, rword))   // <-----------
	{
		return false;
	}
...
}
```
**count.c**:
```c
/**
 * Return the number of optional words strictly between w1 and w2.
 */
static int num_optional_words(count_context_t *ctxt, int w1, int w2)
{
	int n = 0;

	for (int w = w1+1; w < w2; w++)
		if (ctxt->local_sent[w].optional) n++;

	return n;
}

static Count_bin do_count(...)
...
{
...
			if (null_count == (rw-lw-1) - num_optional_words(ctxt, lw, rw))
...
}

```

**Results**:
1). The run-time saving seems to be small (~1%, even for Russian).
This is strange since a test I did (reported in issue #250) shows that setting the `ZZZ` distance during expression-pruning causes a vast speedup.
2). This change automatically solves issue #241 (Disjunct strings sometimes have ZZZ in them).

**Adding `ZZZ+`**:
Note that a `ZZZ` connector (not related to the empty-word device) is still needed for handling quotes.
Currently, when a quote token appears (identified in the code by its `ZZZ-`), a `ZZZ+` is inserted on the previous word.
On first glance it seems this (i.e. inserting `ZZZ+`) can be eliminated by a small change in  num_optional_words()  - count also tokens with  `ZZZ-`. In that way unlinked quote tokens will still be able to appear in the result (even without marking them as null-words), when some of them even be linked with `QUc`/`QUd` exactly as now. I can implement it if desired.

**A remaining problem**:
The SAT parser doesn't work with this change.
To support it, a mechanism to ignore words should be added.
This will automatically solve making linkages with null-count > 0.
I have an idea how to do that, but I need to investigate the SAT-parser code (and SAT solving in general) more deeply.

EDIT: Add ifdef'ed-out removed code in **tokenize.c**.

**Comment by linas** [comment]
Excellent!  I'm confused by this:
```
sent->word[sent->length - 1].optional = true;
```
I don't see optional being set anywhere else, and I can't image why you'd only set it on the last word. 

The term `optional` seems strange: are you suggesting that there will still be tokens in the word stream, but linking to them is optional? 

Perhaps if you made a prototype pull request (even if its not ready for merging) I could look at it.

**Comment by ampli** [comment]
>    `sent->word[sent->length - 1].optional = true;`
> I don't see optional being set anywhere else, and I can't image why you'd only set it on the last word.

It is actually not the last word, but the current word, as the `alternatives` array is being constructed in this function and is extended by one word each time. So when the need for empty word is encountered, instead of issuing an empty-word, I just mark this `alternatives` slot as optional.

>The term optional seems strange: are you suggesting that there will still be tokens in the word stream, but >linking to them is optional?

Note that the said slot (that is marked as optional) is the one  that used to have the empty-word issued into it. Since the empty-word makes the use of the other words in this slot optional (as the empty-word can be linked and discarded, as if the words on this slot had never existed), I called it an optional slot,
because it is permitted for the parser to just disregard it **if needed** (not even an empty-word in it to get linked instead of the other words).

I ran detailed linkages comparison of en/basic / en/fixes / ru/basic (producing up to 1.8M linkages per sentence and comparing the first 200K for each). There were diffs, but I found they just uncovered **existing bugs**. These bugs still need a fix (I will send a PR soon).

I will prepare a PR for the empty-word elimination.
However, please note that it cannot be applied at this time because it makes the SAT-parser buggy due to the missing empty-words.

**Comment by linas** [comment]
Hey, what's-a-matter, don't you guys celebrate Christmas, there in Israel? :-)

**Comment by ampli** [comment]
Closing, as #477 and #478 just got applied.
