### ISSUE TITLE
clang compilation issues

### ISSUE THREAD

**Issue by agayardo** [opencog/link-grammar#51]
Compiling under clang has the following issues:

1. WARNING: unknown warning option '-Wunsafe-loop-optimizations'

2. WARNING: utilities.c:235:6: warning: no previous prototype for function 'lg_mbrtowc' [-Wmissing-prototypes]
void lg_mbrtowc() {}

3. ERROR: Undefined symbol "_analyze_thin_linkage" referenced from link-grammar.def

4. WARNING: ../../bindings/perl/lg_perl_wrap.cc:529:7: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]

5. ERROR: /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/CORE/pad.h:236:17: error: invalid suffix on literal; C++11 requires a space between literal and
      identifier [-Wreserved-user-defined-literal]
              "Pad 0x%"UVxf"[0x%"UVxf"] set_cur    depth=%d\n"
NOTE: the perl binding compilation doesn't fail on version 5.2.1 using the same compilation environment.

The compiler version is the one that comes with the latest xcode, 
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)

**Comment by linas** [comment]
OK, thanks. I've pushed fixes for 1. 2. and 3.

item 4. is actually a swig bug: that file is auto-generated by swig.  I could hand-edit it, but my changes would be lost when it gets regenerated.

item 5. is clearly a perl bug. You are saying it no longer happens for 5.2.1?  Or that it didn't happen for 5.2.0 but started happening in 5.2.1 ?  I think  I started explicitly requiring stdc++11 in 5.2.1 and that could change behavior.  Maybe I shouldn't force c++11 if perl isn't happy with it?

I'll put out a version 5.2.2 maybe tomorrow w/these fixes.

Perhaps I asked before: what are you doing/hoping to do with link-grammar?

**Comment by linas** [comment]
OK,  So I'm being very stupid ... I just pushed version 5.2.2 and realized that I can test clang-3.5 myself.  Yes, I see the error: I think setting the flags to -std=c++03 would probably fix this...

**Comment by linas** [comment]
Fully tested with clang in version 5.2.3. 

I set -std=c++03 instead of -std=c++11 to work around the perl build problem.

**Comment by agayardo** [comment]
Yes, it works, thanks!
