### ISSUE TITLE
Ctrl-C messes up terminal settings

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#522]
Ctrl-D exits terminal fine, but Ctrl-C doesn't. It requires to run ```reset; stty erase ^?``` to bring it back to the original state.

If possible, Ctrl-C should preserve the terminal state.

**Comment by linas** [comment]
would you be able to provide a patch for this?  

This is not an issue for Linux; I suspect the bug is elsewhere, possibly in libeditline.  A generic fix for libeditline would benefit all users, and not just link-grammar.

**Comment by yurivict** [comment]
I am on FreeBSD. It uses libedit-3.1.20150325_2,1 from http://thrysoee.dk/editline/
Does linux use different version?

**Comment by ampli** [comment]
It seems the problem was hidden on Linux.
I just sent PR #523 that hopefully fixes it on FreeBSD too.
See the commit message (251ad0b) for details.
Please verify that it fixes the problem for you too.

BTW, on Fedora (25): libedit-3.1-16.20160618cvs

**Comment by yurivict** [comment]
@ampli The patch fixed the problem. Thanks!

**Comment by ampli** [comment]
@yurivict Thanks for verifying it.
Please note that I have just resent the PR with a modified commit message (a modified command to demonstrate the problem), so if you latter pull this repo again, you need to use something like

`git pull -f`

(You need to be careful with it (-f) if you have other local commits.)

**Comment by ampli** [comment]
Fixed.
