### ISSUE TITLE
Link-grammar 5.2.1 fails to load dictionary (Windows)

### ISSUE THREAD

**Issue by steavy29** [opencog/link-grammar#53]
Hello there.
I`m trying to launch link-grammar 5.2.1 on my Windows machine.
And it fails to load the dictionary file 4.0.dict.
Here are the error details:

Call stack:
>	link-grammar-x86.dll!read_dictionary(Dictionary_s * dict) Line 1773
 	link-grammar-x86.dll!dictionary_six_str(const char * lang, const char * input, const char * dict_name, const char * pp_name, const char * cons_name, const char * affix_name, const char * regex_name) Line 504
 	link-grammar-x86.dll!dictionary_six(const char * lang, const char * dict_name, const char * pp_name, const char * cons_name, const char * affix_name, const char * regex_name) Line 596
 	link-grammar-x86.dll!dictionary_create_from_file(const char * lang) Line 622	C
 	link-grammar-x86.dll!dictionary_create_lang(const char * lang) Line 78

To load the dictionary it reads the file line by line and on line 2982 it crashes like this:

![capture](https://cloud.githubusercontent.com/assets/9865713/5612633/eacc5164-94e0-11e4-86a4-37cc38ff67f4.PNG)

Here is the problematic line itself:

    2982:  gells.v O.K.'s.v OK's.v O.K.’s OK’s:

Though if I rewrite it like this:

    2982:  gells.v O.K.'s.v OK's.v O.K.’s.v OK’s:

it works perfectly. (I added '.v' pos to O.K.’s)
I assume it parses this '.’s' as a pos and fails on it. (is this a correct pos at all?)

Can this be fixed somehow?
Thanks is advance.

Update:
The problem appears to be in this function:

    void patch_subscript(char * s)
    {
        char *ds, *de;
        ds = strrchr(s, SUBSCRIPT_DOT);
        if (!ds) return;

        /* a dot at the end or a dot followed by a number is NOT
         * considered a subscript */
        de = ds + 1;
        if (*de == '\0') return;

        if (isdigit((int)*de)) return;
        *ds = SUBSCRIPT_MARK;
    }

in dict-common.c.
On that line function is being called with parameter O.K.â€™s
â€™ stands for apostrophe `

After taking the subscript part we get
    de = "â€™s"
and ((int)*de) which is passed to isdigit function results into -30.
So the inner assertion in it fails. Basicall that is how we get the error.

What about adding our own check like this to have the trouble fixed:

    // man isdigit: The value of the argument must be representable as an unsigned char or the value of EOF.
    int chr = *de;
    if (chr >= -1 && chr <= 255 && isdigit(chr)) return;
?

**Comment by linas** [comment]
Hi Steavy,

The README talks about this ... You need to configure your windows machine to support unicode. The dictionaries all contain unicode characters, and your crash is typical of what happens in this situation.

**Comment by linas** [comment]
OK, so I re-read what you wrote, and realize I misunderstood the original bug report.

I just pushed a fix for this.  The correct fix was to fix OK to be OK.v  -- its an interesting bug.
