### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by liliburnett** [opencog/link-grammar#532]
From ./autogen.sh:

../configure: line 17259: syntax error near unexpected token `,:'
../configure: line 17259: `			AX_TLS(,:)'

from autogen.err
`configure.ac:327: error: possibly undefined macro: AC_MSG_NOTICE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
`

I have pkg-config, this is Arch Linux.

**Comment by ampli** [comment]
It looks like you need to install `autoconf-archive`.

**Comment by linas** [comment]
assuming that installing autconf-archive fixed this.

But really, you should NOT work out of git, you should use the released versions; only those ar guaranteeed to be bug free, and actually work. The stuff in git might not compile.
