### ISSUE TITLE
Thrift support

### ISSUE THREAD

**Issue by mosyp** [opencog/link-grammar#533]
I'm going to use your parser for one of my pet project and I found it kinda difficult to integrate your solution into JVM world (Scala/Java). Yes, there's some JNI binding however to make them work as you want is unknown for me. (I cannot still find a workaround to `Native Library /usr/local/lib/liblink-grammar-java.so.5.3.15 already loaded in another classloader`)
Anyways, there's a framework [Apache Thrift ](https://thrift.apache.org/) which provides good interface for cross-language development. Also it provides code gen of thrift file (definitions/struct/services) for popular languages.

Personally I have a great experience of using it with Scala server app and C client communicating with each other.
Hence, it would be awesome to integrate such here. As benefit you should not provide bindings to each language but the single thrift file, where eventually any developer can use it as he wants to

**Comment by linas** [comment]
Hi sorry for the very very late reply; I broke my leg and haven't been reading email.

I use the LG java libraries every day, they just-plain work for me, so I have no clue about that error; I've never seen it.  Those jni bindings were written 9 years ago by Borislav Iordanov; they're not shining gems, but they work, they're stable and fully debugged.

I know nothing at all about Thrift. It sounds like SWIG, but different. or libffi, but different; there's gotta be a dozen ways of doing these things.  If you send patches or provide alternate bindings for thrift., or Scala, or whatever, I'll accept those as pull requests. Don't sent me any patches that alter the current Java bindings, unless its something trite.

**Comment by linas** [comment]
closing, stale
