### ISSUE TITLE
The recent fixes cause compilation errors

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#548]
Hi @linas,
There are now some compilation errors - the main ones are in wordgraph.c, which still uses String.
Maybe your fixed wordgraph.c has not been committed?

In any case, I fixed some other problems and would like to send pull requests for them (but I don't want to cause conflicts if you still have uncommitted stuff).

I have also already made most of the needed fixes for Windows (including for pp_lexer.l), which I would like to send after that.

**Comment by linas** [comment]
Hmm. 8 days ago, I was in the middle of a major restructuring. I'm done now, probably for a good long while, at least a few weeks.  Its a good time for fixes.

My commit style is that I commit every 5 minutes, soon as some tiny chunk works.  I usually push at the end of the day, just so I can start with a clean plate the next day ...

**Comment by linas** [comment]
Oh, I think I see. One moment.

**Comment by linas** [comment]
Ah, sees I don'd compile with WORDGRAPH_DISPLAY set, so did not spot this. If you could fix this it would be great.

**Comment by ampli** [comment]
Fixed by #551.
