### ISSUE TITLE
./configure shows that my compiler isn't working

### ISSUE THREAD

**Issue by chris-hawley** [opencog/link-grammar#552]
So...my compiler does work because it can compile programs. I'm not sure which checks it failed on exactly but i do know that the log shows some...disturbing output. Below is what it told me was the problem. 

```
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "link-grammar"
| #define PACKAGE_TARNAME "link-grammar"
| #define PACKAGE_VERSION "5.3.10"
| #define PACKAGE_STRING "link-grammar 5.3.10"
| #define PACKAGE_BUGREPORT "link-grammar@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "link-grammar"
| #define VERSION "5.3.10"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3835: error: in `/home/chris/vbox/link-grammar':
configure:3837: error: C compiler cannot create executables
```
This output was from the latest release.

**Comment by linas** [comment]
That's the "normal" output when configure is unable to compile.  My best guess is that maybe you have the compiler installed in an unusual place, or given an unusual name? 

All that configure is doing is trying to compile the above program, using cc or gcc .. whichever cc or gcc can be found in the search path.  Typical reasons are: the compiler can't be found; the current directory is not writeable, the assembler can't be found, the c library won't link.  You can diagnose this by creating a file with just that simple main in it, and then running just cc on it: were there errors?  Better yet: add a printf("hello world\n"); to it, compile it, and see if you can run it.

Also BTW, the latest release is 5.3.16 not 5.3.10

**Comment by chris-hawley** [comment]
I was referring to the mis-formatted program causing a compile issue

**Comment by linas** [comment]
sorry, what's misformatted about it?

**Comment by chris-hawley** [comment]
```
int
main

```
instead of 

`int main`

i'm not actually sure if that causes this error but I have seen it work before.

**Comment by linas** [comment]
Ahh, all that is perfectly valid C code.   You can write this:
```
int
main
(
)
{ ;;;;;;;;;;;;;;;;;;;;
{}{}{}{}  ;;;;;;   return 0;;;;;;;;
;
;
;
}
```
and it will compile just fine; its 100% legal code, with very well-defined (trivial) behavior.  Anyway, to debug your problem copy the above into a file `x.c`   and then say `cc x.c`  and see what happens.

**Comment by chris-hawley** [comment]
it worked without any errors.

**Comment by linas** [comment]
strange.  Somewhere in `config.log`, towards the end, should be the command that was actually run.  I think it will be printed right before the  part you cut-n-pasted up top.   Try running that command by hand.

**Comment by chris-hawley** [comment]
I think I know where the problem is, I'm not sure how cogutils got compiled with this issue but cmake found an incorrect path for my C compiler...exporting the correct one worked.

**Comment by linas** [comment]
!! cmake and cogutils have nothing to do with link-grammar, so I am surprised.

**Comment by chris-hawley** [comment]
doesn't configure use cmake? the output looks the same.

**Comment by linas** [comment]
configure does not use cmake.   The two are actually two different competing systems that do similar things.
 
It's also highly unusual to export explicit paths to compilers.  That's really intended for wizards doing strange things. Soon as you start exporting paths to over-ride defaults, you are inviting difficult-to-debug situations to occur.  Sticking to defaults is always best, unless there's some important need to do otherwise, and then you risk exactly this kind of trouble.
