### ISSUE TITLE
The recent 5 PRs (554 to 558) 

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#559]
Two of the PRs (#556 and #558) depend on each other, and their application causes a conflict.
I closed them to prevent a confusion.
The remaining 3 can be applied with no conflicts.

I will regenerate the closed PRs (one by one, to prevent conflicts again) after the existing 3 ones are applied. 

BTW, I have many additional fixes pending, but they are based on previous versions of the library.
In order to be sure the PRs for them can be cleanly applied, I will  wait until all the said PRs (including the ones that I need to regenerate due to the said conflicts) are applied.

**Comment by linas** [comment]
OK merged.  Sounds reasonable.  I need help w/ splitting see other bug report

**Comment by ampli** [comment]
I combined the closed #556 and #558 into a new PR #561.
