### ISSUE TITLE
Java test failure

### ISSUE THREAD

**Issue by jbicha** [opencog/link-grammar#563]
Debian and Ubuntu runs link-grammar's test suite using the autopkgtest framework. Now that Debian 9 is released, I updated link-grammar in Debian and Ubuntu from 5.3.14 to 5.3.16. It looks like a new Java test was added but it isn't working.

```
unit-tests           FAIL stderr: In file included from multi-java.cc:23:0:
autopkgtest [10:13:44]: test unit-tests:  - - - - - - - - - - stderr - - - - - - - - - -
In file included from multi-java.cc:23:0:
../bindings/java-jni/jni-client.h:2:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
```

[Full test log](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-artful/artful/ppc64el/l/link-grammar/20170620_101357_635bc@/log.gz)

Debian and Ubuntu use OpenJDK 8 so I think the file it's looking for is at `/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h`

**Comment by jbicha** [comment]
This was a packaging error. I didn't have autopkgtest install the OpenJDK development files

**Comment by linas** [comment]
thanks Jeremy
