### ISSUE TITLE
symbols were dropped in 5.4.0 but soname wasn't bumped

### ISSUE THREAD

**Issue by jbicha** [opencog/link-grammar#572]
Hi, some symbols were removed in the 5.4.0 release but the soname wasn't bumped.

In other words, this sounds like 4a and 4b in the first few lines of configure.ac need to be followed.

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
```
diff --git a/debian/liblink-grammar5.symbols b/debian/liblink-grammar5.symbols
index a5beb8a..a8a555a 100644
--- a/debian/liblink-grammar5.symbols
+++ b/debian/liblink-grammar5.symbols
@@ -16,9 +16,9 @@ liblink-grammar.so.5 liblink-grammar5 #MINVER#
  eliminate_duplicate_disjuncts@Base 4.6.5
  free_disjuncts@Base 4.6.5
  free_lookup_list@Base 5.3.7
- left_print_string@Base 5.3.7
  lg_compute_disjunct_strings@Base 4.6.5
  lg_error_clearall@Base 5.3.14
+ lg_error_flush@Base 5.4.0
  lg_error_formatmsg@Base 5.3.14
  lg_error_printall@Base 5.3.14
  lg_error_set_handler@Base 5.3.14
@@ -50,9 +50,12 @@ liblink-grammar.so.5 liblink-grammar5 #MINVER#
  linkage_get_num_words@Base 4.2.2
  linkage_get_violation_name@Base 4.2.2
  linkage_get_word@Base 4.2.2
+ linkage_get_word_byte_end@Base 5.4.0-1
+ linkage_get_word_byte_start@Base 5.4.0-1
+ linkage_get_word_char_end@Base 5.4.0-1
+ linkage_get_word_char_start@Base 5.4.0-1
  linkage_get_words@Base 4.2.2
  linkage_link_cost@Base 4.2.2
- linkage_post_process@Base 4.2.2
  linkage_print_constituent_tree@Base 4.2.2
  linkage_print_diagram@Base 4.2.2
  linkage_print_disjuncts@Base 4.6.5
@@ -112,8 +115,6 @@ liblink-grammar.so.5 liblink-grammar5 #MINVER#
  parse_options_set_use_viterbi@Base 5.3.7
  parse_options_set_verbosity@Base 4.2.2
  parse_options_timer_expired@Base 4.2.2
- post_process_close@Base 4.2.2
- post_process_open@Base 4.2.2
  print_dictionary_data@Base 5.3.7
  print_one_disjunct@Base 4.6.5
  prt_error@Base 4.3.9
@@ -130,3 +131,4 @@ liblink-grammar.so.5 liblink-grammar5 #MINVER#
  sentence_num_violations@Base 4.2.2
  sentence_parse@Base 4.2.2
  sentence_split@Base 4.6.5
+ utf8_strwidth@Base 5.4.0
```

**Comment by linas** [comment]
Yeah. Have gotten sloppy with this, mostly because no one ever complained before. :-)

**Comment by jbicha** [comment]
Debian packaging has a way to easily detect when this happens.

**Comment by dbl001** [comment]
Also getting these errors building opencog with link-grammar:
```
/home/ubuntu/opencog/opencog/nlp/lg-parse/LGParseLink.cc: In member function ‘virtual opencog::Handle opencog::LGParseLink::execute(opencog::AtomSpace*) const’:
/home/ubuntu/opencog/opencog/nlp/lg-parse/LGParseLink.cc:230:17: error: ‘lg_error_flush’ was not declared in this scope
  lg_error_flush();
                 ^
/home/ubuntu/opencog/opencog/nlp/lg-parse/LGParseLink.cc: In member function ‘opencog::Handle opencog::LGParseLink::cvt_linkage(Linkage, int, const char*, const char*, bool, opencog::AtomSpace*) const’:
/home/ubuntu/opencog/opencog/nlp/lg-parse/LGParseLink.cc:250:49: error: ‘linkage_get_word_byte_start’ was not declared in this scope
   size_t sb = linkage_get_word_byte_start(lkg, w);
                                                 ^
/home/ubuntu/opencog/opencog/nlp/lg-parse/LGParseLink.cc:251:47: error: ‘linkage_get_word_byte_end’ was not declared in this scope
   size_t eb = linkage_get_word_byte_end(lkg, w);
                                               ^
make[2]: *** [opencog/nlp/lg-parse/CMakeFiles/lg-parse.dir/LGParseLink.cc.o] Error 1
make[1]: *** [opencog/nlp/lg-parse/CMakeFiles/lg-parse.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by linas** [comment]
Hi @dbl001 I believe those errors will go away if you download and install link-grammar version 5.4.0.  The cmake script should have checked for this, Its not clear to me why it did not do so automatically.

**Comment by linas** [comment]
Hi @jbicha Looking at the symbols that were dropped: none of those symbols were in the public API, and there should have been exactly zero users of them.  Adding and removing non-public functions presumably does not require adherence to the soname conventions.

For this reason, I am closing this; we add and remove non-public functions all the time, the so major version would be up to several hundred if we bumped each time.

**Comment by jbicha** [comment]
@linas Could you look into hiding or not exporting those private symbols?

**Comment by linas** [comment]
Yes, I tried to do that, but we now have two libraries that inter-operate: one is the SAT solver, which we build as a dynamic library, with the idea that people who don't use the SAT solver would not link to it.  However, it needs some of the private symbols.  Perhaps packaging it as a separate library was a bad idea... 

There are other vague ideas for modularizing more subsystems; these maybe might go into their own libraries, and thus might need various private symbols....

**Comment by dbl001** [comment]
I’m still seeing this error in link-grammar pulled from github: 

...
../configure: line 16829: syntax error near unexpected token `,:'
../configure: line 16829: `			AX_TLS(,:)’

**Comment by linas** [comment]
Hi @dbl001 this bug report is for a different issue than the two issues you've commented. Please stay on topic, or create new issues, as needed.

For your current issue, the general advice is: do NOT build from github; use the 5.4.0 tarball instead.  Github is intended for developers who have all of the prerequisite development tools installed, it is not intended for link-grammar users.

**Comment by ampli** [comment]
> Yes, I tried to do that, but we now have two libraries that inter-operate: one is the SAT solver, which we build as a dynamic library, with the idea that people who don't use the SAT solver would not link to it. However, it needs some of the private symbols. Perhaps packaging it as a separate library was a bad idea...

Please recall that we have already made the SAT solver a static library.
However, some private symbols, like `lg_expand_disjunct_list` and `object_open` are exported for the optional corpus, cluster and viterbi dynamic libraries, which are not a part of the distribution.

The solution is to make these exporting conditional, which seems easy to implement.
In fact, `link-grammar.def` can be entirely eliminated if desired - see [How to use the new C++ visibility support](https://gcc.gnu.org/wiki/Visibility#How_to_use_the_new_C.2B-.2B-_visibility_support).
I can do that.

**Comment by linas** [comment]
The `link-grammar.def` file is not needed for linux, but it is needed for MacOS (or used to be, or something ... whenever we changed something and forgot to put it in that file, the MacOS people would write unhappy emails.)  So, yes, we can remove it, but only if MacOS doesn't get broken.

**Comment by ampli** [comment]
I think MacOS now supports the __attribute__ way.
I can of course test it. If it supports, I will send a PR.
