### ISSUE TITLE
MAX_LINE is too low

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#582]
In a recent commit  0af2d1d281f521074f0939233e273e3e9cad9f16  (from May 18), MAX_LINE got changed from 2500 to 500. As a result, English sentences with more than ~60 words cannot be displayed any more. With Russian this happens with much less words.

I reviewed the sources and it seems it is easy to dynamically allocate MAX_LINE as needed.
I will send a PR for that.

**Comment by linas** [comment]
It was this commit ... https://github.com/opencog/link-grammar/commit/23e567a3ce94cbfc61c562f67465479303d18fe1

yes, OK, make it dynamic

**Comment by ampli** [comment]
Just now I sent PR #584, that removes both MAX_LINE and MAX_HEIGHT.
