### ISSUE TITLE
A sole Wall Wd is not suppressed now

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#600]
Now that this link type has h/d, the following definition never matches:
`#define LEFT_WALL_SUPPRESS ("Wd")`

As a result, the tests don't pass.

Should it just be changed to "hWd"?

BTW, it may be a good idea to move this definition to the dict, since it is dict-dependent.

**Comment by linas** [comment]
Dohhh. Or I could revert the change. On the one hand, it is very tempting to annotate everything with head-dependent markers, on the other hand, it does change the nature of the game. I'm very ambivalent about it.

Yes, this definition should be in the dict.

**Comment by ampli** [comment]
I will put it in the dict in the "connector enumeration" version that is almost finished.

Should the wall-suppress connector(s) match by string match like now, or is it better to use easy_match for that?

**Comment by linas** [comment]
Ah. Yes, if "h" is to be handled correctly, then it should be `easy_match`

**Comment by ampli** [comment]
Fixed.
