### ISSUE TITLE
New problem in en/corpus-basic.batch

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#612]
The following sentences recently started to get full linkages:
*A man I know's family is renovating their kitchen
*I am as intelligent as John does
*Nobody, John seems, wants to be a liberal
*There are a dog and a cat here
*There are a dog or a cat here
*There are neither a dog nor a cat here

**Comment by linas** [comment]
These were probably added  in merge req #608

**Comment by ampli** [comment]
These differences remain:
*A man I know's family is renovating their kitchen
*I am as intelligent as John does

**Comment by ampli** [comment]
The differences as of 0a21d965050f0854eebdb3a399f59aa4c4f6f310:
*A man I know's family is renovating their kitchen
*other five costumes got prizes

**Comment by linas** [comment]
"other five customers" parses because of changes to allow "the five seat" parse, e.g. "the five seat washed out".  This can be tightened by disallowing "other" as a determiner with numbers.

**Comment by ampli** [comment]
Just for dict debug convenience (because it is very easy for me to generate that - by a script), the current differences are:
*A man I know's family is renovating their kitchen
*He told me that even, his mother likes me
*The attempting to go to the party angered Joe
*other five costumes got prizes

(A previously fixed one returned, and a new one appeard.)

**Comment by linas** [comment]
*other five costumes got prizes

got broken, in order to allow "the five seat keeps washing out" which is technical jargon.  Hmm. "the five seat" is singular, "other five costumes" is plural; I guess that could be the distinguishing factor...

**Comment by ampli** [comment]
It seems this is now the only "new" problem:
*other five costumes got prizes
(The others from the previous list were probably fine even then.)

**Comment by ampli** [comment]
This seems to me unimportant so I'm closing this issue to reduce open issue clutter.
