### ISSUE TITLE
unrecognized options

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/link-grammar#629]
When runs with `` flags, the `./configure` script issues a warning:
> configure: WARNING: unrecognized options: --enable-widec, --enable-pthreads

**Comment by linas** [comment]
Two issues:  the README is wrong, there is no enable-pthreads any more. I will fix it.

For the other one, you mis-read the README.  you only say `./configure --enable-widec` when building editline, not link-grammar.

**Comment by linas** [comment]
I just fixed the README, just now. It will appear in the next version.
