### ISSUE TITLE
./configure error

### ISSUE THREAD

**Issue by sushantPythonCactus** [opencog/link-grammar#630]
hi, m using ubuntu 16.04, sudo apt-get install libtool for autogen to work, which worked sucessfully.
Then this, 
./configure --enable-debug
 and I get this error, attached.
[linkGrammarError.txt](https://github.com/opencog/link-grammar/files/1606175/linkGrammarError.txt)

Could you look this out and help me fixing this. The last two lines of error.

**Comment by linas** [comment]
instead of building from github, you should download and build the tarball instead.  The tarball can be obtained at https://www.abisource.com/downloads/link-grammar/current/
