### ISSUE TITLE
Urgent help required import error : no module linkgrammar

### ISSUE THREAD

**Issue by madihayousaf** [opencog/link-grammar#638]
I am working with link grammar and python3. I am new to both of them . On terminal my link grammar is working fine i am attaching a picture of my code with output 
![screenshot from 2018-01-19 16-04-49](https://user-images.githubusercontent.com/28005875/35156989-da42b4e2-fd32-11e7-9dd9-3e729c1f8880.png)

Now I have installed geany on my system as an interface and is running the same code on it but it gives me import error . I need urgent help to solve this issue . Attached is the screen shot 
![screenshot from 2018-01-19 16-03-18](https://user-images.githubusercontent.com/28005875/35157038-0b74b484-fd33-11e7-9d47-93cc8a23cd3a.png)

**Comment by linas** [comment]
Please read about PYTHONPATH ... it is used to specify the location of python modules. Obviously, geany failed to set the PYTHONPATH correctly.  This is a bug in geany, not in link-grammar.

You should spend some time learning how to use python, and how it works.
