### ISSUE TITLE
target 'install-strip' doesn't strip lib/liblink-grammar.so.5.4.3

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#645]
Normally, stripping is expected for gnutools-based projects.

**Comment by linas** [comment]
Is there a suggested fix?  I've never heard of this before...

**Comment by yurivict** [comment]
GNU docs says that this is the default behavior:
> Users that need stripped binaries may invoke the install-strip target to do that.[1]

Not sure what the right fix would be, but something prevents this default behavior.

[1] https://www.gnu.org/prep/standards/html_node/Standard-Targets.html

**Comment by yurivict** [comment]
```
Making install in link-grammar
gmake[5]: Entering directory '/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3/link-grammar'
gmake[6]: Entering directory '/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3/link-grammar'
gmake[7]: Entering directory '/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3/link-grammar'
 /usr/local/bin/gmkdir -p '/usr/ports/textproc/link-grammar/work/stage/usr/local/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c -s  liblink-grammar.la '/usr/ports/textproc/link-grammar/work/stage/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/liblink-grammar.so.5.4.3 /usr/ports/textproc/link-grammar/work/stage/usr/local/lib/liblink-grammar.so.5.4.3
libtool: install: (cd /usr/ports/textproc/link-grammar/work/stage/usr/local/lib && { ln -s -f liblink-grammar.so.5.4.3 liblink-grammar.so.5 || { rm -f liblink-grammar.so.5 && ln -s liblink-grammar.so.5.4.3 liblink-grammar.so.5; }; })
libtool: install: (cd /usr/ports/textproc/link-grammar/work/stage/usr/local/lib && { ln -s -f liblink-grammar.so.5.4.3 liblink-grammar.so || { rm -f liblink-grammar.so && ln -s liblink-grammar.so.5.4.3 liblink-grammar.so; }; })
libtool: install: /usr/bin/install -c .libs/liblink-grammar.lai /usr/ports/textproc/link-grammar/work/stage/usr/local/lib/liblink-grammar.la
libtool: install: /usr/bin/install -c .libs/liblink-grammar.a /usr/ports/textproc/link-grammar/work/stage/usr/local/lib/liblink-grammar.a
libtool: install: chmod 644 /usr/ports/textproc/link-grammar/work/stage/usr/local/lib/liblink-grammar.a
libtool: install: ranlib /usr/ports/textproc/link-grammar/work/stage/usr/local/lib/liblink-grammar.a
libtool: warning: remember to run 'libtool --finish /usr/local/lib'
 /usr/local/bin/gmkdir -p '/usr/ports/textproc/link-grammar/work/stage/usr/local/include/link-grammar'
 /usr/bin/install -c -m 644 link-features.h link-includes.h dict-common/dict-api.h dict-common/dict-structures.h '/usr/ports/textproc/link-grammar/work/stage/usr/local/include/link-grammar'
```

**Comment by ampli** [comment]
Can it be it is actually a problem with the `automake` version on your system?
The `-s` flag is given in the install of` liblink-grammar.la` (in which it doesn't matter).
However, no `-s` is given in the dynamic lib install, and also no strip command is issued after it.

I use automake 1.15. Which version do you use?

**Comment by yurivict** [comment]
I have automake-1.15.1, which is the latest.

**Comment by yurivict** [comment]
A lot of ports on FreeBSD use ```install-strip```, and it does work. I just verified that ```expat-2.2.5``` gets stripped with ```install-strip``` and doesn't without it.

**Comment by ampli** [comment]
To find an example that works fine may be a step toward finding the reason of the problem here.
Could you please post the same `make` output for `expat`, so we can see how the stripping is done in that case?

**Comment by yurivict** [comment]
I will ask on the automake ML first. IMO, they will likely know the answer right away. If this fails, will post the expat output here.

**Comment by linas** [comment]
What's the status on this?

**Comment by linas** [comment]
Is this resolved, or still an issue?

**Comment by linas** [comment]
Closing; additional data needed to proceed with any fix.
