### ISSUE TITLE
--enable-regex-tokenizer causes the error: fatal error: 'dict-api.h' file not found #include "dict-api.h"

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#646]
```
tokenize/regex-tokenizer.c:25:10: fatal error: 'dict-api.h' file not found
#include "dict-api.h"
         ^~~~~~~~~~~~
tokenize/regex-tokenizer.c:29:10: fatal error: 'structures.h' file not found
#include "structures.h"
         ^~~~~~~~~~~~~~
```

```"structures.h"``` is missing completely.

**Comment by ampli** [comment]
The regex-tokenizer is a tokenizing demo (tokenize sentences by regex definitions entered at the command line) that is now not integrated in the `link-parser` code.  (It may be eventually be removed or enhanced.)
So there is no reason to configure it (unless you are interested in developing it further).

**Comment by yurivict** [comment]
configure.ac should explain that this is a demo then.
Currently, I have no way of knowing this by reading the description.

**Comment by yurivict** [comment]
And it shouldn't be broken, even if it is merely a demo.

**Comment by linas** [comment]
I marked it as "experimental".  I'm not clear on why you'd want to mess with the default config, anyway.

**Comment by yurivict** [comment]
> I'm not clear on why you'd want to mess with the default config, anyway.

Because I am updating the FreeBSD port. As per policy, all configure options should be exported as port options. To do this, I need to try each of them. This is why I "mess" with the default config.

**Comment by linas** [comment]
OK... so why does it matter that it should build and/or work?  The fact that it doesn't build is an excellent reason to think that it .. won't work.  Or are you trying to automate unit testing, or something?  I don't understand the use-case.

**Comment by yurivict** [comment]
> The fact that it doesn't build is an excellent reason to think that it .. won't work.

Very often, build breaks because of some other reasons. For example, some compiler incompatibilities, header incompatibilities, etc.

**Comment by linas** [comment]
OK I just pushed a commit that enables this to compile.  It will be in the next version
