### ISSUE TITLE
--enable-sat-solver=yes breaks it: all includes should be #include <minisat/core/Solver.h>

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#648]
This line and similar should change:
```
link-grammar/sat-solver/guiding.hpp:#include <core/Solver.h>
```

**Comment by linas** [comment]
?? Sat solver is already enabled by default, and has been for years. 

I don't understand how you are getting this error: the config file tries to auto-tdetect a system minsat and use that, if available, else it uses the bundled minisat. ... both work for me.

**Comment by yurivict** [comment]
I think, ```=yes``` caused this.

**Comment by yurivict** [comment]
```minisat``` doesn't install ```.pc``` files. So, user projects should include them with the full path.
And ```minisat``` installs headers into its own subdirectory:
```
	/usr/local/include/minisat/core/Dimacs.h
	/usr/local/include/minisat/core/Solver.h
	/usr/local/include/minisat/core/SolverTypes.h
	/usr/local/include/minisat/mtl/Alg.h
...
```

**Comment by linas** [comment]
I still don't understand. All that will happen is that the system minisat files won't be found, and the bundled ones will be used instead.

**Comment by yurivict** [comment]
There is a clear improper use in ```guiding.hpp```.
Not sure why bundled ones aren't used.

**Comment by linas** [comment]
What do you mean when you say "clear improper use" ? It seems clearly correct to me, and it builds on linux, windows, mac, and has been building on all three for (many many) years.  I can't figure out what you are doing to trigger this error.

**Comment by yurivict** [comment]
It can't find ```/usr/local/include/minisat/core/Solver.h``` because you should either supply ```-I/usr/local/include/minisat``` or always do ```#include <minisat/core/Solver.h>```. The latter should be preferred.

And the project includes it differently in different cases:
```
# grep -r "Solver.h" *
configure.ac:			[#include <minisat/core/Solver.h>]
sat-solver/guiding.hpp:#include <core/Solver.h>
...
```

> it builds on linux, windows, mac, and has been building on all three for (many many) years

Doesn't matter.
It doesn't build on FreeBSD, and the reason is a very obvious a bug.

**Comment by ampli** [comment]
I don't have a revent FreeBSD handy, so I have to ask you:
If you make this change (i.e. use #include <minisat/core/Solver.h>), does it then work as desired?
If so I will make this patch and test it on other systems too.

**Comment by yurivict** [comment]
> If you make this change (i.e. use #include <minisat/core/Solver.h>), does it then work as desired?

Yes.

**Comment by ampli** [comment]
I sent a PR (#654) to fix that.

**Comment by ampli** [comment]
I guess this can be closed now.
