### ISSUE TITLE
Requires automake after configure is done

### ISSUE THREAD

**Issue by yurivict** [opencog/link-grammar#649]
Once the supplied ```configure``` has been run, there should be no need for ```automake```.
All ```Makefile.in``` files should be present along with ```configure```.

Error:
```
        Swig interfaces generator:      no
        Perl interfaces:                no
        Perl install location:          
        Python2 interfaces:             no
        Python3 interfaces:             no
        ASpell spell checker:           no
        HunSpell spell checker:         yes
        HunSpell dictionary location:   /usr/share/myspell/dicts
        Boolean SAT parser:             no
        SQLite-backed dictionary:       yes
        Viterbi algorithm parser:       no
        Corpus statistics database:     no
        RegEx tokenizer:                no

===========================================================================
=======================<phase: build          >============================
===>  Building for link-grammar-5.4.3
gmake[1]: Entering directory '/wrkdirs/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3'
 cd . && /bin/sh /wrkdirs/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3/missing automake-1.15 --foreign Makefile
/wrkdirs/usr/ports/textproc/link-grammar/work/link-grammar-5.4.3/missing: automake-1.15: not found
WARNING: 'automake-1.15' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
```

**Comment by linas** [comment]
???  the tarballs come with the Makefile.in and the configure.  How can you possibly obtain a configure without a Makefile.in?

Please note: all code in git is experimental; its for developers only.  Non-developer use of the code in github is not supported.

Users should use the tarballs, and only the tarballs.

**Comment by yurivict** [comment]
> How can you possibly obtain a configure without a Makefile.in?

They might be there, not sure. But the build fails with the above error, which it obviously shouldn't.

**Comment by linas** [comment]
How did you build it? from what sources? Where's you find the configure file?

**Comment by yurivict** [comment]
Tarball is taken from ```http://www.abisource.com/downloads/${PORTNAME}/${PORTVERSION}/```

**Comment by linas** [comment]
Why are you running `missing automake-1.15 --foreign Makefile` ? Don't do that and it won't fail.

**Comment by yurivict** [comment]
automake shouldn't be needed after configure is done.

**Comment by ampli** [comment]
After a recent upgrade from fedora 25 to fedora 27, I also started to get these exact `automake-1.15` errors from time to time. In that cases I used `autogen.sh` to regenerate `configure`. The next time it happens I will investigate its cause and will try to find a fix.

**Comment by yurivict** [comment]
@ampli When ```configure``` is used, automake shouldn't be used. When ```autogen.sh``` is used, ```automake``` should be needed. These might be two different problems.

I had to leave ```USE=autoreconf``` in the FreeBSD port, because it fails without it due to this problem.

**Comment by ampli** [comment]
The said problem of `automake-1.15` happens to me (from time to time) when I invoke `configure` to test another configuration (most of the times to add or remove `--enable-debug`). In that case when I use `autogen.sh`, running the new `configure` doesn't cause this problem again. I suspect something not up to date in the `m4 directory causes that, but as I said, I will be able to check that only when it happens again (unless somebody points out the problem before that).

**Comment by ampli** [comment]
> missing: automake-1.15: not found WARNING: 'automake-1.15' is missing on your system.

I think we need to apply the fix outlined here (+ the first comment):
[User of autotools-generated tarball gets error message: aclocal-1.13: command not found](https://stackoverflow.com/a/30386141/6485214).

**Comment by bapt** [comment]
to prevent the problem the downstream consumers have to run the configure script with --disable-maintainer-mode. (it can be made default  with adding  AM_MAINTAINER_MODE([disable]) to configure.ac).

**Comment by linas** [comment]
Wow! Thank you @bapt ! Sorry I did not notice your suggestion earlier. Pull req #1137 should fix this.
