### ISSUE TITLE
Merging strategy for the wordgraph code

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#66]
Hi Linas,
I have just rebased my **wordgraph** branch on the current **opencog/master**.
It **replaces** my previous branch with the same name, that once got a trashed commit history, and because nobody was supposed to use anything from it up to now, I did the unusual thing of overwriting it on github.

If you once have fetched it, I guess that fetching it again now may cause a mess (because it is a different branch with the same name), so you may need to first delete the remote tracking **wordgraph** branch if you have one.

Alternatively I can rename it to some other name, like wordgraph2.
In any case, the pull request from this branch can now be cleanly merged.
Just tell me if to leave the branch name as is (**wordgraph**) or rename it and I will then send you this pull request.

I also have some new fixes for 5.2.5 (that are not applied yet to the wordgraph branch). One is the Windows project file fix (the I discribed in may last post to the group).
Another one is the dictopen fix (that I still need to test on Windows, now that I succeeded to compile LG on it).
The other two are not tested yet. One fixes a potential memory corruption problem on sent->lang.
The other fixes potential incorrect language setup on Windows.

I mention this because I wonder in which order we should continue: should I first send you these relatively small fixes (but then I'm not totally sure that the **wordgraph** pull request will remain "clean"), or maybe the wordgraph merge should be done first (since the said fixes are not very urgent) and then we will apply them on top of the merged version.

**Comment by linas** [comment]
Closing, I think everything has been merged.

I have not yet reviewed the wordgraph code; I am surprised that it is 3KLOC larger than before.  I often hope that these changes simplify things rather than making them larger and more complex ...

**Comment by ampli** [comment]
Indeed the code  is larger...
Some comments on the code size:

About half of the added code maybe should not be "counted":
 165    #ifdef DEBUG: The biggest chunk of it can be useful but has not been actually used - synthetic_split().
           Much of the new debug code is not under ifdef so it is not counted in the above.
 160    #if 0: Dead code,  some for debug and unimplemented features, some has been left for documentation.
 660    Wordgraph display (in various files).
  70     The experimental dictcap code. The old capitalization-handling code has not been removed.
100     The new README.
  20     read-dict.c: Enhanced the empty-word comments. Added a FIXME comment.
230     Wordgraph flattening code. Needed until the parsers can work directly on the word-graph.
  10     Enhanced spell.
  50     Fixing an old problem in error.c, that is more severe in the Wordgraph version.
1465   Total of the above.

In addition, some of the other code adds new features:
 - Multi-level alternatives.
 - Better null word marking and morpheme recombining.
 - Better (hopefully) sane morphism handling.
 - Linkage word-graph path.
I also was generous with the amount of comments...

The tokenizer code is essentially the previous one.  It needs much work, to take advantage of the word-graph and the ability of re-splitting. This will maybe make it more compact (but maybe even larger...).

There is a way to make the wordgraph node linking handling somewhat more compact: Instead of using prev and next fields, naming them link[0] and link[1]. This allows writing functions to handle both backward and forward node linking. However, the rest of the code will be less readable unless maybe a union is be defined to enable both names.

After reviewing the code maybe you will have ideas how to improve it, a thing that will most probably make it more compact.
