### ISSUE TITLE
Problem running tests.py

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#67]
I am trying to run tests.py without installing.

I have set  PYTHONPATH to the location of linkgrmmar.py and to the location of _clinkgrammar.so, as follows:
```
export PYTHONPATH=/usr/local/src/link-grammar-devel/master/bindings/python:/tmp/link-grammar/master/bindings/python/.libs
ls /usr/local/src/link-grammar-devel/master/bindings/python /tmp/link-grammar/master/bindings/python/.libs

/tmp/link-grammar/master/bindings/python/.libs:
_clinkgrammar.a   _clinkgrammar.lai                  _clinkgrammar.so    _clinkgrammar.so.5.2.5
_clinkgrammar.la  _clinkgrammar_la-lg_python_wrap.o  _clinkgrammar.so.5

/usr/local/src/link-grammar-devel/master/bindings/python:
AUTHORS  __init__.py.in  LICENSE  linkgrammar.py  linkgrammar.pyc  Makefile  Makefile.am  Makefile.in  README.md
```

However, I get an ImportError:

```
python2.7 /usr/local/src/link-grammar-devel/master/bindings/python-examples/tests.py
Traceback (most recent call last):
  File "/usr/local/src/link-grammar-devel/master/bindings/python-examples/tests.py", line 12, in <module>
    import linkgrammar._clinkgrammar as clg
ImportError: No moduIs there a way tole named _clinkgrammar
Exit 1
```
I can fix this import error by a change in tests.py:
```
-import linkgrammar._clinkgrammar as clg
+import _clinkgrammar as clg
```

Now it runs fine:
```

python2.7 /usr/local/src/link-grammar-devel/master/bindings/python-examples/tests.py
............................link-grammar: Info: Dictionary found at /tmp/link-grammar/master/data/en/4.0.dict
.....................
----------------------------------------------------------------------
Ran 49 tests in 8.183s

OK
```

So how can I run the current tests.py without installing?
(I would like to fix "make check" to do that.)

**Comment by linas** [comment]
If you install, then the PYTHONPATH  is no longer necessary.  If you don't install ... I don't know. I am not a python expert. However, Max, who contributed the fix, might know .. you can try asking him ...

**Comment by maxvyaznikov** [comment]
For that case we can make a tests.py to trying to import from multiple possible places.
First, if a python binding install, it should be ```import linkgrammar._clinkgrammar as clg```. After that, if python import failed, we can try a ```import _clinkgrammar as clg``` for version into PYTHONPATH or local (if _clinkgrammar.so is in one folder with tests.py).
The code will be:
```
try:
   import linkgrammar._clinkgrammar as clg
except ImportError:
   import _clinkgrammar as clg
```

**Comment by maxvyaznikov** [comment]
See #74

**Comment by ampli** [comment]
The fix solved this problem for me.
There is still another unrelated problem, that happens when configuring in a different directory than the source directory:
tests.py expects to find the *.txt files in the current directory. However, when using a different directory for compilation, these files are not there (they are in the source directory). I solved this for now by running tests.py using a script that copies these files before running tests.py. I couldn't just change directory to $(srcdir)/binding/python-examples, because the log files need to be written in the compilation directory.

This can be solved in the same manner as my change to find the location of the dictionary by LINK_GRAMMAR_DATA, e.g. a using LINK_GRAMMAR_PYTHON_TEST_DATA.

**The goal is** that after the compilation, the user will always be able to just invoke "make check".
(Such checks are also usually done by package source installation.)

If such a change is desired, I will send such a fix.

**Comment by ampli** [comment]
The **automake** manual says:
Test programs that need data files should look for them in srcdir (which is both a make variable and an environment variable made available to the tests), so that they work when building in a separate directory [...]

This should fix the problem I mentioned above. I will send a pull request that implements it.

**Comment by linas** [comment]
I think this was merged in pull req #80

**Comment by ampli** [comment]
In 5.2.x-maintenance it seems all the recent python changes has not been applied.
Is this intentional?

**Comment by linas** [comment]
that's right. The python changes go into 5.3.0

**Comment by linas** [comment]
that was my original mistake, I should not have merged the python code into master until after 5.2.5 and as a result, we now have two branches, for the moment.
