### ISSUE TITLE
Missing words

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#680]
I have gathered many missing "interesting words".
Many of them, but not all, are computing or technical terms.
Should I just attach them in a post?

BTW, while fixing typos I found this sentence in `en/corpus-fixes.batch`:
`Hi, can you please freind me?`
It seems like as a misspelling.
`freind.v                     15690  disjuncts <en/words/words-medical.v.4.1>`
Strangely, `friend` is found in the dict only as a noun:
`friend.n                      7735  disjuncts <en/words/words.n.1-const>`

(There are other words in my list which have missing POS in the dict, or have a missing plural.)

Also, is this an error (the only appearance of `lookup` in the dict):
`lookup.a                       206  disjuncts <en/words/words.adj.1-const>`

**Comment by linas** [comment]
send them to me, I'll try to pick through.  I'll fix friend/freind now.

**Comment by linas** [comment]
Just pushed a commit that fixes the above.

**Comment by linas** [comment]
Above merge request fixes many -- I think I got them right, but I might have made a few mistakes.
I did not yet do these:
```
et al.
intra
Re:
v/v (volume/volume)
```

**Comment by linas** [comment]
Closing, I believe everything here was addressed.   Some of it may have been sloppy; I hurried through this.
