### ISSUE TITLE
Setting the directory for build.xml

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#693]
> I changed this because I was getting the error message: BUILD FAILED ... bindings/bindings/java does not exist. Basically, the build is already happening in the java directory, and so the @JAVA_SRCDIR@ -- which is a relative path, for me, is off by one -- it failed to go down low enough.

(I guess the extra **bindings**/... is a copying typo.)

>My build.xml currently contains:
>\<fileset dir="../../bindings/java" excludes="**/*.java"/>
>and it works fine that way.

Indeed with a relative pathes there is a problem, and your fix is not going to correct iit unless you always configure in a subdirectory immediately under the source root (for which your added `../` account).

> I have no clue why/when @JAVA_SRCDIR@ would ever be absolute.

Quoting a [message from Ralf Wildenhues](https://lists.gnu.org/archive/html/autoconf/2011-04/msg00060.html) in the autoconf mailing list:

> 1) If you use
>   ../src/configure
> 
> then srcdir will be relative.
> 
> 2) If you use
>   /absolute/path/to/configure
> 
> then srcdir will be absolute.
> 
> 3) If you pass --srcdir=... to configure, it will be, well, whatever you
> passed.
> 
> 4) If you use
>   `pwd`/configure
> 
> then old Autoconf versions would set an absolute srcdir, while newer
> ones try to be smart and set srcdir to '.'.  Same happens in (3) if the
> passed name happens to resolve to '.'.

I configure in a build path `/tmp/link-grammar/BRANCH`, and hence I get absolute paths for all the variables (what he says is true for all of them).

So just `@JAVA_SRCDIR@` works fine for any path as long as absolute path is used.
And it doesn't generally work for relative path unless tuned in advance according to the relative position of the build directory because a path in `build.xml` is relative to this file and not the source root.
On the other hand, the original `@srcdir@` works fine for both absolute and relative paths because it is the path of the directory of `build.xml` when replacing variables in that file, but it is the source root directory when used in `configure` (and hence I appended `bindings/java`, a thing that badly breaks with relative root source paths).

**My proposed solution:**
```
--- a/configure.ac
+++ b/configure.ac
@@ -606,7 +606,7 @@ if test "x$enable_java_bindings" = "xyes"; then
                CFLAGS="${CFLAGS} -arch x86_64"
        fi
 
-       JAVA_SRCDIR=$srcdir/bindings/java
+       JAVA_SRCDIR=../../bindings/java
        if test "$native_win32" = yes; then
                # javac needs a Windows path
                JAVA_SRCDIR=`cygpath -w "$JAVA_SRCDIR"`
```

**Comment by ampli** [comment]
I don't understand something:
With my proposal above, `src` in `build.xml` results as follows:
`<src path="../../bindings/java"/>`
This works fine (the bindings are created with no error) when I use as a build directory  `/tmp/link-grammar/BRANCH`.
But the source directory for the `*.java` source files are not under this build directory. So how does `javac` find them?

**Comment by linas** [comment]
> I guess the extra bindings/... is a copying typo.

No its not. I got two copies of "bindings" in there. That's the bug.

**Comment by linas** [comment]
Pull req #694 works for me, and based on what you write above, it seems like it should work for you.

**Comment by ampli** [comment]
> it seems like it should work for you.

It works for me when the build directory is under /tmp, 1 or 2 levels (I didn't try more...) under the source directory, or under the parent directory of the source directory. So it seems it works fine now.
