### ISSUE TITLE
API for extended version string

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#728]
From issue [#717](https://github.com/opencog/link-grammar/issues/717#issuecomment-376113203):
> @linas,
> In order to make it easier to understand bug reports, I would like to enhance the output of link-parser --version to include the compiler version, the compilation options and the commit number. The API would be something like const char *linkgrammar_get_version_detailed()
> 
> Several more useful enhancements in this line are possible, e.g. printing on startup the version as shown by git describe. It will be the same as today (e.g. link-grammar-5.4.4) unless it is not an official release, in which case it will be something like link-grammar-5.4.4-51-g497932d3.
> 
> Is it fine by you?

>>@ampli Yes, a detailed, enhanced version is a very good idea.

I implemented it as `const char *linkgrammar_get_configuration(void)`, which returns a **static string**.
Without heavy restructuring of `configure.ac` and the Makefiles, I couldn't extract all the interesting information, like linking flags (even though some more info can be added).

I didn't implement yet an addition for `linkgrammar-get_version()` that uses the info from `git describe` (if available). This is left for another PR.

Here is how it looks on Fedora:
``` text
Compiled with: gcc __VERSION__="7.3.1 20180303 (Red Hat 7.3.1-5)" 
OS: linux-gnu __unix__ 
Standards: __STDC_VERSION__=201112L
Configuration (source code):
	CPPFLAGS=
	CFLAGS=-D_DEFAULT_SOURCE -std=c11 -D_BSD_SOURCE -D_SVID_SOURCE -D_GNU_SOURCE -D_ISOC11_SOURCE -g -O2 -O3
Configuration (features):
	DICTIONARY_DIR=/usr/local/share/link-grammar
	-DPACKAGE_NAME="link-grammar" -DPACKAGE_TARNAME="link-grammar" -DPACKAGE_VERSION="5.4.4" -DPACKAGE_STRING="link-grammar 5.4.4" -DPACKAGE_BUGREPORT="link-grammar@googlegroups.com" -DPACKAGE_URL="" -DPACKAGE="link-grammar" -DVERSION="5.4.4" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_STRNDUP=1 -DHAVE_STRTOK_R=1 -DHAVE_ALIGNED_ALLOC=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -DHAVE_PRCTL=1 -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -DHAVE_LOCALE_T_IN_LOCALE_H=1 -DHAVE_STDATOMIC_H=1 -DTLS=_Thread_local -DHAVE_LIBSTDC__=1 -DHAVE_MKLIT=1 -DUSE_SAT_SOLVER=1 -DHAVE_SQLITE=1 -DHAVE_HUNSPELL=1 -DHUNSPELL_DICT_DIR="/usr/share/myspell/dicts" -DHAVE_EDITLINE=1 -DHAVE_WIDECHAR_EDITLINE=1 -DHAVE_TRE_TRE_H=1 -DHAVE_MAYBE_UNINITIALIZED=1
```
If you do `CPPFLAGS=-Dsomething ../configure` then `-Dsomething` appears in `CPPFLAGS:` above. On a Debug Windows build, `DEBUG;` is shown there.
The compiler name is set by `link-grammar/Makefile`, so if you do `make clean; make CC=clang` it is correctly reflected. On the other hand, if you change the compilation flags using make this is not reflected in this output and it becomes misleading. Also, compilation directive that are embedded in the source code (like the case for MSVC, which has no "configure" step) are not shown.

On a Mac:
```
Compiled with: gcc __VERSION__="4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)" 
OS: darwin17.5.0 __APPLE__ __MACH__ 
Standards: __STDC_VERSION__=201112L
Configuration (source code):
	CPPFLAGS=
	CFLAGS=-D_DEFAULT_SOURCE -g -O2 -O3 -arch x86_64
Configuration (features):
	DICTIONARY_DIR=/usr/local/share/link-grammar
	-DPACKAGE_NAME="link-grammar" -DPACKAGE_TARNAME="link-grammar" -DPACKAGE_VERSION="5.4.4" -DPACKAGE_STRING="link-grammar 5.4.4" -DPACKAGE_BUGREPORT="link-grammar@googlegroups.com" -DPACKAGE_URL="" -DPACKAGE="link-grammar" -DVERSION="5.4.4" -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=".libs/" -DHAVE_STRNDUP=1 -DHAVE_STRTOK_R=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -DHAVE_LOCALE_T_IN_XLOCALE_H=1 -DHAVE_STDATOMIC_H=1 -DTLS=_Thread_local -DHAVE_LIBSTDC__=1 -DHAVE_MKLIT=1 -DUSE_SAT_SOLVER=1 -DHAVE_SQLITE=1 -DHAVE_REGEXEC=1
```
(`gcc` is actually a name of `clang`.)

On Windows:
```
Compiled with: lc  _MSC_FULL_VER=190023918
OS: Windows 10 Home [Version 10.0.16299.309] _WIN32 _WIN64 
Standards: 
Configuration (source code):
	CPPFLAGS=
	CFLAGS=NTDDI_VERSION=NTDDI_VISTA;_WIN32_WINNT=_WIN32_WINNT_VISTA;
Configuration (features):
	DICTIONARY_DIR=None
	USE_WORDGRAPH_DISPLAY;
```
(The CFLAGS and CPPFLAGS appear in the message template but are fake for Windows. As said above, `CPPFLAGS=DEBUG;` is shown for a Debug build, to reflect the use of `-DDEBUG`. I didn't know how to find the actual name of the compiler so I used a fixed string `cl`, which is the name as I know it.)

On `link-parser --version`, I added invocation of this `linkgrammar_get_configuratiion()` just after printing the version by `linkgrammar_get_version()`. I also added a Python binding and print it in `tests.py`.

If this seems fine, I will send a PR.

**Comment by linas** [comment]
This is done, and can be closed, right?

**Comment by ampli** [comment]
Yes.
I also think it will be a good idea to add something like 'get_linkgrammar_features()` that will return a JSON string with the library features (like SAT-parser, wordgraph-display, debug, spell). But this is in my to-do list (after many other things) so I close this issue.
