### ISSUE TITLE
A proposal for link-parser -help and !help

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#729]
On some issue (I could not locate it) I talked about adding a linkage output legend.
Here is a proposal:
```
Output legend (!graphics=1):

 [word]            Null-linked word
 word[!]           Word classified by a regex
 word[!REGEX_NAME] Word classified by REGEX_NAME (turn on by !morphology=1)
 word[~]           Word generated by a spell guess (unknown original word)
 word[&]           Word run-on separated by a spell guess
 word[?]           Word is unknown (looked up in the dict as UNKNOWN-WORD)
 word.POS       Word found in the dictionary as word.POS
 word.#CORRECTION  Word is probably a typo - got linked as CORRECTION

For dictionaries that support morphology (turn on by !morphology=1):
 word=             A prefix morpheme
 =word             A suffix morpheme
 word.=            A stem

For more details see:
	http://www.abisource.com/projects/link-grammar/dict/introduction.html
```
I also noted the following current problem:
`link-parser -help` does not show the command line usage (it is shown only when a bad argument is used, e.g. `link-parser -x`. Instead it shows the internal help only.

**Proposal** (according to [GNU Coding Standards 4.7.2](https://www.gnu.org/prep/standards/standards.html#g_t_002d_002dhelp)):
  - Do not show the internal help (show it only on the internal `!help`).
  - Show the command line usage on `-help`.
  - Show package web links.
  - Then **exit**.

On an incorrect command line usage as `link-parser -x`, I propose to mention `-help` and not `!help`.

The proposed output legend can be shown on !help.
However, a better approach can be to add arguments to `!help`, and show it on `help graphics`. This way help texts can be added for other commands too. In principle, it is possible to extract them from a file (e.g. `data/help.txt`) that will be installed in `PREFIX/share/link-grammar`.
(It can be a major change to allow `!help` arguments, but if we use the fact that we don't have commands starting with `h`, then it becomes a trivial change.)

EDIT:
From the `link-parser(1)'  manual (see the <--- marked line):
```
OPTIONS
       --help Print usage and exit.                  <---

       --version
              Print version number and exit.
```
Somehow my proposed action (as opposed to the current behaviour) is already documented.

**Comment by ampli** [comment]
> In principle, it is possible to extract them from a file (e.g. data/help.txt) that will be installed in PREFIX/share/link-grammar.

I found a problem in implementing that, because I would need to implement a location search that is similar to that of  `dictionary_create_lang()`, a duplication of library code that is not a good idea.
Possible alternatives:
1. Add an API like `char *linkgrammar_get_data_file(char *fn)` to get a file from the root data directory.
    But it looks a too ad-hoc solution.
2. Implement the per-command help as an internal string or data structure in `command-line.c`.

**Comment by linas** [comment]
Sounds reasonable.   I thought that the search for dictionary data file-paths was generic -- that it could be used for any kind of file.  Once  `PREFIX/share/link-grammar/` is found, all languages, and the help files, should be there.

What is needed is a quasi-public API that finds and returns `PREFIX/share/link-grammar/` so that the command-line client can call it.

**Comment by ampli** [comment]
> Once PREFIX/share/link-grammar/ is found

OK, I will make it to return the PATH and not the file content.
So the API will be (is there a better name?):
`linkgrammar_get_data_dir(void)`
Note that it is supposed to search for the data dir as `dictionary_create_lang()` does, i.e. to prefer a local ones (`.`, `data` etc.),  instead of the one set by `dictionary_set_data_dir()` or the system dir, so it can be used also when running from the source/build directories and also when `dictionary_set_data_dir()` has never been called.

**Comment by linas** [comment]
Yes, that seems OK.

**Comment by ampli** [comment]
It is mostly done. But I have some problems.

1. In my implementation, `linkgrammar_get_data_dir()` just calls `object_open(".", data_path_location,...)` when `data_path_location()` returns its argument if it is a directory.
If `dictionary_create_*()` is called before it, then the dictionary path is cached and `linkgrammar_get_data_dir()` will just return it, which is as desired.
This is what happens in link-parser - the dict is always created before `!help name` can be issued, and everything is fine.
However, if at some other program `linkgrammar_get_data_dir()` is called first, it will always return `..`, because this is the component which is checked first and it always exist. Then a call to `dictionary_create_*()` may not find a dict there if `..` is not actually a data directory.

Possible solutions:
1. No implementation changes. Just document `linkgrammar_get_data_dir()` should never be called before `dictionary_create_*()`, and mark it as an experimental API which is subject to changes.
2. Put a marker file in the data directory. For example "data-for-5.5.0". Or maybe the help file itself (I called it `link-parser-help.txt` for a lack of a better name) can be served as a marker. In that case `linkgrammar_get_data_dir()` will invoke `object_open(HELP_FILE, data_path_location,...)` and will always find the correct directory, even when called first (supposing everything is consistent).
However, there is a difficulty here, because the marker file name definition (a pure marker or the help file) will need to be defined in one of the installed include files (maybe `link-includes.h`).
3. This is more complex but more compatible to the current way of locating the data dir: If one of the sub-directories contains a file `4.0.dict`, then this is a data directory.

Proposal:
Leave it as it is now (implementation (1), solution (1)) and later change it if needed.
Regarding the definition of HELP_FILE, just  define it in command-line.c and use the same name in the main Makefile so it will get installed. (BTW, I now think a better name is `command-help.txt`.)

**Comment by linas** [comment]
Yes, `command-help.txt` is a better name.  But maybe `command-help-en.txt` would be better still, because, God help us, someday someone will want help in some other language.  I do not think that day will ever come, but still ... 

Solutions 1 2 or 3 are all OK.  Again, I do not expect that anyone will ever want to use this new API call, so doing only (1) seems reasonable.

**Comment by ampli** [comment]
> But maybe `command-help-en.txt`

I didn't think of that. I propose to address this in a slightly different way.
Possibilities:
1. First look for `command-help.txt` in the data language directory, and if not found then look in the data root directory. In such an implementation, the `en` directory will not include this file.
2. Another way is to make `en/command-help.txt` the last resort help file, but there is a problem in that for systems like Ubuntu that package the languages in their own packages (`link-grammar-dictionaries-en`).  Another slight problem in that is that we don't have an API to find the default language besides calling `dictionary_create_default_lang()`, `dictionary_get_lang()` and `dictionary_delete()` ...).
3. File `command-help.txt` in the data directory, and support the `#include` directive so all the other language directory will initially have a `command-help.txt` with `#include ../command-help.txt`. This seems to me cumbersome and also a code bloat.

So I propose to implement (1).

**Comment by ampli** [comment]
My proposal is **not** good, as it is not useful that the help language will be according to the LG language.
The standard is that it is according to LANG and LANGUAGE, and this is useful.

It looks like this is how some other packages are doing that. For example `/usr/share/gnupg/help.LL.txt` and `/usr/share/gnupg/help.LL-CC.txt`, and `/usr/share/anaconda/help/LL-CC/`. (In the case of `gnupg` the `en` help is just `/usr/share/gnupg/help.txt`, but maybe this is due to historical reasons.)

So your suggestion is better, and I will use it.

**Comment by ampli** [comment]
I just finish the per-command help.
I wrote help text for absolutely almost all of the commands.
`!help command`
displays something like this:
```
linkparser> !help width
width (integer) - The width of the display
Current value:   199
Default value: 16381

When writing to a terminal, this value is set from its width.
```

The first line is directly taken from the internal command table.
The lines after the blank line separators are taken from the help file.

For some command I just added a short description. Some parts of the descriptions I wrote myself, some I copied from the `link-parser.1` manual, and some extended (like for !batch) ones I copied from the `An Introduction to the Link Grammar Parser` document (all with my own adaptation for online help).

Since I did intensive source code changes in the `link-parser` subtree, , I'm not sure if this work is appropriate for the next version, unless you deley it some more in order to:
1. Fix my English and also possible inaccurate or incomplete help text.
2. Get some experience in working with the modified `link-parser` in order to see that there are no major problems with the modified `--command` and `!command` interface.
3. Change things that you don't like...
4. Add things I forgot to add. (I just recalled that I forgot to add `You can use  "!help variable"  ...` in the `!variables` output).

I also would like to add command-line completion.
In theory a word completion of the so-far typed sentences can be added too.

So maybe the next version can be issued which includes the pending PR (#737), and the new help system and completion can be deferred to the version after it.
