### ISSUE TITLE
Wrong parse with "was ... before"

### ISSUE THREAD

**Issue by glicerico** [opencog/link-grammar#736]
Temporal adverb "before" behaves differently than "now", and creates incorrect parse in following sentence:
```
linkparser> Mom was home before.
Found 32 linkages (32 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.40 LEN=5)

    +-----------------Xp----------------+
    +----->WV----->+                    |
    +-->Wd--+--Ss--+---Out--+---Mp--+   |
    |       |      |        |       |   |
LEFT-WALL Mom.l was.v-d home.n-u before .
```
while using "now" gives:
```
linkparser> Mom was home now.
Found 36 linkages (36 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 1.00 LEN=6)

    +----------------Xp----------------+
    +----->WV----->+------MVp------+   |
    +-->Wd--+--Ss--+---Out--+      |   |
    |       |      |        |      |   |
LEFT-WALL Mom.l was.v-d home.n-u now.r .
```
@linas was looking at dictionary rule involving "There is no pine in pineapple"

**Comment by linas** [comment]
I'll see if I can fix this, but the primary reason for modifying the noun, and not the verb, is to disambiguate statements like "... went to hell yesterday, and heaven on Tuesday" .  Attaching the prepositional modifiers to the verb makes it unclear as to when which thing happened; attaching them to each of the two nouns makes it clear which is which.

**Comment by linas** [comment]
I will publish version 5.5.0 in a few weeks, it will contain this fix.

**Comment by glicerico** [comment]
Thanks!

**Comment by linas** [comment]
closing
