### ISSUE TITLE
Random numbers for pick_randomly always repeat

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#742]
Please see [this question](https://groups.google.com/d/msg/link-grammar/gYXvOTMTyyY/SQmdsO-DAQAJ) in the discussion group.

In the code, when the `rand` option is set to non-repeatable, the pseudo-random sequence **always** start with 42.  Shouldn't it start in that case with a true random number?

**Comment by linas** [comment]
Changing 42 to something else will not magically scramble the order in which parses are reported.  The rand is used only if there are more parses than the `linkage_max`, only then are they randomly sampled.

**Comment by ampli** [comment]
> only if there are more parses than the linkage_max, only then are they randomly sampled

Yes, but my point is that then the random sequence is always exactly repeated, so the same linkages per sentence are always chosen.

The only difference between `!rand=0` and `!rand=1` is that a different repeated pseudo-random sequence is used in each of these case.

Since `!rand=1` is defined as **Use repeatable random numbers** I would expect `!rand=0` to start with a **random** seed and not always 0.

**Comment by linas** [comment]
Ugh. OK. Fixing this seems like overkill that adds complexity without improving anything. But whatever. Use the low bits from `clock_gettime(CLOCK_REALTIME)` or something like that.
