### ISSUE TITLE
I know it's...We all know what's going on down there.

### ISSUE THREAD

**Issue by cdmalcl** [opencog/link-grammar#744]
I know it's...We all know what's going on down there.

"it's...We[?].n"

**Comment by ampli** [comment]
In this case if you add `...` `MPUNC` (see #743) this tokenizes the `...`, but `We` doesn't link (unless you uncapitalize it).
`LEFT-WALL I.p know.v it 's.v ....y [We] all.a know.v what 's.v going.v on down.e there.r`

The reason is that capitalization is currently not recognized after `...`.

**Comment by linas** [comment]
I just added elipses to fix #743 

I just pushed a commit that allows capitalization after an ellipsis; this will be in version 5.5.0 later today
