### ISSUE TITLE
Using "#inclue <filename>" in link-parser

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#746]
```
grep -r '#include <link-grammar/' link-parser
link-parser/command-line.h:	#include <link-grammar/link-features.h>
link-parser/command-line.h:	#include <link-grammar/link-includes.h>
link-parser/command-line.c:	#include <link-grammar/link-includes.h>
```
Since link-parser is part of the distribution, **I propose to use `#include "filename"` instead.**
Else if the system has an installed LG library, a definition mix may result (that may be even hard to debug).

**Comment by linas** [comment]
Yeah, OK, I guess. The original intent was that the parser served as an "example program", but that seems no longer a viable argument.

**Comment by ampli** [comment]
We may add a comment that says something like:

If you compile your own program out of the LG source-code tree, use "#include <...>" in order to pick up the corresponding include files from the LG package system installation.

**Comment by ampli** [comment]
An even worst problem exists in [`dict-structures.h`](https://github.com/opencog/link-grammar/blob/59600dd3a357076c288f4b914bd56accc8db62e4/link-grammar/dict-common/dict-structures.h#L17):

`#include <link-grammar/link-features.h>`

This mixes a possible system include when compiling the library from the source tree.
It seems `#include "link-grammar/link-features.h"` is better, as it first searches for it locally before searching for it in the system includes. A quote from the [`cpp` documentation](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html) (emphasis mine):

By default, the preprocessor looks for header files included by the quote form of the directive #include "file" first relative to the directory of the current file, **and then in a preconfigured list of standard system directories**.

So if we use `#include "link-grammar/link-features.h"` it will work as intended even if `link-grammar/dict-structures.h` is included by a user in order to pick up the corresponding system include file.

I will change it too.

**Comment by ampli** [comment]
An even worst problem exists in `dict-structures.h`

**Comment by linas** [comment]
`dict-structures.h` is installed, so it has to work appropriately when included in user apps.

**Comment by ampli** [comment]
>> dict-structures.h is installed, so it has to work appropriately when included in user apps.

I wrote:

> #include "link-grammar/link-features.h" is better, as it first searches for it locally before searching for it in the system includes.

Note that  `#include "link-grammar/link-features.h"` **searches in the system includes** after it searches relative to the directory of the current file. If the user has it locally it means this is a compilation from the source/build tree, so this is fine. **Else it will be taken from the system**.

Please see the quote from the I brought in my post above from the **[`cpp` documentation](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html)**, and also please test it yourself.
