### ISSUE TITLE
Allowing input words that happen to be regex labels in 4.0.regex

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#756]
Here is my proposal:
1. Prepend a dot to regex labels in 4.0.dict.
2. The dict reading code will convert them to a character that cannot appear in the input, say `^R`.
3. The `regex-morph` code will search for labels after prepending them `^R`.
4. The `!!` support code will understand a word starting by `.` and then `[A-Z]` as a regex label (a real hack is needed, but it is not too horrible).

**Comment by linas** [comment]
The problem is not just a regex-label problem, it affects all defined macros.  e.g.
```
<post-nominal-x> is not a regex label.
```
fails, but
```
<post-nominal-xx> is not a regex label.
```
"almost works".  The angle brackets make it highly unusual that it will appear in "normal" text, but its essentially the same issue as the regex labels.  We can put the regex labels into angle brackets; this seems to work.

**Comment by linas** [comment]
I will change to use angle brackets for all regex labels tomorrow.

**Comment by ampli** [comment]
> but
> `<post-nominal-xx> is not a regex label.`
> "almost works".

LEFT-WALL [<] post-nominal-xx[!HYPHENATED-WORDS].n >.v [is] not.e a regex.n label.n .

However, this addition seems to perfectly solve the problem:

At the end of 4.0.regex (of all the languages), before UNKNOWN-WORD:
`WORD-IN-GTLT: /^<[^>]*>$/`

In 4.0.dict (of all the languages):
`CAPITALIZED-WORDS WORD-IN-GTLT: [<entity-singular>]0.06;`

Then:
LEFT-WALL <post-nominal-xx>[!WORD-IN-GTLT] is.v not.e a regex.n label.n .

**Comment by ampli** [comment]
I admit that this WORD-IN-GTLT regex is not more needed (and maybe even less) than regexes for hashtag, @username, email address, URL, etc.

**Comment by linas** [comment]
The `WORD-IN-GTLT` idea sounds great, except that it is not working for me.  What am I doing wrong?

**Comment by ampli** [comment]
I don't know what you did, but I can send it as PR.

**Comment by linas** [comment]
I moved WORD-IN-GTLT so that it appears before HYPHENATED-WORDS but the regex never triggers for me.

**Comment by ampli** [comment]
I just sent what works for me as PR #758.

**Comment by linas** [comment]
I get this:
```
linkparser> <post-nominal-x> is not a regex label
No complete linkages found.
Found 14 linkages (12 had no P.P. violations) at null count 2
	Linkage 1, cost vector = (UNUSED=2 DIS= 0.30 LEN=11)

                               +--------SIs*b--------+
                               |        +----Ds**x---+
    +----------->Qd------------+        |    +---AN--+
    |                          |        |    |       |
LEFT-WALL [<post-nominal-x>] is.v [not] a regex.n label.n
```
but this works:
```
linkparser> <post-nominal-xx> is not a regex label
Found 4 linkages (4 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 0.36 LEN=11)

                                             +---------Osm---------+
    +------------------>WV------------------>+        +----Ds**x---+
    +--------->Wd---------+-------Ss*s-------+-EBm+   |    +---AN--+
    |                     |                  |    |   |    |       |
LEFT-WALL <post-nominal-xx>[!WORD-IN-GTLT] is.v not.e a regex.n label.n

Press RETURN for the next linkage.
```

**Comment by ampli** [comment]
Strange. Maybe you can push your branch with this fix and I will try it.

**Comment by linas** [comment]
https://github.com/opencog/link-grammar/compare/master...linas:foo

**Comment by linas** [comment]
above is branch where it does not work, for me.

**Comment by linas** [comment]
"word" - you mean, using quotes in the dictionary?

**Comment by ampli** [comment]
> "word" - you mean, using quotes in the dictionary?

See our discussion in issue #699.
We concluded that `"word"` should be translated to UNKNOWN-WORD, in addition to be split as now to `" word "` (3 tokens).

I tried it with regex and this time is works (mostly):
```
-UNKNOWN-WORD.n:
+UNKNOWN-WORD.n QUOTED-WORD.n:
...
-UNKNOWN-WORD.v:
+UNKNOWN-WORD.v QUOTED-WORD.v:
...
-UNKNOWN-WORD.a: [<ordinary-adj> or <adj-phone>]0.04;
+UNKNOWN-WORD.a QUOTED-WORD.a: [<ordinary-adj> or <adj-phone>]0.04;
```
and
```
+QUOTED-WORD: /^"[[:alnum:].-]+"$/
```

And now:
```
linkparser> We should distinguish between "who" and "whom" but who fucking cares?
...
LEFT-WALL we should.v distinguish.v between "who"[!QUOTED-WORD].n and.j-n "whom"[!QUOTED-WORD].n but.ij who fucking.e cares.v ?
```

I said mostly, because in case the quoted word is an unknown word, it is also tried as such:
```
linkparser> This is a test to "ttttt"
...
LEFT-WALL this.p is.v a  test.n to.r "ttttt"[!QUOTED-WORD].n
...
LEFT-WALL this.p is.v a  test.n to.r  " ttttt[?].n "
```

**Comment by linas** [comment]
After merging #759  I am now getting this mysterious error:
```
linkparser> we ran around the bases
link-grammar: Error: Word 'base': word is unknown
link-grammar: Error: sentence_split(): Internal error detected
```

**Comment by linas** [comment]
Hmm. And I also broke UNKNOWN-WORD somehow.
```
linkparser> I read whatever I could about the subjetc
link-grammar: Error: Word 'subjetc': word is unknown
link-grammar: Error: Sentence not in dictionary
The following words are not in the dictionary: "subjetc"
	Failing sentence contains the following words/morphemes:
	LEFT-WALL I i read whatever could about the subjetc RIGHT-WALL 
```

**Comment by ampli** [comment]
> linkparser> we ran around the bases

It seems it has something to do with UNITS.
I'm now with the repeatable_rand stuff, but I will take a look at that.

**Comment by ampli** [comment]
Again my bad markdown...
It should now be `"<UNKNOWN-WORD>"`.

**Comment by ampli** [comment]
This also reveals a tokenization bug:
In addition to issuing `bases`, `bases` also gets unit-split to `base s` - which is as designed.
However, somehow `base` is still unknown at the time of fetching the expressions from the dict.

This doesn't cause a problem in this sentence when `UNKNOWN-WORD` (or rathrer `<UNKNOWN-WORD>` now) is found. This also doesn't cause a problem in constructs like `10s` or `1000s`- 10 is known from `4.0.dict` and 1000 is known from `4.0.regex`.

I will take a look at it after I send the PR for the rand problem.

**Comment by linas** [comment]
Thanks. Very strange. When I fix `#define UNKNOWN_WORD "<UNKNOWN-WORD>"` then the base/bases problem goes away too.

**Comment by ampli** [comment]
@linas,
Please note that this regex label conversion must be done for all the languages, or at least you must add `<UNKNOWN-WORD>` to all the other dictionaries in addition to `UNKNOWN-WORD` !!!

The ru language malfunction now due to the missing `<UNKNOWN-WORD>` that the code now look up...

**Comment by ampli** [comment]
> The base/bases problem is a mostly hidden bug that got revealed by the missing unknown-word definition
> It happens in a very rare case

The only other case I found in the LG corpus is the `/`'s in the following:
A miner's inch is defined as 1/60 ft³/s.

**Comment by ampli** [comment]
Summary:
Using <REGEX_LABEL> is better than a reference to just  REGEX_LABEL  because `<word>` is a rer-enough combination. However, for a perfect solution, it was better to allow `<word>` in the input.
But defining regex WORD-IN-GTLT todoesn't work for words that appear in the dict, because regexes are not checked for words in the dict.
A scheme that has more control on the cases in which regexes are applied can allow them to work on words in te dict (and in more cases in which they don't apply now), but this is another issue, than can be opened when there are more examples in which it is desired, along with a proposed mechanism how to do that.

So I'm closing this issue.
