### ISSUE TITLE
#warning "_BSD_SOURCE and _SVID_SOURCE are deprecated...

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#76]
I just upgraded my system to Fedora 21, and started to get 80+ of these warnings while compiling:
```
/usr/include/features.h:148:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
```

It turned out this is so with glibc>=2.20. 
See http://man7.org/linux/man-pages/man7/feature_test_macros.7.html .
I will send a pull request that fixes it (in a backwards compatible way).

**Comment by linas** [comment]
fixes merged in pull requests #77 #81
