### ISSUE TITLE
Missing files in the distribution tar

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#765]
I noted the fix in 6b29264a1b720506d42b5ace8ca67cd2bbba2984 of my error that caused `msvc14/` to not be included in the distribution.

So I tried to add a `distcheck-hook` entry to check that all the repository files that are intended for distribution are indeed found in the tar file. It makes "make distcheck" to fail if a file is missing.

I found the following files which are not in the tar file, but more probably some should be (no comment means that I don't know if they should be in the distribution):

file | comment
---- | ------------
data/he/4.0.dict.m4  | I will add it
debug/README.md | I would like to add it
link-grammar/minisat/LICENSE | Must be added...
link-grammar/minisat/* | OK to omit - not related
morphology/ar/ | Maybe an unintended omission (*)
morphology/fa/ | Maybe an unintended omission (*)
link-grammar/sat-solver/matrix-ut-test.cpp | An intended omission
link-grammar/sat-solver/sat-based-link-grammar-parser.pdf | Maybe should be added
data/en/corpus-failures.batch
data/en/corpus-fix-needed.batch
data/ru/tools/
data/sql/README
data/vn/linkgrammar.vi.txt |   Maybe an intended exclusion
link-grammar/corpus/cluster-pop.c
link-grammar/corpus/sniff.c
link-grammar/malloc-dbg.c
.gitignore | Of course an intended exclusion
viterbi/ | An intended exclusion

 __(*)__ The reason that I think the omission of `morphology/fa/` and `morphology/ar` is unintended is that `morphology/README` and `morphology/Makefile.*` are included.

The said `distcheck-hook` entry compares "git ls-files' to the tar file list.
If you like this idea, we will need to add a file like EXCLUDED to list the few files (including itself) that exist in the repository but are not intended for distribution in the `tar` file.

**Comment by linas** [comment]
only the first three need to be added. The rest are omitted because they are not useful to end-users.
