### ISSUE TITLE
LG raises an exeption '... :word is unknown' although 'UNKNOWN-WORD: XXX+;' is in dictionary

### ISSUE THREAD

**Issue by alexei-gl** [opencog/link-grammar#771]
Link grammar raises exceptions when using Python API:
```
link-grammar: Error: Word '.': word is unknown
link-grammar: Error: Sentence not in dictionary
The following words are not in the dictionary: "."
	Failing sentence contains the following words/morphemes:
	sausage was a food before . 
```
Although the '.' is actualy not in the dictionary 'UNKNOWN-WORD: XXX+;' is specified at the end of the dictionary file.
When using link-parser executable I get the same errors.

Installation details:
Link Grammar version: 5.5.0 build from the official distribution tar ball.
OS: Ubuntu 17.04
Dictionary file is attched.
[dict.tar.gz](https://github.com/opencog/link-grammar/files/1978488/dict.tar.gz)

**Comment by linas** [comment]
Punctuation is not normally considered a "word", although that depends on the contents of `4.0.affix`

Look at your 4.0.affix file, and make sure the period does not appear there.

**Comment by linas** [comment]
Also double check that your 4.0.regex file doesn't have any regexes that could match punctuation.

**Comment by alexei-gl** [comment]
Previous version of link-parser works fine with the same .dict, .affix and .regex files. Has anything changed conceptualy with 5.5.0 version?

**Comment by ampli** [comment]
@alexei-gl,
In 5.5.0 `UNKNOWN-WORD` has been renamed to `<UNKNOWN-WORD>`, but in your dictionary it still appears as `UNKNOWN-WORD`.

@linas,
Maybe we should have a fallback in the code that tries to read `UNKNOWN-WORD` if `<UNKNOWN-WORD>` is not found, with a possible warning on obsolete name. (If the user has it as `UNKNOWN-WORD` in `4.0.regex` it will still not match, but a clear error is generated in that case `Error: Regex name <UNKNOWN-WORD> not found in dictionary`).
Also, I guess this needs to be updated in the docs.
Maybe something like:
`Note: From Link-grammar version 5.5.0 it is <UNKNOWN-WORD>.`

**Comment by ampli** [comment]
@linas 
I started to implement it by this change:
``` diff
 #define UNKNOWN_WORD "<UNKNOWN-WORD>"
+#define UNKNOWN_WORD_FALLBACK "UNKNOWN-WORD" /* Old name - for compatibility. */
...
-       bool         unknown_word_defined;
+       const char * unknown_word;
```
The idea was to set `unknown_word` to the one actually found and from then use `dict->unknown_word` instead of `UNKNOWN-WORD` (print a warning if the old name is used).

But it occured to me that another change is possible:
In `sentence_in_dictionary()`, check for `UNKNOWN-WORD` in the dict, and if found, print a warning like:
`Warning: Old name "UNKNOWN-WORD" found in the dictionary. Use "<UNKNOWN-WORD>" instead.`

Please tell me which of these approaches is preferred.

**Comment by linas** [comment]
The warning should be sufficient. I believe that Alexei is the only person in the world who has a text dictionary that is not part of the distro. 

Alexi -- btw, I mentioned before - you will almost surely find that the sqlite3 dictionary is easier and more convenient to use. Its easier to edit, easier to export to, easier to automate.   The text dicts are only for hand-maintained lexis.

**Comment by ampli** [comment]
> The warning should be sufficient

Ok.



> sqlite3 dictionary

This reminds me that I didn't check the connector descriptor stuff with an SQL dictionary.
How can I check it?

The current implementation of the connector descriptor table doesn't allow for adding new connector names after the initial read of the directory (adding expressions with existing conector names should be fine). If this is needed in the SQL version, a more complex implementation of the connector descriptor table is needed.

**Comment by linas** [comment]
The dist should have a file `link-grammar/dict-sql/demo.sql` and the README.md should explain all !?

The API is that expressions are fished out straight from the database, without first reading the dictionary.

**Comment by ampli** [comment]
> the connector descriptor table doesn't allow for adding new connector names after the initial read of the directory

Fixxed in PR #777.
