### ISSUE TITLE
Connectors with uppercase letters in their subscript are not rejected

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#775]
Currently, connector labels like `A01B02` are not rejected.
The part after the initial `A` is considered as a subscript, which is not supposed to contain uppercase letters.

It seems that the code (including the latest one which encode subscripts into a 64-bits number) just doesn't care.

But nevertheless I propose to add a check in `check_connector()` to reject such connector subscripts.

**Comment by ampli** [comment]
Do you mean that numbers can be both a part of the connector subscript and part of the uppercase letters?

How this should be interpreted?
`C1`
Currently `C` is interpreted as the uppercase part, and `1` as the subscript.

Questions:
- Should we **change** it to interpret `C1` as the uppercase part?
- Or do you propose some complex rule, like numbers to be part of the connector subscript only if there are no uppercase letters after them?

**Comment by linas** [comment]
I don't want a complex rule. As far as I know, none of the existing dictionaries use numbers as connector "subscripts". So I believe that we could safely extend the definition of "uppercase" to mean "uppercase or number", without breaking anything.

Hmm Maybe. do recall you wanted to pack upper-case into 5 bits, and uppercase+number would not fit into 5 bits. If this pack-uppercase-into-5-bits idea is still alive, then numbers should be treated as part of the "subscript".

 A third alternative would be to not allow numbers at all.  Which is not a bad alternative...

**Comment by ampli** [comment]
> existing dictionaries use numbers as connector

Here are the current ones:
fa (Spn1, Spn2)
he (many)
kz (many)
ru (many)
tr (Va3s, Va3p, Np2, Np3)

> safely extend the definition of "uppercase" to mean "uppercase or number", without breaking anything.

It will break `ru` and `he`, which use `*` to match subscripts witch include numbers.
E.g. `ru` has `SIp3` and `SI*3` and more, and `he` extensively uses subscripts with numbers and `*`.
It will also break '`kz', which has `OFr2p` and `OFr2`  and `tr` which has `Np3` and `N`.
Of course all of them can be "fixed", e.g. changing 1,2,3 to a,b,c, but this will be somewhat less conveniente and readable.

> pack upper-case into 5 bits

This was in my original proposal.
In the actual implementation the uppercase part is just enumerated and doesn't need to be packed.
(So currently comparing the uppercase part is just comparing two integers, and their enumeration serves as a perfect hash for them.)

> A third alternative would be to not allow numbers at all. Which is not a bad alternative...

I don't see why it is good (beside the possibility to pack 12 subscript letters instead of max. 10), as it is much clearer to use numbers for N-person connectors. I just propose to enforce a check which is consistent with their usage in the current dictionaries.

**Comment by linas** [comment]
OK, Right. I guess I completely forgot about russian and didn't much look at the others. So we should not change that.

Then yes, any capital letters appearing after a lower-case or a number is illegal, and should be explicitly checked for during dictionary read, (or other convenient point?, for sql)

**Comment by linas** [comment]
> the language-learning project is using such names.

Still? Again? Did we open a bug report against them? I'd rather have them change. They're not experienced software developers, and its kind-of important that they learn how to play by the rules, instead of just creating random messes for others to work around.

**Comment by ampli** [comment]
They still use such names, also in the last dict file that has been committed on July 31.
I will open an issue there.
