### ISSUE TITLE
link-parser looses sentences when piped with a big corpus

### ISSUE THREAD

**Issue by alexei-gl** [opencog/link-grammar#802]
`link-parser` looses sentences when piped with a big corpus. Sentence count of the original corpus does not match the sentence count of the `link-parser` output stream. This problem does not happen with small corpora. I ran the test several times on ver 5.4.4 and on the latest version built from github sources. The problem exists in both versions. Because the amount of test data is huge for github, I only attach test script and the result output file. You can repeat the test either on the same data downloaded from http://langlearn.singularitynet.io/data/cleaned/English/PubMed/train/lower/pubmed-articles.txt_default or using your own data file, but be prepared to wait for ~6 hrs, depending on your hardware. The script can be run by typing `./no-of-sent-test.sh pubmed-articles.txt_default`
[test-script.tar.gz](https://github.com/opencog/link-grammar/files/2216761/test-script.tar.gz)

**Comment by ampli** [comment]
From identical input batches, are these the same sentences that are missing every time?
Can you please give me examples of missing sentences?

**Comment by alexei-gl** [comment]
It may look weired but I managed to get the exact sentence list out of the output. It looks like there are some special characters interfere.
As you have already observed the exact number of sentences is 165348, but using my python wrapper code and `csplit` I get 165333. As you have observed the linkages are separated by blank lines, But if I count blanks I get:
```
alex@alex-X510UN:~/data/tests/1$ grep -cP "^$" pubmed-articles.txt_default-postscript-clean 
165332
```
If I count trailing `[0]` I get:
```
alex@alex-X510UN:~/data/tests/1$ grep -cP "^\[0\]$" pubmed-articles.txt_default-postscript-clean 
165333
```
If I parse it like `output.split("\n\n")` from within my python code I get the same 165333.
But with some nifty `sed` manipulations I managed to get proper 165348:
```
alex@alex-X510UN:~/data/tests/1$ sed -n '1,/^\[(/p' pubmed-articles.txt_default-postscript-clean | sed '/^\[(/d' > restored
alex@alex-X510UN:~/data/tests/1$ sed -n '/^$/,/^\[(/p' pubmed-articles.txt_default-postscript-clean | sed '/^$/d;/^\[(/d' >> restored
alex@alex-X510UN:~/data/tests/1$ diff pubmed-articles.txt_default-no-blanks restored
alex@alex-X510UN:~/data/tests/1$ wc -l restored
165348 restored
```
As it turned out it is not exactly a `link-parser` issue, but if you have any ideas why could that happen, please let me know. By the way `pubmed-articles.txt_default-postscript-clean` is a file with `link-parser` linkages output without leading parameter setting lines and trailing 'Bye.' line.

**Comment by alexei-gl** [comment]
It is still an issue. I extracted skipped sentences and parses they sticked to. Please, see attachments. 
[skipped-parses.txt](https://github.com/opencog/link-grammar/files/2221809/skipped-parses.txt)
[skipped-sentences.txt](https://github.com/opencog/link-grammar/files/2221810/skipped-sentences.txt)

**Comment by linas** [comment]
OK, but link parser tells you what to do: 
```
linkparser> we also presented the time trends of copd between @number@ and @number@ by age , gender and setting ( urban vs rural ) .
No complete linkages found.
link-grammar: Warning: Combinatorial explosion! nulls=2 cnt=17530328
Consider retrying the parse with the max allowed disjunct cost set lower.
At the command line, use !cost-max
Found 17530328 linkages (0 of 1000 random linkages had no P.P. violations) at null count 2
```

Of course, you can play with the disjunct costs, or asking for more than 1000 parses.

However, the sentence is obviously mall-formed. Just replace `@number@` by an actual number, and it mostly works.

**Comment by linas** [comment]
`the accumulation of aggregated β-amyloid and tau proteins into plaques and tangles is a central feature of alzheimer disease ( ad ) .`

Write `alzheimer` in uppercase, and then it works. The link parser can recognize `Alzheimer` as a proper name, because it is capitalized. It has a lot more trouble with the lower-case word; it struggles to guess what it is.

**Comment by linas** [comment]
`those findings might help to develop new classes of drugs which may supplement or replace classical anticoagulants and help clinicians to tackle cvd more efficiently.`

As before, the parser provides a suggestion:
```
No complete linkages found.
link-grammar: Warning: Combinatorial explosion! nulls=1 cnt=29156927
Found 29156927 linkages (0 of 1000 random linkages had no P.P. violations) at null count 1
```
 Set `!limit=6000` and it will find a parse.

**Comment by alexei-gl** [comment]
Thank you, Linas! The problem is clear. We will discuss further strategy at today's meeting.

**Comment by linas** [comment]
Also: there is a way to alter the link-grammar dict to add support for markup such as `@number@` or `@date@` or `@time@` -- its not hard. We used to do that, for RelEx, some 6-8 years ago, when RelEx used a "Named Entity Recognizer" (NER) to find named entities, and substitute these generic tags for them. This seemed like a great idea, way back then.  Then, during a commercial deployment for a search engine for financial news (lots of named entities - banks, companies, newservices, dates, times, money amounts) we discovered that Link Grammar was more accurate than the NER software was!  And not just a little bit, but by a lot!  (Not a surprise: context is important for NER, and all NER packages ignore context ) At that point, the NER got riped out and thrown away.

If you think you can do better by using things like `@number@` or `@date@` or `@time@`  -- well, you can try, if you want to, and convince yourself however, but historical experience shows that this is a loosing strategy. 

But if you do have an NER package that is higher accuracy than LG, let me know. Provide examples.

**Comment by akolonin** [comment]
Just note that we should not expect that LG with English dictionary should parse these @number@ or @date@ or @time@ - we need them to be parsed only if they have corresponding placeholder entires in the rules of the dictionary learned programmatically with the "normalized" corpus which contains these placeholders.

**Comment by ampli** [comment]
Is there something more to do here?
Or can this issue be closed now?

**Comment by alexei-gl** [comment]
No. It's all clear. Thank you!
