### ISSUE TITLE
Bug with linkage_get_*(linkage, w) and morphology=0

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#828]
I noticed this bug when I saw output like:
```
Display of disjuncts used turned on.
link-grammar: Info: Dictionary found at ../ru/4.0.dict
link-grammar: Info: Dictionary version 5.3.15, locale ru_RU.UTF-8
link-grammar: Info: Library version link-grammar-5.5.1. Enter "!help" for help.
linkparser> сержант мгновенно повернулся , пытаясь определить направление .
Found 6 linkages (6 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 2.00 LEN=22)

    +--------------------------------------------------Xp--------------------------------------------------+
    +-------------------Wd-------------------+                                                             |
    |           +-------------Sm3------------+---------D--------+                                          |
    |           |            +-------EI------+         +---Xc---+-------I-------+-------MVv------+         |
    |           |            |               |         |        |               |                |         |
LEFT-WALL сержант.nlmsi мгновенно.e повернулся.vsndpms , пытаясь.vnnddn определить.vspdi направление.ndnsv .

            LEFT-WALL    0.000  W+ Xp+ 
        сержант.nlmsi    0.000  Sm3+ 
          мгновенно.e    1.000  EI+ 
   повернулся.vsndpms    0.000  LLFWG+ 
                    ,    0.000  LLFWG- EI- Sm- Wd- D+ 
       пытаясь.vnnddn    0.000  Xc+ 
     определить.vspdi    0.000  LLDEM+ 
    направление.ndnsv    0.000  LLDEM- Xc- D- I+ 
                    .    0.000  LLFWV+ 
           RIGHT-WALL    0.000  LLFWV- I- MVv+ 

Press RETURN for the next linkage.
linkparser> !m
Display word morphology turned on.
linkparser> сержант мгновенно повернулся , пытаясь определить направление .
Found 6 linkages (6 had no P.P. violations)
	Linkage 1, cost vector = (UNUSED=0 DIS= 2.00 LEN=22)

    +----------------------------------------------------------Xp----------------------------------------------------------+
    +----------------------Wd----------------------+                                                                       |
    |           +----------------Sm3---------------+----------D----------+                                                 |
    |           |            +----------EI---------+       +------Xc-----+----------I----------+----------MVv---------+    |
    |           |            |          +---LLFWG--+       |    +--LLDEM-+          +---LLFWV--+           +---LLARP--+    |
    |           |            |          |          |       |    |        |          |          |           |          |    |
LEFT-WALL сержант.nlmsi мгновенно.e поверн.= =улся.vsndpms , пыта.= =ясь.vnnddn определ.= =ить.vspdi направлени.= =е.ndnsv .

            LEFT-WALL    0.000  W+ Xp+ 
        сержант.nlmsi    0.000  Sm3+ 
          мгновенно.e    1.000  EI+ 
             поверн.=    0.000  LLFWG+ 
        =улся.vsndpms    0.000  LLFWG- EI- Sm- Wd- D+ 
                    ,    0.000  Xc+ 
               пыта.=    0.000  LLDEM+ 
          =ясь.vnnddn    0.000  LLDEM- Xc- D- I+ 
            определ.=    0.000  LLFWV+ 
           =ить.vspdi    0.000  LLFWV- I- MVv+ 
         направлени.=    0.000  LLARP+ 
             =е.ndnsv    1.000  LLARP- MVv- 
                    .    0.000  Xp- RW+ 
           RIGHT-WALL    0.000  RW- 
```
Note than when `!morphology=0`, the displayed disjuncts are "out of sync".
This happened due to the following change in `linkage_print_disjuncts()` (commit 1cfdcf4db2f7e1f8e47a443abf1c5fa9fa371871):
``` diff
@@ -263,12 +263,17 @@ char * linkage_print_disjuncts(const Linkage linkage)
                Disjunct *disj = linkage->chosen_disjuncts[w];
                if (NULL == disj) continue;
 
                /* Subscript mark will be cleaned up by append_string(). */
                infword = disj->word_string;
 
+               /* ... except that subscript marks confuse utf8_strwidth() */
+               /* linkage->word[w] should be same as disj->word_string except
+                * that the subscript mark hs been replaced by a dot. */
+               infword = linkage->word[w];
```
Note that in the modified code, linkage->word[] is used instead of `linkage->chosen_disjuncts[]`.
The "out of sync" happens when `linkage->word[]` has been modified to support `!morphology=0`.

On first glance a fix can be introduced to again use `linkage->chosen_disjuncts[]`, but this time after
converting `SUBSCRIPT_MARK` to `SUBSCRIPT_DOT`, so we always display the disjuncts of the
not-combined tokens.

But this is not good, because we don't know the upper limit of  `linkage->chosen_disjuncts[]`, since there is no Linkage struct field for it: we have `cdsz` which is its allocated length, and `num_words` which get reduced when we combine words for `!morphology=0` and create a new `linkage->word[]`.

So it seems a field for the correct size of `linkage->chosen_disjuncts[]` can be added (and used here) and all will be fine.

But there is a more severe problem: The linkage words are returned from the modified `linkage->word[]`.
Note that `num_words` is the length of `linkage->word[]`.
```c
const char ** linkage_get_words(const Linkage linkage)
{
        return linkage->word;
}
size_t linkage_get_num_words(const Linkage linkage)
{
        if (!linkage) return 0;
        return linkage->num_words;
}
```

However, other `linkage_get_*()` functions take works from `chosen_disjuncts[]` that  may be totally different:
```c
const char * linkage_get_disjunct_str(const Linkage linkage, WordIdx w)
{
        Disjunct *dj;

        if (NULL == linkage) return "";
        if (NULL == linkage->disjunct_list_str)
        {
                lg_compute_disjunct_strings(linkage);
        }

        if (linkage->num_words <= w) return NULL; /* bounds-check */

        /* dj will be null if the word wasn't used in the parse. */
        dj = linkage->chosen_disjuncts[w];
        if (NULL == dj) return "";

        return linkage->disjunct_list_str[w];
}
```
Moreover, we even don't have a function to return the length of `chosen_disjuncts[]`.

**Fix proposal:**
1. In `compute_chosen_words()`, modify `linkage->chosen_words[]` according to `linkage_word[]`.
(I tested that and it works fine).
2.  In addition, add code for `!morphology=0` support, to remove the discarded links from the link-array (we once wanted to do that for ZZZ, see #241).

If this is fine, I can send a PR.

**Also:**
In addition the docs may  mention somewhere that for raw library results one should set `morphology=1`, which is not the default. But I think it should have been the default of the library (and `morphology=0` still  the default of `link-parser`).
But now that we have this bug, we see that tryng to extract linkage details when `morphology=0` makes a difference didn't work for much time now, so maybe we can change this default along with this fix.

**Comment by linas** [comment]
I'm somewhat confused by above.  Originally, the `parse_options_set_display_morphology()` function was supposed to set a flag that only altered the display/printing, and not the actual processing.  However, I see that `HIDE_MORPHO` has already leaked out of that bottle, so to make everything consistent, the additional fixes to `compute_chosen_words()` seem necessary.  Also, for consistency, part 2 also seems to be needed.

Yes, the default of the library should definitely be `morphology=1`

**Comment by ampli** [comment]
> If you think this is not a real problem, I can send the PR right away. Else I need your input on what to do regarding that.

I can send it first without the `display_morphology` default change, but UI first need the cleanup (#835) PR to be applied in order to prevent a conflict.

**Comment by linas** [comment]
Earlier, you said this: 

> for raw library results one should set morphology=1, (and morphology=0 still the default of link-parser).

which still seems reasonable to me. Users of the command-line client won't see any change; users of the library will maybe get a surprise.
