### ISSUE TITLE
Unable to run Link Parser with 'dict.db'

### ISSUE THREAD

**Issue by leungmanhin** [opencog/link-grammar#841]
Steps I followed, from the `link-grammar` directory:

```
mkdir data/foo
cp data/demo-sql/4.0.* data/foo
cat link-grammar/dict-sql/dict.sql |sqlite3 data/foo/dict.db
cat link-grammar/dict-sql/demo.sql |sqlite3 data/foo/dict.db
link-parser ./data/foo
```

And I got:

```
link-grammar: Error: Could not open dictionary "./data/foo/4.0.dict"
link-grammar: Fatal error: Unable to open dictionary.
```

Looks like it's expecting `4.0.dict`, instead of reading the `dict.db`. Am I missing any steps here?

**Comment by ampli** [comment]
I suppose that
`link-parser ./data/demo-sql`
works fine for you.

In that case what you did should have worked fine too (the second `sqlite3` command is even redundant).
In order to debug the problem, please do:
```
file ./data/foo/dict.db
link-parser ./data/foo -verbosity=3
```

**Comment by ampli** [comment]
Contrary to what I originally wrote above, the second `sqlite3` is of course not redundant in order to get a duplicate copy of the dict...
But the dict open succeeded for me in any case.

**Comment by leungmanhin** [comment]
I had the same problem when doing `link-parser ./data/demo-sql`, but the problem disappeared once I upgrade LG to 5.5.1

**Comment by leungmanhin** [comment]
so I'm closing this issue, thanks!
