### ISSUE TITLE
size_t format conversion specifyer on MSVC

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#88]
While checking MSVC-compiled wordgraph version code on Windows (it needs some portability changes), I found that it crashes when verbosity > 1.

It turned out this happens when the code encounters a printf() that has `%zu` format. MSVC just doesn't support it and prints "zu" instead (without the leading %). A format argument mismatch then often happens and causes a crash. In MSVC, the supported format for size_t is `%Iu`.

There are 55 code lines which have %zu in them. They are used for Postscript generation, debug, assert, Info messages and verbosity > 1 problem messages.

Since not using size_t variables - to make the code portable to MSVC, is not a good option, I propose to solve the problem in one of these ways:
1. Use a macro `ZU` that usually expands to `"zu"` but on MSVC expands to `"Iu"`.
2. Use macros (with the same names of the printf variants)  that invoke functions that convert the formats and call the real printf variants).
3. Use %lu and convert each size_t variable with a cast `(unsigned long)` directly of via a macro `UL(s) ((unsigned long)(s))`.

Using solution 1 is simple, but the result is not so nice:
For example, the following line from build_linkage_postscript_string()
` append_string(string,"[%zu %zu %d",`
is to be written in this way:
`append_string(string,"[%"ZU" %"ZU" %d",`

(I don't even want to consider (2)...).

Using solution (3) seems to be the most normal way. I'm for using a macro UL(s), to make less likely the need to break the printing calls to several lines.

Linas, if this is fine by you, I will send you a pull request.
I will then be able to proceed with other MSVC portability fixes.

**Comment by linas** [comment]
solutions 1 and 3 are nasty.  How about this one:

In utilities;h:
```
#ifdef _MSVC
int printf_cmpat(const char *format, ...)
{
   tmp = alloca(strlen(format))
   strcpy(tmp, fomat);
   tok = tmp;
   while (tok = strtok(tok, "%zu")) tok[1] = 'I';
   printf(tmp, ...)
}

#define printf printf_compat
#endif
```

**Comment by linas** [comment]
sorry strstr not strtok

**Comment by linas** [comment]
oh and of course  `va_list args; va_start(args, format); printf(tmp, args); va_end(args);`

**Comment by linas** [comment]
I updated the example into code that probably compiles and should work.

**Comment by ampli** [comment]
The drawback of this method is that it causes an overhead in any printf usage, not only the ones that use %zu. But it is only for Windows, so never mind :).

I thing that the *printf_compat functions should better be in a ".c" file, since else they need to be static, and their private copy will be in almost every C /C++ file. (In any case, they cannot be inlined if they contain alloca(), and most probably would not be inlined anyway due to the vararg).

I found that there is a need for at least 2 variants:
 - sprintf() (used with %zu at least in sat_encoder.cpp).
 - printf()

Also, additional ones may be a good idea:
 - fprintft() (I used it with %zu, I can change it to another variant but it is a source for future problems)
 - snprintft() (could not found evidences it can be used with %zu, but maybe).
 
The following is used but not with %zu: wprintf().

In addition, the format conversion code needs to be added to:
 - verr_msg() 
 - append_string()

I will try to do it.

**Comment by linas** [comment]
OK, one more fix is needed.  I really don't want printf_compat in the public API.   If link-parser.c is using %zu somewhere, lets just change that.

**Comment by ampli** [comment]
I can change that if you tell me how.
The *printf_compat() #define's are in utilities.h, which is included in command_line.c.
This exposes them when _MSC_VER is defined.
Due to that they are required in link-parser program linkage..

The question is how to disable this exposure without a strange hack.

**Comment by linas** [comment]
Hmm. Ideally, link-parser.c should not include the "private" files utilities.h, error.h   Surely, there is very little in utilities.h that link-parser.c actually needs ...

**Comment by ampli** [comment]
1. Maybe the things that link-parser needs can be isolated into another header file.
2. Alternatively, a special definitions like LINKGRAMMAR_LIB can be defined when compiling the library (but not link-parser), to be used to protect things that should be private to the library.

In option (1), a header file (named, e.g, linkgrammar-application.h) can include only what link-parser needs.
However, some of these things may be needed also by the library, so this name may be a misnomer (because this file will be needed by the library too).
Option (2) seems to me easier to implement.

Which one, if any, to choose?

Do you know what link-parser needs from utilities.h, and especially from error.h?
(I guess I can try to comment out their inclusion to see what the errors are...)

**Comment by linas** [comment]
No, both of those sulutions are too complicated.  This does not have to be over-engineered.  From what I can tell, one only needs to #include <malloc.h> and <string.h> and that should be enough ... let me try.

**Comment by linas** [comment]
I just pushed a simple fix: it removes utilities.h and add stdlib.h and string.h which was all that was missing.

**Comment by ampli** [comment]
Ok, I will try now to remove the public API definitions.

**Comment by ampli** [comment]
You also removed the inclusion of regex-tokenizer.h. Do you want me to remove the regex-tokenizer test  from command-line.c, or can this include be returned?

**Comment by linas** [comment]
I assumed the regex tokenizer was old dead code ... what is it?

**Comment by ampli** [comment]
It seems to me this idea can be explored more, i.e. to try a separate_word() that uses it.
However, it can indeed be removed from the link-parser program since for my tests I can apply it as a patch to command-line.c whenever needed. Or maybe the test code itself can remain and I will just add the header if I needed it.

**Comment by linas** [comment]
I don't remember what it did, and I can't imagine why it would be needed in command-line.c instead of in tokenize.c

**Comment by ampli** [comment]
The following is now missing in command_line.c when compiling on Windows:
```
#define inline _inline
#define strcasecmp _stricmp
#define strncasecmp(a,b,s) strnicmp((a),(b),(s))
```
Also, the removal of `#define nl_langinfo(X) ""` from utilities.h causes the following error in tokenize.c:
`..\link-grammar\tokenize.c(2514): error C2065: 'CODESET' : undeclared identifier`

When I defined the missing MSVC definitions in  command_line.c, and re-added nl_langinfo(X) to utilities.h, everything then is compiled fine.

I can include this in the next Windows pull request (I also have a fix to my fix of for the size_t format).


Not related to that (it existed before all of these changes), there is the following compilation warning on MSVC:
```
link-parser.obj : warning LNK4217: locally defined symbol issue_special_command imported in function special_command
```
I think this is because of the **link_public_api** prepend to the issue_special_command() prototype in command-line.h (that is defined as `__declspec(dllimport)`). This seems to me like an error - this function is not imported from a dll, but is just a function from another file that is linked together. Removing this prepended definition solves this warning problem, with no bad effects. So I would include it too (in a separate commit).

(I eventually would like to solve all the MSVC warnings.)

**Comment by ampli** [comment]
Regarding the regex-tokenizer:
It can tokenize a word, or even a whole sentence at once, according to a regex definition that can refer to affix class definitions, dictionary words, and regex names in the regex files, and also tag the results (a SUF, PRE, UNIT, LPUNC etc.)

Its inclusion in command-line.c enabled testing it from the command line, in order to explore its capabilities.

Regarding my previous message:
I will send you a fix for nl_langinfo() that defined it in tokenize.c, that only place that needs its definition on MSVC (without it there is a compilation error).

**Comment by linas** [comment]
I just pushed fixes for these. Today, it was easier to make these changes than to talk about them.

If there are other msvc warnings, they should probably go into a new bug report, this one is getting long.
