### ISSUE TITLE
Misleading message printed by autogen.sh

### ISSUE THREAD

**Issue by stefan-reich** [opencog/link-grammar#894]
This is on Peppermint Linux.

```
checking for stdatomic.h... checking for stdatomic.h... yes
../configure: line 17793: syntax error near unexpected token `,:'
../configure: line 17793: `			AX_TLS(,:)'

Now type 'make' to compile link-grammar.
stefan@stefan-quadcore ~/dev/link-grammar-link-grammar-5.6.0 $ make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by stefan-reich** [comment]
Ah, apt install autoconf-archive solved it. No way to improve the error message maybe?

**Comment by stefan-reich** [comment]
You should improve this message too...

[Now type 'make' to compile link-grammar.
stefan@stefan-quadcore ~/dev/link-grammar-link-grammar-5.6.0 $ make
make: *** No targets specified and no makefile found.  Stop.](url)

What one needs to do next is call ./configure, not make.

**Comment by ampli** [comment]
> Ah, apt install autoconf-archive solved it. No way to improve the error message maybe?

I didn't find a way to improve it.
A solution is welcome.

> What one needs to do next is call ./configure, not make.

It seems this can be fixed. I will look at it.

**Comment by linas** [comment]
As a general rule, using the tarball is recommended, vs. pilling from git. The code in git can sometimes be unstable; the tarballs are guaranteed to pass unit tests.

**Comment by stefan-reich** [comment]
I'm using the release as indicated by the directory name

Am Mi., 6. Feb. 2019 23:37 hat Linas Vepštas <notifications@github.com>
geschrieben:

**Comment by linas** [comment]
The tarballs, and the documentation, are located here:  https://www.abisource.com/projects/link-grammar/ This github repo has no documentation in it, so you'll be lost, if that's all you look at.

**Comment by stefan-reich** [comment]
Surely these releases are also good to use? https://github.com/opencog/link-grammar/releases

**Comment by linas** [comment]
> Surely these releases are also good to use? https://github.com/opencog/link-grammar/releases

No. That is an undesirable github "feature" that I don't know how to turn off or correct. Github calls them releases, but they're not, and there does not seem to be any (pallatable) way of fixing them to actually be releases. (There are some bogus, cure-is-worse-than-disease type fixes)

**Comment by ampli** [comment]
I just sent a fix.
BTW, it turns out that after installing `autoconf-archive`, there is a need to rerun `./autogen.sh` (running `./configure' will still just give the same error again).
