### ISSUE TITLE
Redistributable binaries

### ISSUE THREAD

**Issue by stefan-reich** [opencog/link-grammar#897]
Hi.

One of the ways in which we have to advance computer science for AI is making distribution of programs simpler.

Suppose I want to ship the link parser binary to users of Linux, Mac OS or Windows. How would I do this? I don't even have a Mac myself...

**Comment by ampli** [comment]
On many Linux distributions, especially the main ones, you can install it using the distributions package manager.
On Mac you can install it with the Homebrew package manager.
For native Windows I don't have a solution besides compiling it yourself. However, you can enable the "Windows subsystem for Linux" and install it with a package manager there.

**Comment by linas** [comment]
Google knows all.  

On Linux systems based on Debian, you would say `sudo apt-get install link-grammar`  

For Linux systems based on RPM, try here: http://rpmfind.net/linux/rpm2html/search.php?query=link-grammar 

For Apple MacOS you'd use homebrew: https://formulae.brew.sh/formula/link-grammar

For Microsoft, no clue. Whatever it is that they do. My impression is that windows users are clueless.  Or at least, google doesn't have any answers to that question.

For Android, not supported; no one has ever tried android.
