### ISSUE TITLE
Current pp_prune() problems

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#912]
I rewrote `pp_prune()` and intend to send a PR soon, with the description of the new algo.
Here I would like to document the problems of the current one:

1. It is rather inefficient. Instead of checking each connector name only once, it repeats checking the same names tens/hundreds of time each. The overhead is of course very high.
2. It doubles the overhead of (1) by doing a totally useless second pass (see (3)), which cannot prune anything.
The reason is that it neglects to actually clean the `cms` table. It only subtracts reference counts, but for nothing but added overhead since they are never consulted on table lookup... This is so from the first version of pp_prune().
3. The second pass just unmarks exactly the same disjuncts of the first pass.
4. Even if fixed to actually delete entries from the `cms` table, this mainly adds overhead since the second pass usually removes nothing (>99.9% of the times) sometimes 1 disjunct and very seldom a few more. This is because the trigger links are not usually also criterion links. So this just adds more overhead.
5. The code contains a bug: Usually it only passes over the first rules and neglects the other ones.
This is due to the handling of `deleteme`: It breaks out of the loop in order to mark a deletion, forgetting to scan the rest of rules! Fortunately, the first rules are (most probably deliberately) the once that have the best change to work. So fixing this bug in the current code just adds much overhead...
6. Its checking method for must-contain links is buggy in that it allows triggers that don't have the needed criterion links and the actual implementation also has an unneeded overhead. For example, this rule:
` Ws    ,  D##w  S##w   H                    , "S-V inversion required5" ,`
The current code makes these matches (from a debug printout):
```
match_in_cms_table: S### Sa*v
match_in_cms_table: S### Sa*v
match_in_cms_table: S##w S**w

match_in_cms_table: D### D**w
match_in_cms_table: D### D**w
match_in_cms_table: D##w D**w
```
Not only that it does some checks more than once (due to the already included  `#`), but also some of its checks are satisfied by irrelevant connectors (like `Sa*v`).
This is from the code comments:
`Say bar="Xabc".  Then we see if there are connector  names that post_process_match "Xa##", "X#b#", and "X##c".`
So the above method would be wrongly satisfied by the following: `Xafg`,  `Xfbg`, `Xfgc` even though they cannot create `Xabc`.

I implemented it in a strict way: On each position of a criterion link, if it is a letter then it is required that there will be at list one connector with this letter at this position, and the others positions may exactly match or be `*`. `post_process_check()` doesn't fit the task of checking that, so I wrote a similar function to do that.

As a result, **if you currently comment out** the invocation of `pp_prune()`, the "basic" /"fixes" batch run ~15% **faster**.
However, long sentences still benefit from it ("fix-long" runs 8% slower without it). `pp_prune()` also has a benefit of reducing the chance for overflows, increasing the good linkages density on overflows and the number of good linkages per given `linkage_limit`, so it is still a good idea that it is included even in its current form (also for short sentences).

I already rewrote it to check each connector name only once, and it became 100x  (or more) faster for  sentences which are not very short. In its new form, it adds good net speedup even for the "basic" /"fixes" batches. Its speedup for the "fix-long" batch is ~13%.
```
 2.494000 -   2.0900 =   -0.4040 +19.3%    data/en/corpus-basic.batch
 7.404000 -   6.1580 =   -1.2460 +20.2%    data/en/corpus-fixes.batch
```
The `ru` batch got slightly slowed down by my incorporating of the pp_prune() disjunct discarding in `power_prune()`. I will check how to mitigate that, but anyway `power_prune()` can still have major efficiency improvements so I may leave that for a later work.

My WIP currently includes my tries to fix the problems of the current code (as described above) which made it to work correctly but with even more overhead. So I will remove these commits from the PR and include only the new code (also because there is no point to validate their full correctness by rigorous checks).

**Comment by linas** [comment]
:-) Awesome. What more can I say?
