### ISSUE TITLE
More connector terminology

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#928]
Currently I use the following terms for the recently introduced code:
1. Trailing Connectors sequence.
2. Connector Suffix ID.
3. Trailing Connectors sequence hash/hashing (generating and using Connector Suffix IDs)
4. Trailing connectors sequence sharing (sharing memory for Trailing connector sequences).
5. Sentence/disjunct/connector packing (putting disjunct and connectors in sequential memory, when "sentence packing" is the whole process.

I am now trying to make changes (for efficiency) in the existing code of this stuff, and also try to introduce something resembles the combination of jets and Trailing Connector sequence for faster pruning (to be able to add more pruning methods without too much overhead).
So maybe we can introduce a better terminology in this opportunity.

For example:
- Should (1) be "Trailing Connector list"? Or maybe "Trailing jets"?
- Should (2) be "Connector hash ID" (but then it doesn't hint on suffix or trail)? Or "Trailing jet ID"?

**Comment by linas** [comment]
What, exactly, is a "trailing connector sequence"? Are there ever any "leading connector sequences"?

**Comment by ampli** [comment]
> What, exactly, is a "trailing connector sequence"? Are there ever any "leading connector sequences"?

It is a connector sequence (in a jet) that starts at any connector and ends with the deepest one. It is identified by its "suffix_id" number. In addition, all the "trailing connector sequence" share their memory in the parsing step to reduce its CPU cache footprint. Recently I found that a variation of such a sharing can be used to further speed up pruning (a WIP), but the problem is there is much overhead to do this sharing before the pruning (creating jet memory-sharing has much less overhead).

There is also a "leading connector sequence", that starts with the shallow one and may end at any connector. It could be used for speedup but I don't know how to do that with low enough overhead.
(A jet is both a leading and a trailing connector sequence. The "suffix_id" of its shallow connector is used to identify it.)

**Comment by linas** [comment]
When I hear the word "deepest", my gut instinct is to think "starts at the deepest and moves up to the shallower end"  because mentally, it "feels right" to think of the deepest connectors as being somehow invariant or rooted.  But of course, if you are parsing, its kind of the exact opposite: you connect up the shallowest connectors first, and then try to go deeper and deeper.   That mental model places the shallowest connectors at "the head", and the rest "trail behind".

So, perhaps, instead of saying "trailing", how about saying "remaining"? It's what remains, after making the simplest connections.

One can invent new words: "tracon" or "remcon". I think "tracon" sounds nicer. Just explain what "tracon" actually means. I cannot think of any existing English words that would describe "trailing connector sequence", and aren't wildly over-used and easily misunderstood - queue? pattern? template? joint?  Some word from this list: https://www.popularwoodworking.com/tools/woodworking-glossary/ ?

**Comment by ampli** [comment]
More observations that can maybe give a wider picture:

> if you are parsing, its kind of the exact opposite: you connect up the shallowest connectors first, and then try to go deeper and deeper.

It is interesting to note that on power-pruning, you start to with the deepest connector first, finding the nearest word it could match. Then you do the same with the less deeper connector, and so on. In this case you start with what I called "trailing connectors". In that context, "remaining" seems to be very confusing....

The connector "suffix_id" enumeration and memory-sharing procedure also starts with the deeper connectors first (for string creation efficiency).

> [...]. That mental model places the shallowest connectors at "the head", and the rest "trail behind".
The shallowest connectors are at "the head" also because the direction of the "next" pointers.

The SAT-parser also uses the terms "trailing connectors" and "leading connectors", but for their position in the expression.

> One can invent new words: "tracon" or "remcon". I think "tracon" sounds nicer.

In any case we also need some name instead of suffix_id. "tracon_id"?
And the process of assigning it "tracon enumeration"?
And for the method used for endpoint hashing "tracon hashing"?

**Comment by linas** [comment]
> In any case we also need some name instead of suffix_id. "tracon_id"?
> And the process of assigning it "tracon enumeration"?
> And for the method used for endpoint hashing "tracon hashing"?

Seems reasonable to me.

**Comment by ampli** [comment]
When I need to use the term "tracon" in a comment, should I spell it as **tracon** or **Tracon**?

**Comment by ampli** [comment]
> When I need to use the term "tracon" in a comment, should I spell it as **tracon** or **Tracon**?

It seems to me Tracons is more appropriate so this is what I actually used when I rewrote the original comments.
 
Here is the comment block about Tracons. It includes the details on how the pruning became faster (mainly because the connector sharing by Tracons is much greater than the one using Jets).
I guess that some things may not be clear at all (but it is hard for me to find what needs a further clarification). Your comments are of course welcome.
``` text
/*
 * sentence_pack() copies the disjuncts and connectors to a continuous
 * memory block. This facilitate a better memory caching for long
 * sentences.
 *
 * In addition, it shares the memory of identical trailing connector
 * sequences, aka "Tracons". Tracons are considered identical if they
 * belong to the same Gword (or same word for the pruning step) and
 * contain identical connectors in the same order. Connectors are
 * considered identical if they have the same string representation
 * (including "multi" and the direction mark) with an additional
 * requirement if the packing is done for the pruning step - shallow and
 * deep connectors are then not considered identical (because shallow
 * connectors can match any connectors, while deep connectors can match
 * only shallow connectors). Note: For efficiency, the actual connector
 * string representation is not used for connector comparison.
 *
 * Identical Tracons are assigned a unique Tracon ID, which is kept in
 * their first connector. The rest of their connectors also have
 * Tracon IDs, which belong to Tracons starting with that connectors.
 *
 * For the pruning step, more things are done:
 * Additional data structure - a Tracon list - is constructed, which
 * includes a Tracon table and per-word prune table sizes. These data
 * structure consists of 2 identical parts - one for each Tracon
 * direction (left/right). The Tracon table is indexed by (tracon_id -
 * 1), and it indexes the connectors memory block (it doesn't use
 * pointers in order to save memory on 64-bit CPUs because it may
 * contain in the order of 100K entries for very long sentences).
 * Also, a refcount field is set for each Tracon to tell how many
 * Tracons are memory-shared at that connector address.
 *
 * Tracons are used differently in the pruning and parsing steps.
 *
 * Pruning:
 * The first connector of each Tracon is inserted into the connector
 * tables, along with its reference count. When a connector cannot be
 * matched, its means that all the disjuncts that contain its Tracon
 * cannot be matched. When it is marked as bad, due to the Tracon memory
 * sharing all the connectors that share the same memory are marked
 * simultaneously, and thus are detected when the next disjuncts are
 * examined without a need to further check them. The Tracon IDs are
 * not directly used in the pruning algo - they are only used for
 * the Tracon sharing and for indexing the Tracon list.
 *
 * Parsing:
 * Originally, the classic parser memoized the number of possible
 * linkages per a given connector-pair using connector addresses. Since
 * an exhaustive search is done, such an approach has two main problems
 * for long sentences:
 * 1. A very big count hash table (Table_connector in count.c) is used
 * due to the huge number of connectors (100Ks) in long sentences, a
 * thing that causes a severe CPU cache trash (to the degree that
 * absolutely most of the memory accesses are L3 misses).
 * 2. Repeated linkage detailed calculation for what seemed identical
 * connectors. A hint for the Tracon idea was the use of 0 hash values for
 * NULL connectors, which is the same for all the disjuncts of the same
 * word.
 *
 * The idea that is implemented here is based on the fact that the
 * number of linkages between the same words using any of their
 * connector-pair endpoints is governed only by these connectors and the
 * connectors after them (since cross links are not permitted). Using
 * Tracon IDs as the hash keys allows us to share the memoizing table
 * counts between connectors that start the same Tracons. As a
 * result, long sentences have significantly less different connector
 * hash values than their total number of connectors.
 *
 * In order to save the need to cache and check the endpoint word
 * numbers the Tracon IDs should not be shared between words. They also
 * should not be shared between alternatives since connectors that belong
 * to disjuncts of different alternatives may have different linkage
 * counts because some alternatives-connectivity checks (to the middle
 * disjunct) are done in the fast-matcher.
 *
 * The Tracon memory sharing is currently not directly used in the
 * parsing algo besides reducing the needed CPU cache by a large factor.
 *
 * Algo of generating Tracon Ids, shared Tracons and the Tracon list:
 * The string-set code has been adapted (see tracon-set.c) to hash
 * Tracons. The tracon-set hash table slots are Connector pointers which
 * point to the memory block of the sentence connectors. When a Tracon
 * is not found in the hash table, a new Tracon ID is assigned to it,
 * and the Tracon is copied to the said connector memory block. However,
 * if it is found, its address is used instead of copying the
 * connectors, thus sharing its memory with identical Tracons. The
 * tracon-set hash table is cleared after each word (for pruning Tracons)
 * or Gword (for parsing Tracons), thus ensuring that the Tracons IDs are
 * not shared between words (or Gwords).
 */
```

**Comment by linas** [comment]
What, exactly, is a "trailing connector sequence"? 

The above explains how to tell if they are identical, how to prune them, how to assign ID's to them, etc. but does not explain what they actually are. Explain what they are, give a few examples.  e.g. "a tracon is a sequence of connectors, all having the same direction, where the left-most connector has already been connected to form a link, and the remaining connectors have not yet been connected. For example for blah blah A+ B+ C+ the tracon is blah blah B+ C+".  Or something like that.

**Comment by ampli** [comment]
Say this is the disjunct list (having 2 disjuncts) as printed by print_disjunct_list(d):
```
<--> A+ B+ C+
<--> B+ C+
```
Lets call the first disjunct d1 and the second one d2.
So in that case `d1->left==NULL` and `d1->right==A+'.

In the  first disjunct we have 3 tracons:
d1:
t11: `A+ B+ C+`
t12: `B+ C+`
t13: `C+`
In the second disjunct we have 2 tracons:
d2:
t21: `B+ C+`
t22: `C+`

**That's all I can say on the definition of tracon.** The possible connection of their connectors don't belong to the definition. It belongs to their properties. But these properties are already described.

Here is the description (extracted from my post above) of how they are used in the **parsing** stage:
```
 * The idea that is implemented here is based on the fact that the
 * number of linkages between the same words using any of their
 * connector-pair endpoints is governed only by these connectors and the
 * connectors after them (since cross links are not permitted).
```
A connector and the connectors after it is a tracon, so maybe I should add:
```
 * I.e. the number of linkages depends only on the endpoint tracons. If they are identical
 * then the number of linkages would be the same, totally independent on the connectors
 * that are before these tracons on the same jet.
```
(So I need also to include here the definition for jet.)

Here is the description (also from the post above) of how they are used in the **pruning** stage:
```
 * [...] When a connector cannot be
 * matched, its means that all the disjuncts that contain its Tracon
 * cannot be matched. 
```
Should I add an example like that?
```
 * E.g. if d1 and d2 are:
 * d1: <--> A+ B+ C+ D+
 * d2: <--> B+ C+ D+
 * and C+ cannot match a connector on any word following its word, than both of these
 * disjuncts cannot match [ is there a better word than "match" for disjuncts? ] and can
 * be discarded.
```
BTW, there is also a null tracon (the ending NULL of a connector sequence) and it is the only tracon that is used by the original `do_count()` code. I wondered why explicit connector addresses are used (i.e. a different address for each disjunct, e.g. even if the jets are identical) while for the ending NULL only a single address is used (NULL) independent on the disjunct. The tracon was a generalization of that NULL usage.

(By now I found a wider generalization of tracon equality, and it seems this will lead to an additional parsing speedup. But I would like first to release my current WIP even if I will then need to heavily modify it yet again, else this would be an endless private work...)

**Comment by ampli** [comment]
BTW, I see you wrote it is "tracon" and not "Tracon". So I will do that too.

**Comment by linas** [comment]
> That's all I can say on the definition of tracon. 

Fine. I'm not asking you to explain it to me, right here, right now; I'm asking you to make sure that it is explained in thee code somewhere. I'm not sure where, or which file, but somewhere near the top of some main file, where future maintainers are likely to see it.

> I see you wrote it is "tracon" and not "Tracon". 

In German, it would always be a capital T. In English, both upper and lower-case are allowed. Upper-case if its a proper name, a trademarked name, name of a product or name of a globally-unique identity (something of which there is only one in the world, like Europe, or CERN)  For software, its ambiguous. If journalists and youtube stars were calling you to ask about Tracon, I would recommend a capital T.  But for code documentation, lower-case t is easier to read, it doesn't hurt the eyes as much. It's also easier to type.

**Comment by ampli** [comment]
By now I fixed most/all of the places that need to use the new terminology.
(I will fix the rest, if any, when I encounter them.)
