### ISSUE TITLE
Fixing the word-graph display feature

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#93]
While it works fine on Linux, and even works on Windows when compiling with MSVC if it runs under Cygwin/X, it doesn't work on pure Windows. It also has some design problems. All of these can be fixed.

I would like to send two sets of pull requests:
1. Fixes for the design problems.
2. Fixes for compiling and and running under pure Windows (when Graphviz for Windows is installed - it has a turnkey installation package).

**Comment by linas** [comment]
Sure. Why are you asking me?  I don't think you need to open a bug report before you create a pull request.
