### ISSUE TITLE
ubuntu 18.04 install issue with 5.6.0

### ISSUE THREAD

**Issue by cpsoft123** [opencog/link-grammar#930]
I downloaded version 5.6.0, and did:

> mkdir build
> cd build
> ../configure --prefix=/home/chuck/pub
> make
> make check
> make install

All appeared to be OK up until the make install part.  I got many errors complaing about -fPIC, for example:

> /usr/bin/ld: /home/chuck/pub/lib/libpython2.7.a(bytes_methods.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: /home/chuck/pub/lib/libpython2.7.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> libtool:   error: error: relink '_clinkgrammar.la' with the above command before installing it
> Makefile:505: recipe for target 'install-pkgpyexecLTLIBRARIES' failed
> make[3]: *** [install-pkgpyexecLTLIBRARIES] Error 1

For reference, after the config I saw:

> 
> link-grammar-5.6.0  build configuration settings
> 
> 	prefix:                         /home/chuck/pub
> 	datadir:                        ${prefix}/share
> 	C compiler:                     gcc  -D_DEFAULT_SOURCE -std=c11 -D_BSD_SOURCE -D_SVID_SOURCE -D_GNU_SOURCE -D_ISOC11_SOURCE -g -O2 -O3
> 	C++ compiler:                   g++  -D_DEFAULT_SOURCE -std=c++11 -g -O2 -O3 -Wall
> 	Regex library:                  
> 	TLS:                            yes
> 	Editline command-line history:  no
> 	UTF8 editline support:          no
> 	Java libraries:                 yes
> 	Java interfaces:                no
> 	Swig interfaces generator:      no
> 	Perl interfaces:                no
> 	Perl install location:          
> 	Python2 interfaces:             2.7 (/usr/bin/python)
> 	Python3 interfaces:             3.6 (/usr/bin/python3)
> 	ASpell spell checker:           no
> 	HunSpell spell checker:         no
> 	HunSpell dictionary location:   
> 	Boolean SAT parser:             yes (using the bundled minisat library)
> 	SQLite-backed dictionary:       yes
> 	Corpus statistics database:     no
> 	RegEx tokenizer:                
> 	Definitions:                    -DPACKAGE_NAME=\"link-grammar\" -DPACKAGE_TARNAME=\"link-grammar\" -DPACKAGE_VERSION=\"5.6.0\" -DPACKAGE_STRING=\"link-grammar\ 5.6.0\" -DPACKAGE_BUGREPORT=\"https://github.com/opencog/link-grammar\" -DPACKAGE_URL=\"https://www.abisource.com/projects/link-grammar\" -DPACKAGE=\"link-grammar\" -DVERSION=\"5.6.0\" -DYYTEXT_POINTER=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_STRNDUP=1 -DHAVE_STRTOK_R=1 -DHAVE_ALIGNED_ALLOC=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -DHAVE_PRCTL=1 -D__STDC_FORMAT_MACROS=1 -D__STDC_LIMIT_MACROS=1 -DHAVE_LOCALE_T_IN_LOCALE_H=1 -DHAVE_STDATOMIC_H=1 -DTLS=_Thread_local -DHAVE_MKLIT=1 -DUSE_SAT_SOLVER=1 -DUSE_WORDGRAPH_DISPLAY=1 -DHAVE_SQLITE=1 -DHAVE_REGEX_H=1 -DHAVE_REGEXEC=1 -DHAVE_MAYBE_UNINITIALIZED=1
> 	Libraries:                       -lsqlite3 
>

**Comment by ampli** [comment]
From the error message you got:
> /usr/bin/ld: /home/chuck/pub/lib/libpython2.7.a(bytes_methods.o): [...]

Note that it tries to link against a Python library in your home directory.
Also note that this is a static library. If this privately-installed python has been compiled statically, it cannot be used here.

From your configuration settings summary:
> Python2 interfaces: 2.7 (/usr/bin/python)

Note that the configuration uses the system python.

In a try to solve these things, if you must use python2 then install a dynamically-linked python2 and add in front of your PATH the directory of its python binary (and then `configure` again).

If you don't have python3 installed in your home directory and you prefer using python3 over python2 (recommended), you may try to install with `make -k install` in a hope that the python3 bindings will not have a problem (or alternatively,  configure with `--enable-python-bindings=3` so the python2 bindings will not be generated).

BTW (not related to this problem):
>UTF8 editline support: no

Adding it will make the use of  `link-parser` more convenient.

**Comment by linas** [comment]
What @ampli says. Also, please note that the `-fPIC` suggestion is meant to apply to your python libraries, not to link-grammar. "PIC" is "Position Independent Code" and is mandatory for shared libraries; the error and resulting suggestion is because you don't have a shared library available for python2; the compiler tried as best it could with the static lib, but it was not enough to get usable python2 bindings.

**Comment by linas** [comment]
Also as @ampli points out, mixing together system python:
> Python2 interfaces: 2.7 (/usr/bin/python)
> Python3 interfaces: 3.6 (/usr/bin/python3)

with local python:
> /home/chuck/pub/lib/libpython2.7

is an almost sure-fire guarantee that things will get broken, for a very simple reason: your local libpython will almost surely not be compatible with the system libpython (due to differing version numbers) resulting in any number of strange and confounding errors.  You're encountering what is called "DLL hell".

**Comment by cpsoft123** [comment]
Thanks for your help, an install in a clean environment indeed works for me.
