### ISSUE TITLE
wordgraph throws no such file

### ISSUE THREAD

**Issue by sbguthery** [opencog/link-grammar#990]
The following throws 

Link-Grammar: Error: execlp of dot: No such file or directory

when link-parser is run locally (i.e. not installed).

!verbosity=0
!islands-ok
!links
!graphics=1
!echo
!limit=1
!morphology
!wordgraph=1
Bob went to the store and found a carrot in lane fifteen.

**Comment by ampli** [comment]
For wordgraph display support on Linux you need to have the `graphviz` package installed.
This package provides the missing `dot` program.

I will add something like `(may need to install the "graphviz" package)` to this error.
